### ISSUE TITLE
Windows 10 Install Error: "RuntimeError: Error compiling objects for extension"

### ISSUE THREAD

**Issue by MrTornado24** [facebookresearch/pytorch3d#1028]
### Environment
windows 10 

cuda 11.3

python 3.9

pytorch 1.10.1 with cuda 11.3

### Full error information
```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\projects\pytorch3d-0.6\setup.py", line 132, in <module>
    setup(
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\distutils\command\build_ext.py", line 529, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 708, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1399, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\admin\anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

### My installing steps
I installed following [B200011011's answer](https://stackoverflow.com/questions/62304087/installing-pytorch3d-fails-with-anaconda-and-pip-on-windows-10)

- Create conda enviroment, install torch and dependencies
```
conda create -n pytorch3d python=3.9
conda activate pytorch3d
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
```
- Set correct path to cl.exe Visual C++ compiler and other environment variables

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x86
```
```
PYTORCH3D_NO_NINJA 1
CUB_HOME C:\portable\cub-1.11.0
```
- Open "X64 Native Tools Command Prompt for VS 2019" as root and move into pytorch3d folder and run `python setup.py install`.

**Comment by MrTornado24** [comment]
This issue has been solved by comment out `-std=c++14"` in `nvcc_args`. Moreover, though `from pytorch3d import _c` still fails, it works normally in my code.

**Comment by apolinario** [comment]
@MrTornado24, where are those `nvcc_args` that you commented out `-std=c++14`?
