### ISSUE TITLE
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Sibylle-Van-Hove** [facebookresearch/pytorch3d#1060]
When running a third-party python script I am getting this error:
```
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 25, in <module>
    from decalib.deca import DECA
  File "/data/Workbench/AvatarTech/deca/deca-20210805/decalib/deca.py", line 27, in <module>
    from .utils.renderer import SRenderY
  File "/data/Workbench/AvatarTech/deca/deca-20210805/decalib/utils/renderer.py", line 23, in <module>
    from pytorch3d.io import load_obj
  File "/home/gpu/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/io/__init__.py", line 8, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/home/gpu/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/io/obj_io.py", line 22, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/home/gpu/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/home/gpu/anaconda3/envs/deca-env/lib/python3.7/site-packages/pytorch3d/renderer/blending.py", line 11, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory
```

This seems to be the same error reported in [Issue 923](https://github.com/facebookresearch/pytorch3d/issues/923) but I'm still having issues (possibly a version mismatch somewhere).

These are the commands I ran to install the dependencies for the third-party python script & for installing pytorch3d:

```
conda create --name test-env python=3.7
conda activate test-env
pip install -r requriements.txt
conda install -c pytorch pytorch=1.9.1 torchvision cudatoolkit=10.2
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
conda install pytorch3d -c pytorch3d
```

The requirements.txt file requests the following versions:
```
numpy>=1.18.5
scipy>=1.4.1 
chumpy>=0.69
scikit-image>=0.15 
opencv-python>=4.1.1 
scikit-image>=0.15
PyYAML>=5.1.1         
torch==1.7.0
torchvision==0.8.1
face-alignment
```

This is the result from the environments `conda list`:
```
# packages in environment at /home/gpu/anaconda3/envs/test-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aom                       3.2.0                h9c3ff4c_2    conda-forge
blas                      1.0                         mkl
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cffi                      1.15.0           py37h036bc23_0    conda-forge
chumpy                    0.70                     pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cudatoolkit               10.2.89             h8f6ccaa_10    conda-forge
dataclasses               0.6                      pypi_0    pypi
face-alignment            1.3.5                    pypi_0    pypi
ffmpeg                    4.4.1                h6987444_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py37h89c1867_4    conda-forge
fvcore                    0.1.5.post20210915            py37    fvcore
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
imageio                   2.14.1                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561
iopath                    0.1.9                      py37    iopath
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0            12_linux64_mkl    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libdrm                    2.4.109              h7f98852_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpciaccess              0.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.18.1               h780b84a_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuv                     1.43.0               h7f98852_0    conda-forge
libva                     2.13.0               h7f98852_2    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvmlite                  0.38.0                   pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py37h402132d_0    conda-forge
mkl_fft                   1.3.1            py37h3e078e5_1    conda-forge
mkl_random                1.2.2            py37h219a48f_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_1    conda-forge
numba                     0.55.1                   pypi_0    pypi
numpy                     1.21.5                   pypi_0    pypi
numpy-base                1.21.2           py37h79a1101_0
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.5.5.62                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pillow                    9.0.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
portalocker               2.3.2            py37h89c1867_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7                    pypi_0    pypi
python                    3.7.12          hf930737_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.9.1           cpu_py37hf3cc979_3    conda-forge
pytorch3d                 0.6.1           py37_cu102_pyt191    pytorch3d
pywavelets                1.2.0                    pypi_0    pypi
pyyaml                    6.0              py37h5e8e339_3    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scikit-image              0.19.1                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                60.5.0           py37h89c1867_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
svt-av1                   0.9.0                h9c3ff4c_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.11               h27826a3_1    conda-forge
torch                     1.7.0                    pypi_0    pypi
torchvision               0.8.1                    pypi_0    pypi
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
x264                      1!161.3030           h7f98852_1    conda-forge
x265                      3.5                  h4bd325d_1    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

This is the result from `conda info`:
```
     active environment : test-env
    active env location : /home/gpu/anaconda3/envs/test-env
            shell level : 2
       user config file : /home/gpu/.condarc
 populated config files : /home/gpu/.condarc
          conda version : 4.11.0
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.2=0
                          __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/gpu/anaconda3  (writable)
      conda av data dir : /home/gpu/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/gpu/anaconda3/pkgs
                          /home/gpu/.conda/pkgs
       envs directories : /home/gpu/anaconda3/envs
                          /home/gpu/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.22.0 CPython/3.7.6 Linux/4.15.0-166-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

This is the output I get from `torch.cuda.is_enabled()`
```
>>> import torch
>>> torch.cuda.is_enabled()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.cuda' has no attribute 'is_enabled'
```

**Comment by bottler** [comment]
The conda list looks odd in terms of pytorch. The official pytorch build should be a package called `pytorch` from the pytorch channel and the build string should show the cuda version. It shows you have a package called `pytorch` from `conda-forge`, which I think is an unofficial CPU-only build of pytorch. You also have the `torch` package from pypi. You want neither, and I think one or both of these is the problem.

What is `requirements.txt`?

[The error references the `deca-env` environment not `test-env`. I assume you get the same error in the test env (which is where you ran the other commands).]

**Comment by Sibylle-Van-Hove** [comment]
Hi yes sorry the error was for the `test-env`.
Yes it seems to work now. I installed pytorch, torchvision & the corresponding cudatoolkit first, then installed pytorch3d & then installed the requirements for the third-party code (these requirements were specified in `requirements.txt`).

**Comment by Klawens** [comment]
followed the install guid step by step, and still having this problem
