### ISSUE TITLE
Running "setup.py install" not working

### ISSUE THREAD

**Issue by Eliso7777** [facebookresearch/pytorch3d#1099]
I keep getting this error when running "setup.py install":

```
C:/Users/eliso/.conda/envs/pytorch3d/lib/site-packages/torch/include\c10/util/Optional.h(526): note: see reference to alias template instantiation 'c10::OptionalBase<c10::cuda::impl::CUDAGuardImpl>' being compiled
C:/Users/eliso/.conda/envs/pytorch3d/lib/site-packages/torch/include\c10/core/impl/InlineStreamGuard.h(231): note: see reference to class template instantiation 'c10::optional<T>' being compiled
        with
        [
            T=c10::cuda::impl::CUDAGuardImpl
        ]
C:/Users/eliso/.conda/envs/pytorch3d/lib/site-packages/torch/include\c10/cuda/CUDAGuard.h(292): note: see reference to class template instantiation 'c10::impl::InlineMultiStreamGuard<c10::cuda::impl::CUDAGuardImpl>' being compiled
C:/Users/eliso/.conda/envs/pytorch3d/lib/site-packages/torch/include\c10/util/Optional.h(418): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
        with
        [
            T=c10::cuda::impl::CUDAGuardImpl
        ]
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\eliso\discoAI4\pytorch3d\setup.py", line 132, in <module>
    setup(
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\distutils\command\build_ext.py", line 529, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 708, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1399, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\eliso\.conda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

There is a lot more than just that, there's over 1,000 lines of that error.

**Comment by bottler** [comment]
There isn't any detail here about what the root cause error is. Two possibilities

(1) There is actually a compilation error. You can look if there is a log file from the build, and search it for the word "error". If you retry, setting the environment variable PYTORCH3D_NO_NINJA to 1 the build will be slower and less distributed, and the error might appear in the output, which might make it easier to find.

(2) The build is running in parallel and running out of memory. Then the PYTORCH3D_NO_NINJA setting above could just fix it. Or, if you have many cores, you could set the environment variable MAX_JOBS to a small number.

**Comment by bottler** [comment]
@RobinLiuZX Please look for new files in the build directory. Also can you try my suggestions earlier?

**Comment by RobinLiuZX** [comment]
**C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/include\thrust/system/cuda/config.h(79): fatal error C1189: #error:  The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit status 2**
@bottler  Thank you for your patience. After I set it, it appeared on the problem, and I saw your help again.
