### ISSUE TITLE
Installation Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by qsisi** [facebookresearch/pytorch3d#1155]
Hello! I had the following problems when I was trying to build pytorch3d-0.6.0 from source. 

Environments:

**OS: ubuntu16.04
CUDA: 10.2
GCC: 7.3.0**

Commands (due to the unstable network condition, I choose to install pytorch using pre-built wheels.)

```
conda create -n pytorch3d python=3.6
conda activate pytorch3d
pip install torch-1.10.0+cu102-cp36-cp36m-linux_x86_64.whl
pip install torchvision-0.11.0+cu102-cp36-cp36m-linux_x86_64.whl
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
cd pytorch-0.6.0
pip install -e .
```

Then I get at least thousands of lines of error output messages, at the bottom of these messages look like this:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ghn/RegTR/pytorch3d-0.6.0/setup.py", line 150, in <module>
        "": ["*.json"],
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
        build_ext.build_extensions(self)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 565, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/ghn/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ghn/anaconda3/envs/pytorch3d/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ghn/RegTR/pytorch3d-0.6.0/setup.py'"'"'; __file__='"'"'/home/ghn/RegTR/pytorch3d-0.6.0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

Could someone help me with this? Thanks!

**Comment by bottler** [comment]
You need to install pytorch and torchvision via conda if you want to install pytorch3d via conda. This is because conda packages depend on conda packages.
