### ISSUE TITLE
How can I install PyTorch3D correctly **with GPU support**?

### ISSUE THREAD

**Issue by yd-yin** [facebookresearch/pytorch3d#1161]
I'm trying hard to run [implicitron_trainer](https://github.com/facebookresearch/pytorch3d/tree/main/projects/implicitron_trainer), only to find `RuntimeError: Not compiled with GPU support.` (The stack trace is attached at the end.)

I've cloned the latest PyTorch3D repo and followed [the instructions](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) to install PyTorch3D from a local clone.  My scripts to install PyTorch3D is like
```bash
conda create -n co3d python=3.8
conda activate co3d 
conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=10.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
```
And I have PyTorch GPU-supported
```python
>>> import torch
>>> torch.cuda.is_available()
True
```

Then how can I install PyTorch3D properly **with GPU support**? And how can I check if it is GPU supported?

Thanks a lot!

```bash
Traceback (most recent call last):
  File "experiment.py", line 715, in experiment
    run_training(cfg, device)
  File "experiment.py", line 498, in run_training
    trainvalidate(
  File "experiment.py", line 380, in trainvalidate
    preds = model(**{**net_input, "evaluation_mode": EvaluationMode.TRAINING})
  File "/DATA/disk1/yinyingda/miniconda3/envs/co3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATA/disk1/yinyingda/codes/PyTorch3D/pytorch3d/implicitron/models/base.py", line 407, in forward
    rendered = self._render(
  File "/DATA/disk1/yinyingda/codes/PyTorch3D/pytorch3d/implicitron/models/base.py", line 554, in _render
    return self.renderer(
  File "/DATA/disk1/yinyingda/miniconda3/envs/co3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATA/disk1/yinyingda/codes/PyTorch3D/pytorch3d/implicitron/models/renderer/multipass_ea.py", line 136, in forward
    return self._run_raymarcher(
  File "/DATA/disk1/yinyingda/codes/PyTorch3D/pytorch3d/implicitron/models/renderer/multipass_ea.py", line 163, in _run_raymarcher
    fine_ray_bundle = self._refiners[evaluation_mode](ray_bundle, weights)
  File "/DATA/disk1/yinyingda/miniconda3/envs/co3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATA/disk1/yinyingda/codes/PyTorch3D/pytorch3d/implicitron/models/renderer/ray_point_refiner.py", line 67, in forward
    z_samples = sample_pdf(
  File "/DATA/disk1/yinyingda/codes/PyTorch3D/pytorch3d/renderer/implicit/sample_pdf.py", line 57, in sample_pdf
    _C.sample_pdf(
RuntimeError: Not compiled with GPU support.

```

**Comment by yd-yin** [comment]
`FORCE_CUDA=1` works for me. Thanks!

I think the installation guidance could still be clearer, though

**Comment by bottler** [comment]
This is confusing. FORCE_CUDA shouldn't have been needed - If `CUDA_HOME` is set and `torch.cuda.is_available()` it should be automatic. Could you have built from the wrong environment?

**Comment by yd-yin** [comment]
Thanks for the response. It is because I did not set `CUDA_HOME`.

I would recommend a way to explicitly specify the CPU / GPU version, or offer some method to test, just like `torch.cuda.is_available()`. Thanks!

**Comment by codeHorasan** [comment]
I am having the same issue but I don't know where should I write "FORCE_CUDA=1"

**Comment by bottler** [comment]
@codeHorasan (It's better to open a new issue than commenting a new question on an old issue.) It's an environment variable, and how you set it depends on your operating system.

In linux in the shell, you can write `FORCE_CUDA=1` at the beginning of a command - e.g. `FORCE_CUDA=1 pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"`, where the command is building the latest release from source.

In Windows in the relevant command prompt, one way is to run the command `set FORCE_CUDA=1` on its own and that affects future commands in that prompt.

**Comment by sinAshish** [comment]
I get the same error when I try to install pytorch3d inside my docker container, that is then converted to `singularity` image to run on slurm clusters..
Error persists even after setting correct `CUDA_HOME` paths, and `FORCE_CUDA=1` in my docker config
```
torch==1.12.1+cu113
pytorch-lightning==1.7.5
```
No conda env.
I use `RUN pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable` cmd to install py3d.

**Comment by bottler** [comment]
@sinAshish Please open a new issue with full details. This issue is old and closed.

**Comment by axbycc-mark** [comment]
Someone built pre-compiled packages that you can pip install. More info here https://github.com/facebookresearch/pytorch3d/discussions/1752
