### ISSUE TITLE
Error building from source On Linux torch1.8.1/CUDA11.1/ gcc 9.4.0/clang version 10.0.0-4ubuntu1

### ISSUE THREAD

**Issue by BianFeiHu** [facebookresearch/pytorch3d#1196]
## 🐛 Bugs / Unexpected behaviors
Failed building from source with message "subprocess.CalledProcessError: Command '['which', 'clang++-9']' returned non-zero exit status 1."

I cloned the source code and installed nvidiacub、fvcore and iopath using conda. Then i typed "pip install -e ." and encountered error the full message is as follows.

× python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [48 lines of output]
        running develop
        running egg_info
        writing pytorch3d.egg-info/PKG-INFO
        writing dependency_links to pytorch3d.egg-info/dependency_links.txt
        writing entry points to pytorch3d.egg-info/entry_points.txt
        writing requirements to pytorch3d.egg-info/requires.txt
        writing top-level names to pytorch3d.egg-info/top_level.txt
        reading manifest file 'pytorch3d.egg-info/SOURCES.txt'
        writing manifest file 'pytorch3d.egg-info/SOURCES.txt'
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/data/feihu/AD-NeRF-master/pytorch3d-main/setup.py", line 159, in <module>
            "": ["*.json"],
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/distutils/core.py", line 148, in setup
            dist.run_commands()
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/distutils/dist.py", line 966, in run_commands
            self.run_command(cmd)
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
            self.run_command('build_ext')
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
            _build_ext.run(self)
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/distutils/command/build_ext.py", line 339, in run
            self.build_extensions()
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
            self._check_abi()
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
            check_compiler_abi_compatibility(compiler)
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
            if not check_compiler_ok_for_platform(compiler):
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
            which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/subprocess.py", line 389, in check_output
            **kwargs).stdout
          File "/home/feihu/.conda/envs/adnerf/lib/python3.7/subprocess.py", line 481, in run
            output=stdout, stderr=stderr)
        subprocess.CalledProcessError: Command '['which', 'clang++-9']' returned non-zero exit status 1.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Can't roll back pytorch3d; was not uninstalled
error: subprocess-exited-with-error

And the test environment is "torch1.8.1" "CUDA11.1"  "gcc 9.4.0"  "clang version 10.0.0-4ubuntu1"

**Comment by bottler** [comment]
This doesn't seem specific to PyTorch3D, I think you'd suffer this problem building any PyTorch extensions in this environment. For some reason it expects clang++-9 to exist and it doesn't. You want version 10 to be used, not 9. Could you check your environment variables? Maybe some of them are pointing at clang++-9.
