### ISSUE TITLE
RuntimeError: CUDA error: __global__ function call is not configured

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/pytorch3d#1204]
```
/pytorch3d/transforms/transform3d.py", line 162, in __init__
    self._matrix = torch.eye(4, dtype=dtype, device=device).view(1, 4, 4)

```

there was something wrong inside __global__ call? install from latest git also tried stable.

this is not pytorch side issue.

**Comment by bottler** [comment]
Can you include all the output with the error, and a stack trace? And try again with the environment variable CUDA_LAUNCH_BLOCKING=1 as well, which may give a better stack trace.

**Comment by d4l3k** [comment]
I'm also running into this issue. The stack trace is the same w/ CUDA_LAUNCH_BLOCKING.

```
Traceback (most recent call last):
  File "/mnt/ext/env/train/train.py", line 177, in <module>
    losses = model(batch, global_step)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/ext/env/train/models/van.py", line 378, in forward
    rendered_images, rendered_silhouettes = self.renderer(cameras=cameras, volumes=volumes)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/renderer/implicit/renderer.py", line 248, in forward
    return self.renderer(
  File "/home/rice/venvs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/renderer/implicit/renderer.py", line 157, in forward
    ray_bundle = self.raysampler(
  File "/home/rice/venvs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/renderer/implicit/raysampling.py", line 200, in forward
    return _xy_to_ray_bundle(
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/renderer/implicit/raysampling.py", line 553, in _xy_to_ra
y_bundle
    unprojected = cameras.unproject_points(to_unproject, from_ndc=True)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/renderer/cameras.py", line 1138, in unproject_points
    to_camera_transform = self.get_full_projection_transform(**kwargs)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/renderer/cameras.py", line 234, in get_full_projection_tr
ansform
    return world_to_view_transform.compose(view_to_proj_transform)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/transforms/transform3d.py", line 211, in compose
    out = Transform3d(dtype=self.dtype, device=self.device)
  File "/home/rice/venvs/env/lib/python3.10/site-packages/pytorch3d/transforms/transform3d.py", line 162, in __init__
    self._matrix = torch.eye(4, dtype=dtype, device=device).view(1, 4, 4)
RuntimeError: CUDA error: __global__ function call is not configured
```

dtype and device are `torch.float32 cuda:0` which is very odd.

Running with nightly pytorch and pytorch3d compiled from master

**Comment by d4l3k** [comment]
Running with torch 1.11 avoids that error and instead I got some (correct) mismatched device errors. Might be a regression in core PT?
