### ISSUE TITLE
Install Pytorch3D on Mac M1 Chip

### ISSUE THREAD

**Issue by mkhoshle** [facebookresearch/pytorch3d#1210]
Hello,

Recently, there has been a new PyTorch release that supports GPU computation on Mac M1 ([here](https://pytorch.org/get-started/locally/)). I also want to install pytorch3d on my machine. Is there GPU support for mac m1 for pytorch3d by any chance?

I would really appreciate it if you could let me know about this.
Thank you,

**Comment by bottler** [comment]
PyTorch3D does not support GPU on mac. I would imagine that you can build PyTorch3D from source in the usual way for CPU-only use on the M1.

**Comment by BotScutters** [comment]
@bottler Running PyTorch3D on Apple Silicon hardware is definitely something my team is interested in. We've got it built for CPU-only and running just fine now, but does the PyTorch3D team have any plans to add support for using the GPU on Silicon hardware? Thanks!

**Comment by AsaphLightricks** [comment]
My team is also interested in running pytorch3d on apple GPU (M1)

**Comment by geyang** [comment]
We need a CPU only wheel for M1 Macs so that we can do the development locally. 

What is the plan for PyTorch3D in this regard?

**Comment by nicolasfischoeder** [comment]
PyTorch on m1 gpus would be great! I also need that one

**Comment by bottler** [comment]
This is unlikely to happen soon. Can you build PyTorch3D from source CPU-only on your M1? If you can, I would expect it to work.

**Comment by nicolasfischoeder** [comment]
Thank you for your fast response. How would I do that?

**Comment by ericlitman** [comment]
Any particular technical or market driven reason behind this?

**Comment by matiasfreitas** [comment]
I want to know as well how to run pyttorch 3d in a mac m1

**Comment by malhotraa** [comment]
+1 for pytorch3d using gpus on m1 mac. It would be great.

**Comment by SeriousSamV** [comment]
How do I build Pytorch3d from source?

`MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"` doesn't work! :(

```
(venv) ➜  pytorch3d git:(main) ✗ MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"
Collecting git+https://github.com/facebookresearch/pytorch3d.git
  Cloning https://github.com/facebookresearch/pytorch3d.git to /private/var/folders/3v/b9w_0wg94g1bks0gczcvm4dm0000gn/T/pip-req-build-0ofua0nc
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorch3d.git /private/var/folders/3v/b9w_0wg94g1bks0gczcvm4dm0000gn/T/pip-req-build-0ofua0nc
  Resolved https://github.com/facebookresearch/pytorch3d.git to commit 7aeedd17a4140eef139987e946a7017df7a97433
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/samuel/workspace/python/pytorch3d/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/samuel/workspace/python/pytorch3d/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/samuel/workspace/python/pytorch3d/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/3v/b9w_0wg94g1bks0gczcvm4dm0000gn/T/pip-build-env-yfvvuirw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/3v/b9w_0wg94g1bks0gczcvm4dm0000gn/T/pip-build-env-yfvvuirw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/3v/b9w_0wg94g1bks0gczcvm4dm0000gn/T/pip-build-env-yfvvuirw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/3v/b9w_0wg94g1bks0gczcvm4dm0000gn/T/pip-build-env-yfvvuirw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ohadkorenok** [comment]
Hi, are there any news with this? I would like to run it on my computer!!

**Comment by bottler** [comment]
@SeriousSamV Looks like an environment problem. torch needs to be installed.

@ohadkorenok As mentioned, it should be fine to build yourself. Just that the GPU will not be used.

**Comment by guochengqian** [comment]
it gives error when installing cpu-only version using the following command: 
```
MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"
```

```
        File "/Users/gqian/miniconda3/envs/angre/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects
```

Note this happens even with  `pip install pyproject-toml` installed. 

gcc version: 
```
gcc --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by TMAstrider** [comment]
@guochengqian do you solved the issue

**Comment by adrianariton** [comment]
Had the same error and solved it by using `virtualenv` installed with `pipx`
