### ISSUE TITLE
import error  :    from pytorch3d import _C

### ISSUE THREAD

**Issue by sytest7** [facebookresearch/pytorch3d#1315]
Traceback (most recent call last):
  File "inference.py", line 9, in <module>
    from renderer import Estimator3D
  File "/content/Occlusion-Robust-3D-Face-CFR-GAN/renderer.py", line 19, in <module>
    from pytorch3d.renderer import TexturesVertex
  File "/usr/local/lib/python3.7/dist-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from pytorch3d.renderer.blending import BlendParams,hard_rgb_blend,sigmoid_alpha_blend,softmax_rgb_blend
  File "/usr/local/lib/python3.7/dist-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: /usr/local/lib/python3.7/dist-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

**Comment by bottler** [comment]
This is usually due to a mismatch in the version of pytorch which pytorch3d was built with and the version of pytorch which you have at runtime. How did you install pytorch and how did you install pytorch3d?

**Comment by bottler** [comment]
This is usually due to a mismatch in the version of pytorch which pytorch3d was built with and the version of pytorch which you have at runtime. How did you install pytorch and how did you install pytorch3d?

**Comment by cocoshe** [comment]
> This is usually due to a mismatch in the version of pytorch which pytorch3d was built with and the version of pytorch which you have at runtime. How did you install pytorch and how did you install pytorch3d?

I have the same error.And I install pytorch by `conda install pytorch==1.8.0`, and install pytorch3d by `conda install pytorch3d`

**Comment by cocoshe** [comment]
> > This is usually due to a mismatch in the version of pytorch which pytorch3d was built with and the version of pytorch which you have at runtime. How did you install pytorch and how did you install pytorch3d?
> 
> I have the same error.And I install pytorch by `conda install pytorch==1.8.0`, and install pytorch3d by `conda install pytorch3d`

I just solve the error, I just use `pip uninstall torch`, and find that the pytorch 1.12.1 is uninstalled. But when I use `conda list` and find this 
![JOQMC{RDGFV}3W$(%05T)1R](https://user-images.githubusercontent.com/69197635/190648579-f57657a2-4d2e-402d-8769-59d4d2ab8dee.png)

However, I just uninstall the torch, then there is no error when I import pytorch3d.
But I don't know why, maybe someone can explain it?

**Comment by SCZwangxiao** [comment]
I met the same problem when installing pytorch3d using `conda`. Just install the package from the source.
```bash
pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"
```
