### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch3d.implicitron_trainer'

### ISSUE THREAD

**Issue by keloee** [facebookresearch/pytorch3d#1318]
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch3d/bin/pytorch3d_implicitron_runner", line 33, in <module>
    sys.exit(load_entry_point('pytorch3d', 'console_scripts', 'pytorch3d_implicitron_runner')())
  File "/root/anaconda3/envs/pytorch3d/bin/pytorch3d_implicitron_runner", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/root/anaconda3/envs/pytorch3d/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/root/anaconda3/envs/pytorch3d/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked

I build the code with 95771985b7ac14dae4606d799e82703b530d4e0c successfully but still got an error when try to use the shell command pytorch3d_implicitron_runner and it reported the above error

**Comment by cinamon123** [comment]
It seems that your directory is blank.
Please check your conda-envs. The package 'pytorch3d/implicitron_runner' is available or not. In conda-envs, the structure of packages is different from that in github.

**Comment by ghy0324** [comment]
Hi @keloee  I met the same problem, have you solved it?
