### ISSUE TITLE
bugs of install pytorch on linux

### ISSUE THREAD

**Issue by surheaven** [facebookresearch/pytorch3d#1356]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
version: Linux version 5.4.0-124-generic (buildd@lcy02-amd64-019) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #140~18.04.1-Ubuntu SMP Fri Aug 5 11:43:34 UTC 2022
python==3.6.8
conda install pytorch==1.7.0 torchvision==0.8.0 cudatoolkit=11.0 -c pytorch

when i run pip install "git+https://github.com/facebookresearch/pytorch3d.git", get a bug :

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-0hd18ba2/setup.py", line 178, in <module>
        "": ["*.json"],
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
        build_ext.build_extensions(self)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
  Rolling back uninstall of pytorch3d
  Moving to /home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/pytorch3d
   from /home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/~ytorch3d
  Moving to /home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/pytorch3d-0.6.1-py3.6.egg-info
   from /home/user/anaconda3/envs/Avatar/lib/python3.6/site-packages/~ytorch3d-0.6.1-py3.6.egg-info
ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/Avatar/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0hd18ba2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0hd18ba2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rc3j_9q4/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/Avatar/include/python3.6m/pytorch3d Check the logs for full command output.

**Comment by bottler** [comment]
There should be a log file (eg error_log.txt) with more information about what went wrong. Search it for "error " and "error:". If you don't see any errors, then probably this is a case of running out of memory during the build. Try the build again with the environment variable `PYTORCH3D_NO_NINJA` set to 1.
