### ISSUE TITLE
_C.rasterize_meshes incompatible function arguments

### ISSUE THREAD

**Issue by xiao-lin-hub** [facebookresearch/pytorch3d#1412]
This is a question about using pytorch3d for actual projects.I extracted the key code from the actual project to better find errors.
**The main program code is as follows**
```
import torch
from render_3dmm import Render_3DMM

dir_path = r"E:\AD-NeRF-master\AD-NeRF-master\data_util\face_tracking"
arg_focal = 1100
id_dim, exp_dim, tex_dim, point_num = 100, 79, 100, 34650
h = 450
w = 450
batch_size = 50
device_render = torch.device('cuda:0')
renderer = Render_3DMM(arg_focal, h, w, batch_size, device_render)
rott_geo = torch.rand([50, 34650, 3])
sel_texture = torch.rand([50, 34650, 3])
sel_light = torch.rand([50, 27])
render_imgs = renderer.forward(rott_geo.to(device_render), sel_texture.to(device_render), sel_light.to(device_render))
```

**The render_3dmm code is as follows**

```
import torch
import torch.nn as nn
import numpy as np
import os

from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    PerspectiveCameras,
    FoVPerspectiveCameras,
    PointLights,
    DirectionalLights,
    Materials,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    SoftPhongShader,
    TexturesUV,
    TexturesVertex,
    blending
)

from pytorch3d.ops import interpolate_face_attributes

from pytorch3d.renderer.blending import (
    BlendParams,
    hard_rgb_blend,
    sigmoid_alpha_blend,
    softmax_rgb_blend,
)


class SoftSimpleShader(nn.Module):
    """
    Per pixel lighting - the lighting model is applied using the interpolated
    coordinates and normals for each pixel. The blending function returns the
    soft aggregated color using all the faces per pixel.

    To use the default values, simply initialize the shader with the desired
    device e.g.

    """

    def __init__(
        self, device="cpu", cameras=None, lights=None, materials=None, blend_params=None
    ):
        super().__init__()
        self.lights = lights if lights is not None else PointLights(
            device=device)
        self.materials = (
            materials if materials is not None else Materials(device=device)
        )
        self.cameras = cameras
        self.blend_params = blend_params if blend_params is not None else BlendParams()

    def to(self, device):
        # Manually move to device modules which are not subclasses of nn.Module
        self.cameras = self.cameras.to(device)
        self.materials = self.materials.to(device)
        self.lights = self.lights.to(device)
        return self

    def forward(self, fragments, meshes, **kwargs) -> torch.Tensor:

        texels = meshes.sample_textures(fragments)
        blend_params = kwargs.get("blend_params", self.blend_params)

        cameras = kwargs.get("cameras", self.cameras)
        if cameras is None:
            msg = "Cameras must be specified either at initialization \
                or in the forward pass of SoftPhongShader"
            raise ValueError(msg)
        znear = kwargs.get("znear", getattr(cameras, "znear", 1.0))
        zfar = kwargs.get("zfar", getattr(cameras, "zfar", 100.0))
        images = softmax_rgb_blend(
            texels, fragments, blend_params, znear=znear, zfar=zfar
        )
        return images


class Render_3DMM(nn.Module):
    def __init__(self, focal=1015, img_h=500, img_w=500, batch_size=1, device=torch.device('cuda:0')):
        super(Render_3DMM, self).__init__()

        self.focal = focal
        self.img_h = img_h
        self.img_w = img_w
        self.device = device
        self.renderer = self.get_render(batch_size)

        dir_path = os.path.dirname(os.path.realpath(__file__))
        topo_info = np.load(os.path.join(
            dir_path, '3DMM', 'topology_info.npy'), allow_pickle=True).item()
        self.tris = torch.as_tensor(topo_info['tris']).to(self.device)
        self.vert_tris = torch.as_tensor(
            topo_info['vert_tris']).to(self.device)

    def compute_normal(self, geometry):
        vert_1 = torch.index_select(geometry, 1, self.tris[:, 0])
        vert_2 = torch.index_select(geometry, 1, self.tris[:, 1])
        vert_3 = torch.index_select(geometry, 1, self.tris[:, 2])
        nnorm = torch.cross(vert_2-vert_1, vert_3-vert_1, 2)
        tri_normal = nn.functional.normalize(nnorm, dim=2)
        v_norm = tri_normal[:, self.vert_tris, :].sum(2)
        vert_normal = v_norm / v_norm.norm(dim=2).unsqueeze(2)
        return vert_normal

    def get_render(self, batch_size=1):
        half_s = self.img_w * 0.5
        R, T = look_at_view_transform(10, 0, 0)
        R = R.repeat(batch_size, 1, 1)
        T = torch.zeros((batch_size, 3), dtype=torch.float32).to(self.device)

        cameras = FoVPerspectiveCameras(device=self.device, R=R, T=T, znear=0.01, zfar=20,
                                        fov=2*np.arctan(self.img_w//2/self.focal)*180./np.pi)
        lights = PointLights(
            device=self.device,
            location=[[0.0, 0.0, 1e5]],
            ambient_color=[[1, 1, 1]],
            specular_color=[[0., 0., 0.]],
            diffuse_color=[[0., 0., 0.]]
        )
        sigma = 1e-4
        raster_settings = RasterizationSettings(
            image_size=(self.img_h, self.img_w),
            blur_radius=np.log(1. / 1e-4 - 1.)*sigma / 18.0,
            faces_per_pixel=2,
            perspective_correct=False,
        )
        blend_params = blending.BlendParams(background_color=[0, 0, 0])
        renderer = MeshRenderer(
            rasterizer=MeshRasterizer(
                raster_settings=raster_settings,
                cameras=cameras
            ),
            shader=SoftSimpleShader(
                lights=lights,
                blend_params=blend_params,
                cameras=cameras
            ),
        )

        return renderer.to(self.device)

    @staticmethod
    def Illumination_layer(face_texture, norm, gamma):

        n_b, num_vertex, _ = face_texture.size()
        n_v_full = n_b * num_vertex
        gamma = gamma.view(-1, 3, 9).clone()
        gamma[:, :, 0] += 0.8

        gamma = gamma.permute(0, 2, 1)

        a0 = np.pi
        a1 = 2 * np.pi / np.sqrt(3.0)
        a2 = 2 * np.pi / np.sqrt(8.0)
        c0 = 1 / np.sqrt(4 * np.pi)
        c1 = np.sqrt(3.0) / np.sqrt(4 * np.pi)
        c2 = 3 * np.sqrt(5.0) / np.sqrt(12 * np.pi)
        d0 = 0.5 / np.sqrt(3.0)

        Y0 = torch.ones(n_v_full).to(gamma.device).float() * a0 * c0
        norm = norm.view(-1, 3)
        nx, ny, nz = norm[:, 0], norm[:, 1], norm[:, 2]
        arrH = []

        arrH.append(Y0)
        arrH.append(-a1 * c1 * ny)
        arrH.append(a1 * c1 * nz)
        arrH.append(-a1 * c1 * nx)
        arrH.append(a2 * c2 * nx * ny)
        arrH.append(-a2 * c2 * ny * nz)
        arrH.append(a2 * c2 * d0 * (3 * nz.pow(2) - 1))
        arrH.append(-a2 * c2 * nx * nz)
        arrH.append(a2 * c2 * 0.5 * (nx.pow(2) - ny.pow(2)))

        H = torch.stack(arrH, 1)
        Y = H.view(n_b, num_vertex, 9)
        lighting = Y.bmm(gamma)

        face_color = face_texture * lighting
        return face_color

    def forward(self, rott_geometry, texture, diffuse_sh):
        face_normal = self.compute_normal(rott_geometry)
        face_color = self.Illumination_layer(texture, face_normal, diffuse_sh)
        face_color = TexturesVertex(face_color)
        mesh = Meshes(rott_geometry, self.tris.float().repeat(
            rott_geometry.shape[0], 1, 1), face_color)

        rendered_img = self.renderer(mesh)
        rendered_img = torch.clamp(rendered_img, 0, 255)

        return rendered_img
```
ERROR ：

```
Traceback (most recent call last):
  File "E:/AD-NeRF-master/AD-NeRF-master/data_util/face_tracking/test0.py", line 28, in <module>
    render_imgs = renderer.forward(rott_geo.to(device_render), sel_texture.to(device_render), sel_light.to(device_render))
  File "E:\AD-NeRF-master\AD-NeRF-master\data_util\face_tracking\render_3dmm.py", line 192, in forward
    rendered_img = self.renderer(mesh)
  File "E:\Anaconda\envs\tr\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda\envs\tr\lib\site-packages\pytorch3d-0.6.0-py3.7-win-amd64.egg\pytorch3d\renderer\mesh\renderer.py", line 59, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "E:\Anaconda\envs\tr\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda\envs\tr\lib\site-packages\pytorch3d-0.6.0-py3.7-win-amd64.egg\pytorch3d\renderer\mesh\rasterizer.py", line 203, in forward
    cull_to_frustum=raster_settings.cull_to_frustum,
  File "E:\Anaconda\envs\tr\lib\site-packages\pytorch3d-0.6.0-py3.7-win-amd64.egg\pytorch3d\renderer\mesh\rasterize_meshes.py", line 246, in rasterize_meshes
    cull_backfaces,
  File "E:\Anaconda\envs\tr\lib\site-packages\pytorch3d-0.6.0-py3.7-win-amd64.egg\pytorch3d\renderer\mesh\rasterize_meshes.py", line 320, in forward
    cull_backfaces,
TypeError: rasterize_meshes(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: std::tuple<int,int>, arg5: float, arg6: int, arg7: int, arg8: int, arg9: bool, arg10: bool, arg11: bool) -> std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor>

Invoked with: tensor([[[ 21.5609, -10.5920,  -0.2041],
         [  3.8227, -21.4536,  -0.0762],
         [ 11.4958, -10.2565,  -0.2256]],

        [[ 21.5609, -10.5920,  -0.2041],
         [ 11.4958, -10.2565,  -0.2256],
         [  4.4152,  -5.2979,  -0.6546]],

        [[  3.8227, -21.4536,  -0.0762],
         [  2.3177,  -2.7730,  -0.9041],
         [ 11.4958, -10.2565,  -0.2256]],

        ...,

        [[ 23.1012, -11.9373,  -0.1499],
         [  0.0573,  -1.3546,  -0.7545],
         [  4.0953,  -4.4413,  -0.6042]],

        [[  3.1199,  -8.4308,  -0.2762],
         [  2.3714,  -2.6248,  -0.8423],
         [  5.1089,  -2.7342,  -0.8373]],

        [[ 23.1012, -11.9373,  -0.1499],
         [  4.0953,  -4.4413,  -0.6042],
         [  6.5975,  -8.9232,  -0.1691]]], device='cuda:0'), tensor([      0,   68746,  137492,  206238,  274984,  343730,  412476,  481222,
         549968,  618714,  687460,  756206,  824952,  893698,  962444, 1031190,
        1099936, 1168682, 1237428, 1306174, 1374920, 1443666, 1512412, 1581158,
        1649904, 1718650, 1787396, 1856142, 1924888, 1993634, 2062380, 2131126,
        2199872, 2268618, 2337364, 2406110, 2474856, 2543602, 2612348, 2681094,
        2749840, 2818586, 2887332, 2956078, 3024824, 3093570, 3162316, 3231062,
        3299808, 3368554], device='cuda:0'), tensor([68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746,
        68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746,
        68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746,
        68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746,
        68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746, 68746],
       device='cuda:0'), tensor([-1, -1, -1,  ..., -1, -1, -1], device='cuda:0'), (450, 450), 5.116800203875472e-05, 2, 32, 13749, False, True, False

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.`
```
I tried to check the logic of the code used and found no obvious mistakes. Since I am very interested in pytorch3d but just started learning recently, I don't know if it is the problem of my installation of pytorch3d itself or the code I wrote. mistake.
Hope to get your advice, very grateful ！

**Comment by bottler** [comment]
The error is saying that the internal C++/cuda function `rasterize_meshes` has been called with the wrong argument types (deep inside your call to the renderer). I think the problem here might be that in PyTorch3D, `blur_radius` has to be a Python `float` but you are supplying a numpy special type.

Can you replace 
```
blur_radius=np.log(1. / 1e-4 - 1.)*sigma / 18.0
```
with 
```
blur_radius=math.log(1. / 1e-4 - 1.)*sigma / 18.0
```
(with `import math`) or
```
blur_radius=float(np.log(1. / 1e-4 - 1.)*sigma / 18.0)
```
?

**Comment by bottler** [comment]
Actually, it should cope with `numpy.float64` for the blur_radius fine. I think there might be something wrong with the installation (which means that the tensor arguments are not understood properly). Can you explain how you installed and paste the output of `conda list`?

**Comment by xiao-lin-hub** [comment]
> Actually, it should cope with `numpy.float64` for the blur_radius fine. I think there might be something wrong with the installation (which means that the tensor arguments are not understood properly). Can you explain how you installed and paste the output of `conda list`?

I installed pytorch3d on the windows10 operating system.
I first downloaded pytorch3d-0.6.0 and cub-1.17.2 (I used pytorch3d-0.6.0 +cub-cuda-11.6 and pytorch3d-0.6.2+cub-1.17.2 before, but the above error still exists) , then I add the cub-1.17.2 path as the system variable CUB_HOME, unzip pytorch3d-0.6.2 to "E:\Anaconda\envs\tr\Lib\site-packages" (tr is my virtual environment name). I am in Run the following commands in sequence in x64 Native Tools Command Prompt for VS 2019:
```
set DISTUTILS_USE_SDK=1
set PYTORCH3D_NO_NINJA=1
cd /d E:\Anaconda\envs\tr\Lib\site-packages\pytorch3d
activate tr
python setup.py install
```
(**But I encountered the following error message**)
![屏幕截图 2023-01-03 213416](https://user-images.githubusercontent.com/82574684/210369188-56c40970-6b37-484e-8987-d4b4c2eaceab.png)

So I found the cast.h file in the E:\Anaconda\envs\tr\Lib\sitepackages\torch\include\pybind11 path, and I commented out a few lines of code around 1510:
```
//template <typename T1, typename T2> class type_caster<std::pair<T1, T2>>
// : public tuple_caster<std::pair, T1, T2> {};
//
//template <typename... Ts> class type_caster<std::tuple<Ts...>>
// : public tuple_caster<std::tuple, Ts...> {};
```
部分代码：
```
// Base implementation for std::tuple and std::pair
template <template<typename...> class Tuple, typename... Ts> class tuple_caster {
    using type = Tuple<Ts...>; //**--1433--**
    static constexpr auto size = sizeof...(Ts);
    using indices = make_index_sequence<size>;
public:

    bool load(handle src, bool convert) {
        if (!isinstance<sequence>(src))
            return false;
        const auto seq = reinterpret_borrow<sequence>(src);
        if (seq.size() != size)
            return false;
        return load_impl(seq, convert, indices{});
    }

    template <typename T>
    static handle cast(T &&src, return_value_policy policy, handle parent) {
        return cast_impl(std::forward<T>(src), policy, parent, indices{});
    }

    // copied from the PYBIND11_TYPE_CASTER macro
    template <typename T>
    static handle cast(T *src, return_value_policy policy, handle parent) {
        if (!src) return none().release();
        if (policy == return_value_policy::take_ownership) {
            auto h = cast(std::move(*src), policy, parent); delete src; return h;
        } else {
            return cast(*src, policy, parent);
        }
    }

    static constexpr auto name = _("Tuple[") + concat(make_caster<Ts>::name...) + _("]");

    template <typename T> using cast_op_type = type;

    operator type() & { return implicit_cast(indices{}); }
    operator type() && { return std::move(*this).implicit_cast(indices{}); }

protected:
    template <size_t... Is>
    type implicit_cast(index_sequence<Is...>) & { return type(cast_op<Ts>(std::get<Is>(subcasters))...); }
    template <size_t... Is>
    type implicit_cast(index_sequence<Is...>) && { return type(cast_op<Ts>(std::move(std::get<Is>(subcasters)))...); }

    static constexpr bool load_impl(const sequence &, bool, index_sequence<>) { return true; }

    template <size_t... Is>
    bool load_impl(const sequence &seq, bool convert, index_sequence<Is...>) {
#ifdef __cpp_fold_expressions
        if ((... || !std::get<Is>(subcasters).load(seq[Is], convert)))
            return false;
#else
        for (bool r : {std::get<Is>(subcasters).load(seq[Is], convert)...})
            if (!r)
                return false;
#endif
        return true;
    }

    /* Implementation: Convert a C++ tuple into a Python tuple */
    template <typename T, size_t... Is>
    static handle cast_impl(T &&src, return_value_policy policy, handle parent, index_sequence<Is...>) {
        std::array<object, size> entries{{
            reinterpret_steal<object>(make_caster<Ts>::cast(std::get<Is>(std::forward<T>(src)), policy, parent))...
        }};
        for (const auto &entry: entries)
            if (!entry)
                return handle();
        tuple result(size);
        int counter = 0;
        for (auto & entry: entries)
            PyTuple_SET_ITEM(result.ptr(), counter++, entry.release().ptr());
        return result.release();
    }

    Tuple<make_caster<Ts>...> subcasters;//**--1507--**
};

//template <typename T1, typename T2> class type_caster<std::pair<T1, T2>>
//    : public tuple_caster<std::pair, T1, T2> {};
//
//template <typename... Ts> class type_caster<std::tuple<Ts...>>
//    : public tuple_caster<std::tuple, Ts...> {};

/// Helper class which abstracts away certain actions. Users can provide specializations for
/// custom holders, but it's only necessary if the type has a non-standard interface.
template <typename T>
struct holder_helper {
    static auto get(const T &p) -> decltype(p.get()) { return p.get(); }
};
```
Execute the python setup.py install command again, no error
Successful installation
![安装成功](https://user-images.githubusercontent.com/82574684/210370166-4d320f45-5047-4757-83d7-8742e358ac2c.png)

The conda list is as follows：
```
# Name                    Version                   Build  Channel
(tr) C:\Users\dell>conda list
# packages in environment at E:\Anaconda\envs\tr:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bzip2                     1.0.8                h8ffe710_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2022.10.11           haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
configargparse            1.4                pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudatoolkit               11.1.1              hb074779_11    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
debugpy                   1.6.4                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
face-alignment            1.3.4                    pypi_0    pypi
freetype                  2.12.1               h546665d_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fvcore                    0.1.5.post20221221    pyhd8ed1ab_0    conda-forge
imageio                   2.23.0                   pypi_0    pypi
importlib-metadata        5.2.0                    pypi_0    pypi
intel-openmp              2023.0.0         h57928b3_25922    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
iopath                    0.1.9                      py37    iopath
ipykernel                 6.16.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jpeg                      9e                   h8ffe710_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter-client            7.4.8                    pypi_0    pypi
jupyter-core              4.12.0                   pypi_0    pypi
lerc                      4.0.0                h63175ca_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libblas                   3.9.0              16_win64_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcblas                  3.9.0              16_win64_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libdeflate                1.14                 hcfcfb64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h8ffe710_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libhwloc                  2.8.0                h039e092_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.17                 h8ffe710_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
liblapack                 3.9.0              16_win64_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.39               h19919ed_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.40.0               hcfcfb64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.5.0                hc4f729c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuv                     1.44.2               h8ffe710_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp                   1.2.4                hcfcfb64_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.2.4                h8ffe710_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.10.3               hc3477c8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               hcfcfb64_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
natsort                   7.1.1              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.11.0               h2d74725_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numba                     0.56.4                   pypi_0    pypi
numpy                     1.21.6           py37h2830a78_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
opencv-python             3.4.2.16                 pypi_0    pypi
openssl                   1.1.1s               h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
parso                     0.8.3                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.3.0            py37hdc2b20a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pip                       22.3.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
portalocker               2.6.0            py37h03978a9_0    conda-forge
prompt-toolkit            3.0.36                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pthreads-win32            2.9.1                hfa6e2cd_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pygments                  2.13.0                   pypi_0    pypi
python                    3.7.15               h6244533_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python_abi                3.7                     2_cp37m    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.8.1           py3.7_cuda11.1_cudnn8_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytorch3d                 0.6.0                    pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   305                      pypi_0    pypi
pyyaml                    6.0              py37hcc03f2d_4    conda-forge
pyzmq                     24.0.1                   pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.6.3             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0             pyh6c4a22f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sqlite                    3.40.0               hcfcfb64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.7.0             h91493d7_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
termcolor                 2.1.1              pyhd8ed1ab_0    conda-forge
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h8ffe710_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
torchvision               0.9.1                    pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.8.0                    pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ucrt                      10.0.22621.0         h57928b3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vc                        14.3                 h3d8a991_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.38.4             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.8                h8cc25b3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               hcfcfb64_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zstd                      1.5.2                h7755175_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
```
The pip list is as follows：
```
Package            Version
------------------ ------------------
backcall           0.2.0
colorama           0.4.6
ConfigArgParse     1.4
cycler             0.11.0
debugpy            1.6.4
decorator          5.1.1
entrypoints        0.4
face-alignment     1.3.4
fonttools          4.28.1
fvcore             0.1.5.post20221221
imageio            2.23.0
importlib-metadata 5.2.0
iopath             0.1.9
ipykernel          6.16.2
ipython            7.34.0
jedi               0.18.2
jieba              0.42.1
joblib             1.1.0
jupyter_client     7.4.8
jupyter_core       4.12.0
kiwisolver         1.3.2
llvmlite           0.39.1
matplotlib         3.5.0
matplotlib-inline  0.1.6
natsort            7.1.1
nest-asyncio       1.5.6
networkx           2.6.3
numba              0.56.4
numpy              1.21.6
opencv-python      3.4.2.16
packaging          21.2
pandas             1.3.4
parso              0.8.3
pickleshare        0.7.5
Pillow             8.4.0
pip                22.3.1
portalocker        2.6.0
prompt-toolkit     3.0.36
psutil             5.9.4
Pygments           2.13.0
pyparsing          2.4.7
python-dateutil    2.8.2
pytorch3d          0.6.0
pytz               2021.3
PyWavelets         1.3.0
pywin32            305.1
PyYAML             6.0
pyzmq              24.0.1
scikit-image       0.19.3
scikit-learn       1.0.1
scipy              1.7.3
setuptools         65.6.3
setuptools-scm     6.3.2
six                1.16.0
tabulate           0.9.0
termcolor          2.1.1
threadpoolctl      3.0.0
tifffile           2021.11.2
tomli              1.2.2
torch              1.8.1
torchvision        0.9.1
tornado            6.2
tqdm               4.64.1
traitlets          5.8.0
typing_extensions  4.4.0
wcwidth            0.2.5
wheel              0.38.4
yacs               0.1.8
zipp               3.11.0
```
Thank you very much !

**Comment by xiao-lin-hub** [comment]
> The error is saying that the internal C++/cuda function `rasterize_meshes` has been called with the wrong argument types (deep inside your call to the renderer). I think the problem here might be that in PyTorch3D, `blur_radius` has to be a Python `float` but you are supplying a numpy special type.
> 
> Can you replace
> 
> ```
> blur_radius=np.log(1. / 1e-4 - 1.)*sigma / 18.0
> ```
> 
> with
> 
> ```
> blur_radius=math.log(1. / 1e-4 - 1.)*sigma / 18.0
> ```
> 
> (with `import math`) or
> 
> ```
> blur_radius=float(np.log(1. / 1e-4 - 1.)*sigma / 18.0)
> ```
> 
> ?

I tried modifying the code, but sadly it doesn't seem to work, the error is still exist.

**Comment by bottler** [comment]
The (windows-only, nvcc-only) compile-time error with pybind11 is not the fault of pybind11. If you use an up-to-date checkout of PyTorch3D you should not get the error. See for example #1398 . I think you have modified pybind11 itself to get round the error, and that might be the cause of this issue. I won't dig in to that.

**Comment by xiao-lin-hub** [comment]
> The (windows-only, nvcc-only) compile-time error with pybind11 is not the fault of pybind11. If you use an up-to-date checkout of PyTorch3D you should not get the error. See for example #1398 . I think you have modified pybind11 itself to get round the error, and that might be the cause of this issue. I won't dig in to that (but note that we DO use tuple binding to pass the image size to the rasterizer).

My pytorch3d code runs successfully ！I use version 7.0 ，thanks for your help !
