### ISSUE TITLE
SoftDepthShader: The size of tensor a (2) must match the size of tensor b (201) at non-singleton dimension 3

### ISSUE THREAD

**Issue by dav-ell** [facebookresearch/pytorch3d#1431]
## 🐛 Bugs / Unexpected behaviors

I'm attempting to use `SoftDepthShader` with the tutorial cow_mesh and 200 views, like so:
```python
from pytorch3d.renderer.mesh.shader import SoftDepthShader

raster_settings = RasterizationSettings(
    image_size=128, blur_radius=0.0, faces_per_pixel=1
)

depth_renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
    shader=SoftDepthShader(
        device=device, cameras=cameras, lights=lights, blend_params=blend_params
    ),
)
depths = depth_renderer(meshes, cameras=cameras, lights=lights)

```

and I'm getting an error: 

```bash
Traceback (most recent call last):
  File "fit_textured_volume.py", line 45, in <module>
    target_cameras, target_images, target_silhouettes, target_depths = generate_cow_renders(num_views=200)
  File "/home/odin/odin/perception-3d/generate_cow_renders.py", line 157, in generate_cow_renders
    depths = depth_renderer(meshes, cameras=cameras, lights=lights)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 62, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 442, in forward
    return (probs * dists).sum(dim=3).unsqueeze(3)
RuntimeError: The size of tensor a (2) must match the size of tensor b (201) at non-singleton dimension 3
```

To debug, I copy/pasted the shader from [here](https://github.com/facebookresearch/pytorch3d/blob/a7256e4034376f3e802178da5e8498f8ba184888/pytorch3d/renderer/mesh/shader.py#L400):

```python
class SoftDepthShader(ShaderBase):
    def forward(self, fragments: Fragments, meshes: Meshes, **kwargs) -> torch.Tensor:
        if fragments.dists is None:
            raise ValueError("SoftDepthShader requires Fragments.dists to be present.")

        cameras = super()._get_cameras(**kwargs)

        N, H, W, K = fragments.pix_to_face.shape
        device = fragments.zbuf.device
        mask = fragments.pix_to_face >= 0

        zfar = kwargs.get("zfar", getattr(cameras, "zfar", 100.0))

        # Sigmoid probability map based on the distance of the pixel to the face.
        prob_map = torch.sigmoid(-fragments.dists / self.blend_params.sigma) * mask

        # append extra face for zfar
        dists = torch.cat(
            (fragments.zbuf, torch.ones((N, H, W, 1), device=device) * zfar), dim=3
        )
        probs = torch.cat((prob_map, torch.ones((N, H, W, 1), device=device)), dim=3)

        # compute weighting based off of probabilities using cumsum
        probs = probs.cumsum(dim=3)
        probs = probs.clamp(max=1)
        probs = probs.diff(dim=3, prepend=torch.zeros((N, H, W, 1), device=device))

        return (probs * dists).sum(dim=3).unsqueeze(3)
```

and started a debugger. `probs` is of shape `[200, 128, 128, 2]` and `dists` is of shape `[200, 128, 128, 201]`. My guess is that this bit:

```python
        dists = torch.cat(
            (fragments.zbuf, torch.ones((N, H, W, 1), device=device) * zfar), dim=3
        )
```

was supposed to be something like:

```python
        dists = torch.cat(
            (fragments.zbuf, torch.ones((N, H, W, 1), device=device) * zfar.unsqueeze(1).unsqueeze(2).unsqueeze(3).expand(N, H, W, 1)), dim=3
        )
```

When I use this, I get these:

![target_depth_0195](https://user-images.githubusercontent.com/17986781/215199365-90ee1bea-0186-4de1-bd86-a7c2ad421879.png)
![target_depth_0145](https://user-images.githubusercontent.com/17986781/215199369-41557e39-bd3c-4db0-8cfb-d69184f04551.png)
![target_depth_0095](https://user-images.githubusercontent.com/17986781/215199370-976522ac-0eab-4471-a282-d6efae4c5131.png)
![target_depth_0035](https://user-images.githubusercontent.com/17986781/215199374-0dadbb9b-1fc0-425f-9da2-7d2645eaa145.png)

I'm still working out how to use [fit_textured_volume.ipynb ](https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/fit_textured_volume.ipynb) to learn a density map from the depths, but at least the mesh has depth values now.

**Comment by bottler** [comment]
If you want 200 renders, then `cameras`, `lights` and `meshes` must all be 200-long batches. The renderer is not designed to do broadcasting. I suspect this is the problem.

**Comment by dav-ell** [comment]
Still using the tutorial [fit_textured_volume.ipynb](https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/fit_textured_volume.ipynb) code, I changed the light instantiation in `generate_cow_renders.py` from this:

https://github.com/facebookresearch/pytorch3d/blob/c8af1c45ca9f4fdd4e59b49172ca74983ff3147a/docs/tutorials/utils/generate_cow_renders.py#L108

to this:

```python
    light_locs = [[0.0, 0.0, -3.0] for _ in range(num_views)]
    lights = PointLights(device=device, location=light_locs)
```

where `len(lights)` is now equal to `num_views` instead of 1. But still the same error. Maybe I'm missing something.

@d4l3k any idea?

**Comment by d4l3k** [comment]
Not sure -- you might want to put print statements in the shader to see the shapes

Here's my configs:

```
        sigma = 1e-4 / 3
        raster_settings = RasterizationSettings(
            image_size=(240, 320),
            faces_per_pixel=10,
            blur_radius=np.log(1.0 / 1e-4 - 1.0) * sigma,
            # perspective_correct=False,
        )
        self.rasterizer = MeshRasterizer(
            raster_settings=raster_settings,
        )
        self.shader_depth = SoftDepthShader(
            device=device,
            cameras=cameras,
        )
...
                cameras = CustomPerspectiveCameras(
                    T=T,
                    K=K,
                    image_size=torch.tensor(
                        [[h // 2, w // 2]], device=device, dtype=torch.float
                    ).expand(BS, -1),
                    device=device,
                )
                render_args = dict(
                    cameras=cameras,
                    zfar=100.0,
                    znear=0.2,  # empirically from voxel we don't see closer than 1.3
                    # cull backfaces to prevent the ground becoming the ceiling
                    cull_backfaces=True,
                    eps=1e-8,  # minimum scaling factor for transform_points
                )
                fragments = self.rasterizer(meshes, **render_args)
                depth = self.shader_depth(fragments, meshes, **render_args)[..., 0]
```

I'm not actually setting any lights at all

**Comment by benjamin-dinkelmann** [comment]
I know this is an old issue and can be solved easily with the configuration provided by @d4l3k.

For anyone else, who might be stumped by what's actually the issue:
Both SoftDepthShader and HardDepthShader require zfar as maximal depth. 
If zfar is not provided via kwargs, it is pulled from the cameras. 

`zfar = kwargs.get("zfar", getattr(cameras, "zfar", 100.0))`

Now if there are multiple cameras, zfar is a vector of equal length to the batch dimension.
The code however assumes than zfar is scalar, which is why a broadcasting error occurs.
i.e. in HardDepthShader the mask assignment:

`zbuf[mask] = zfar`

and in SoftDepthShader the dists, which are later multiplied with probs:

```
dists = torch.cat(
            (fragments.zbuf, torch.ones((N, H, W, 1), device=device) * zfar), dim=3
        )
probs = torch.cat((prob_map, torch.ones((N, H, W, 1), device=device)), dim=3)
```

At least for the latter case, it would be relatively straight-forward to apply zfar correctly by reshaping.
