### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by hasan1292** [facebookresearch/pytorch3d#1441]
Hi, when I ran the command to train fern dataset, it threw following error, any idea how to solve it? 
```
(pytorch3d) hasan@hasanpc:~/Downloads/pytorch3d-main/projects/nerf$ python ./train_nerf.py --config-name fern
/home/hasan/Downloads/pytorch3d-main/projects/nerf/./train_nerf.py:26: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path=CONFIG_DIR, config_name="lego")
/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2023-02-09 14:18:10,304][visdom][WARNING] - Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f206f129160>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f206f129160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/visdom/__init__.py", line 692, in _send
    return self._handle_post(
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/visdom/__init__.py", line 656, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f206f129160>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-02-09 14:18:10,312][visdom][WARNING] - Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.
Loading dataset fern, image size=[378, 504] ...
Downloading dataset fern from https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/fern.pth to /home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/../data/fern.pth.
Downloading dataset fern from https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/fern.png to /home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/../data/fern.png.
Downloading dataset fern from https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/fern_license.txt to /home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/../data/fern_license.txt.
Precaching 17 ray bundles ...
[██████████████████████████████]
Precaching 3 ray bundles ...
[██████████████████████████████]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/hasan/Downloads/pytorch3d-main/projects/nerf/./train_nerf.py", line 181, in main
    nerf_out, metrics = model(
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/nerf_renderer.py", line 332, in forward
    chunk_outputs = [
  File "/home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/nerf_renderer.py", line 333, in <listcomp>
    self._process_ray_chunk(
  File "/home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/nerf_renderer.py", line 226, in _process_ray_chunk
    (rgb, weights), ray_bundle_out = self._renderer[renderer_pass](
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/pytorch3d/renderer/implicit/renderer.py", line 160, in forward
    ray_bundle = self.raysampler(
  File "/home/hasan/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/raysampler.py", line 351, in forward
    *[
  File "/home/hasan/Downloads/pytorch3d-main/projects/nerf/nerf/raysampler.py", line 352, in <listcomp>
    v.view(n_pixels, -1)[sel_rays]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by shiqi-dai** [comment]
changing line 352 to 
`v.view(n_pixels, -1)[sel_rays.to("cpu").detach()]`
worked for me

**Comment by shapovalov** [comment]
Please note that projects/nerf is not actively maintained and has known bugs. Please use pytorch3d/implicitron instead.
This may be a good place to start if you need a vanilla NeRF: https://github.com/facebookresearch/pytorch3d/blob/main/projects/implicitron_trainer/configs/overfit_singleseq_nerf_blender.yaml

**Comment by bottler** [comment]
fixed by the mentioned commit
