### ISSUE TITLE
Large numerical errors in PerspectiveCameras.transform_points() on A40 GPUs

### ISSUE THREAD

**Issue by jinlinyi** [facebookresearch/pytorch3d#1466]
## 🐛 Bugs / Unexpected behaviors

The PerspectiveCameras.transform_points() function may produce large numerical errors when running on A40 GPUs, while producing correct results on V100 and 2080Ti GPUs, as well as on CPUs. 

## Instructions To Reproduce the Issue:
1. System environment
```python
Python 3.7.16 (default, Jan 17 2023, 22:20:44)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
'11.3'
>>> torch.__version__
'1.11.0'
>>> import pytorch3d
>>> pytorch3d.__version__
'0.7.1'
```
```bash
> nvidia-smi
Wed Mar  1 09:49:35 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          On   | 00000000:22:00.0 Off |                    0 |
|  0%   30C    P8    30W / 300W |      0MiB / 46068MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
2. Code to replicate the issue
```python
import torch
from pytorch3d.renderer.cameras import PerspectiveCameras
Rs, _ = torch.linalg.qr(torch.randn(3, 3))
Rs = Rs.unsqueeze(0)
Ts = torch.randn(1, 3)
Ks = torch.FloatTensor([
    [ 1.3284,  0.0000,  0.0000,  0.0000],
    [ 0.0000,  1.3284,  0.0000,  0.0000],
    [ 0.0000,  0.0000,  1.0127, -0.1013],
    [ 0.0000,  0.0000,  1.0000,  0.0000]
]).unsqueeze(0)
camera = PerspectiveCameras(R=Rs, T=Ts, K=Ks)
pts = torch.randn(1,10,3)
res1 = camera.transform_points(pts)
res2 = camera.cuda().transform_points(pts.cuda())
torch.testing.assert_allclose(res1, res2.cpu(), rtol=1e-5, atol=1e-5)

```
3. Does not pass assertion test if runs on A40 GPU:
```bash
(py37) ➜ python tools/test_torch_numerical.py
Traceback (most recent call last):
  File "tools/test_torch_numerical.py", line 16, in <module>
    torch.testing.assert_allclose(res1, res2.cpu(), rtol=1e-5, atol=1e-5)
  File "/envs/py37/lib/python3.7/site-packages/torch/testing/_deprecated.py", line 88, in assert_allclose
    msg=msg or None,
  File "/envs/py37/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1320, in assert_close
    msg=msg,
  File "/envs/py37/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1080, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 30 / 30 (100.0%)
Greatest absolute difference: 2.11639404296875 at index (0, 0, 1) (up to 1e-05 allowed)
Greatest relative difference: 0.01271602171914995 at index (0, 1, 2) (up to 1e-05 allowed)
```

**Comment by jinlinyi** [comment]
I tested on more environment setups and find the same issue with
```
python 3.8 + pytorch 1.11 + pytorch3d 0.7.2
python 3.8 + pytorch 1.10 + pytorch3d 0.7.2
```
And the following environments do not have this issue
```
python 3.8 + pytorch 1.12 + pytorch3d 0.7.2 
python 3.9 + pytorch 1.13 + pytorch3d 0.7.2
```

**Comment by jonilaserson** [comment]
I'm seeing the same issue on NVIDIA GPU A100
python 3.8.13 + pytorch 1.13.0+ cuda 11.6 + pytorch3d 0.7.2

**Comment by bottler** [comment]
It sounds like this is a (fixed) bug in dependent libraries. I don't think we can help, except to advise using newer versions.
