### ISSUE TITLE
When I from pytorch3d import _C on windows，encoutering the ImportError: DLL load failed while importing _C: 找不到指定的程序。

### ISSUE THREAD

**Issue by DISHENGRZH** [facebookresearch/pytorch3d#1515]
Hellow, when I from pytorch3d import _C on windows, the problems below occoured. I appreciate your reply.

## 🐛 Bugs / Unexpected behaviors
Traceback (most recent call last):
  File "scripts/demo_video.py", line 17, in <module>
    from hybrik.utils.render_pytorch3d import render_mesh
  File "d:\zhenghengrui\hybrik-main\hybrik\utils\render_pytorch3d.py", line 3, in <module>
    import pytorch3d.renderer
  File "D:\_programsLarge\envs\hybrik\lib\site-packages\pytorch3d-0.7.2-py3.8-win-amd64.egg\pytorch3d\renderer\__init__.py", line 7, in <module>
    from .blending import (
  File "D:\_programsLarge\envs\hybrik\lib\site-packages\pytorch3d-0.7.2-py3.8-win-amd64.egg\pytorch3d\renderer\blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: DLL load failed while importing _C: 找不到指定的程序。

my conda list and pip list
# packages in environment at D:\_programsLarge\envs\hybrik:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
blas                      1.0                         mkl    defaults
brotlipy                  0.7.0           py38h294d835_1004    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1           py38hd8c33c5_0    conda-forge
charset-normalizer        3.1.0                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7                    pypi_0    pypi
cryptography              3.4.8            py38hb7941b4_1    conda-forge
cudatoolkit               11.3.1              h280eb24_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    3.0.0b2                  pypi_0    pypi
easydict                  1.10                     pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
flit-core                 3.8.0            py38haa95532_0    defaults
fonttools                 4.39.3                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0    defaults
future                    0.18.3                   pypi_0    pypi
fvcore                    0.1.5.post20210915            py38    https://conda.anaconda.org/fvcore
google-auth               2.17.3                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.54.0                   pypi_0    pypi
hybrik                    0.1.0+556e715             dev_0    <develop>
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.5.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46319    defaults
iopath                    0.1.9                      py38    https://conda.anaconda.org/iopath
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0    defaults
libblas                   3.9.0           1_h8933c1f_netlib    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge
libdeflate                1.17                 h2bbff1b_0    defaults
libffi                    3.4.2                hd77b12b_6    defaults
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
libpng                    1.6.39               h8cc25b3_0    defaults
libtiff                   4.5.0                h8a3f274_0    defaults
libuv                     1.44.2               h2bbff1b_0    defaults
libwebp                   1.2.4                h2bbff1b_0    defaults
libwebp-base              1.2.4                h2bbff1b_1    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mkl                       2023.1.0         h8bd8f75_46356    defaults
msys2-conda-epoch         20160418                      1    conda-forge
ninja                     1.10.2               haa95532_5    defaults
ninja-base                1.10.2               h6d14046_5    defaults
numpy                     1.24.2                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.1.2.30                 pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0    defaults
packaging                 23.1                     pypi_0    pypi
pillow                    6.2.1                    pypi_0    pypi
pip                       23.0.1           py38haa95532_0    defaults
portalocker               1.4.0                      py_0    conda-forge
protobuf                  4.22.3                   pypi_0    pypi
pyasn1                    0.5.0rc2                 pypi_0    pypi
pyasn1-modules            0.3.0rc1                 pypi_0    pypi
pycocotools               2.0.6                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pypiwin32                 223                      pypi_0    pypi
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.8.16               h6244533_3    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.1          py3.8_cuda11.3_cudnn8_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.7.2                    pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                66.0.0           py38haa95532_0    defaults
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.41.2               h2bbff1b_0    defaults
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tb-nightly                2.13.0a20230418          pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0    defaults
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.2.0              pyhd8ed1ab_0    conda-forge
terminaltables            3.1.10                   pypi_0    pypi
tk                        8.6.12               h2bbff1b_0    defaults
torchaudio                0.10.1               py38_cu113    pytorch
torchvision               0.10.1                   pypi_0    pypi
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing_extensions         4.4.0            py38haa95532_0    defaults
urllib3                   1.26.15                  pypi_0    pypi
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py38haa95532_0    defaults
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xz                        5.2.10               h8cc25b3_1    defaults
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0    defaults
zstd                      1.5.5                hd43e919_0    defaults

pip list
Package                 Version            Editable project location
----------------------- ------------------ ---------------------------
absl-py                 1.4.0
brotlipy                0.7.0
cachetools              5.3.0
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      3.1.0
chumpy                  0.70
colorama                0.4.6
contourpy               1.0.7
cryptography            3.4.8
cycler                  0.11.0
Cython                  3.0.0b2
easydict                1.10
ffmpeg-python           0.2.0
flit_core               3.8.0
fonttools               4.39.3
future                  0.18.3
fvcore                  0.1.5.post20210915
google-auth             2.17.3
google-auth-oauthlib    1.0.0
grpcio                  1.54.0
hybrik                  0.1.0+556e715      d:\zhenghengrui\hybrik-main
idna                    3.4
importlib-metadata      6.5.0
importlib-resources     5.12.0
iopath                  0.1.9
joblib                  1.2.0
kiwisolver              1.4.4
Markdown                3.4.3
MarkupSafe              2.1.2
matplotlib              3.7.1
numpy                   1.24.2
oauthlib                3.2.2
opencv-python           4.1.2.30
packaging               23.1
Pillow                  6.2.1
pip                     23.0.1
portalocker             1.4.0
protobuf                4.22.3
pyasn1                  0.5.0rc2
pyasn1-modules          0.3.0rc1
pycocotools             2.0.6
pycparser               2.21
pyOpenSSL               20.0.1
pyparsing               3.0.9
pypiwin32               223
PySocks                 1.7.1
python-dateutil         2.8.2
pytorch3d               0.7.2
pywin32                 306
PyYAML                  3.13
requests                2.28.2
requests-oauthlib       1.3.1
rsa                     4.9
scipy                   1.10.1
setuptools              66.0.0
six                     1.16.0
tabulate                0.9.0
tb-nightly              2.13.0a20230418
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
termcolor               2.2.0
terminaltables          3.1.10
torch                   1.10.1
torchaudio              0.10.1
torchvision             0.11.2
tqdm                    4.65.0
typing_extensions       4.4.0
urllib3                 1.26.15
Werkzeug                2.2.3
wheel                   0.38.4
win-inet-pton           1.1.0
yacs                    0.1.8
zipp                    3.15.0

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

**Comment by DISHENGRZH** [comment]
My torch version is1.10.1 and pytorch3d version is 0.7.2. Their versions are matched.

**Comment by DISHENGRZH** [comment]
I solved it by change the version of pytorch3d.
