### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'is_enabled'

### ISSUE THREAD

**Issue by prokaryote-hgy** [facebookresearch/pytorch3d#1531]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

Hi, I'm installing pytorch3d and I'm struggling with this bug:

```
>>> import pytorch3d
>>> from pytorch3d import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libc10.so: cannot open shared object file: No such file or directory
```

I want to know how to install pytorch3d correctly.

There is some related issues, but none of them slove my problem: #1484, #1152, #1060, #923

## Instructions To Reproduce the Issue:

I install the pytorch3d in a new conda environment. The following commands show all my operations during install pytorch3d:

```
conda create -n pytorch3d python=3.9
conda activate pytorch3d
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
pip install fvcore iopath
pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1110/download.html
```

The following is my conda env list:

```
(pytorch3d) root@8fa738f84d3f:~/hgy/code# conda list
# packages in environment at /root/miniconda3/envs/pytorch3d:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
idna                      3.4                      pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
ncurses                   6.4                  h6a678d5_0    defaults
numpy                     1.24.3                   pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0    defaults
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1           py39h06a4308_0    defaults
portalocker               2.7.0                    pypi_0    pypi
python                    3.9.16               h7a1cb2a_2    defaults
pytorch3d                 0.7.2                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
requests                  2.30.0                   pypi_0    pypi
setuptools                66.0.0           py39h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tabulate                  0.9.0                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
torch                     1.11.0+cu113             pypi_0    pypi
torchaudio                0.11.0+cu113             pypi_0    pypi
torchvision               0.12.0+cu113             pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   2.0.2                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yacs                      0.1.8                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults
```

My GPU environment is: 

```
(pytorch3d) root@8fa738f84d3f:~/hgy/code# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_19:13:29_PDT_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0
```

And I download the CUB library (cub-1.13.1) and set the environment variable: 

```
(pytorch3d) root@8fa738f84d3f:~/hgy/code# $CUB_HOME/
bash: /root/hgy/code/cub-1.13.1/: Is a directory
```

Thanks a lot for helping me!

**Comment by bottler** [comment]
What happens when you run

```
import torch
from pytorch3d.structures import Meshes
```
?

**Comment by prokaryote-hgy** [comment]
Thank you for your reply. I found that when I import pytorch3d after importing torch, there would be not error. Is this normal?

```
(deca-env) root@8fa738f84d3f:~# python
Python 3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytorch3d import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libc10.so: cannot open shared object file: No such file or directory
>>> import torch
>>> from pytorch3d import _C
>>> from pytorch3d.structures import Meshes
```

**Comment by bottler** [comment]
This is normal. Everything looks ok. `_C` is internal to pytorch3d, and is a bit fragile: it can't be imported unless `torch` has already been imported. If you see a public module in pytorch3d which imports `_C` without importing `torch` first then feel free to let us know, that would be a bug.

**Comment by prokaryote-hgy** [comment]
OK, thank you. Now I have no more questions. I will close this issue.
