### ISSUE TITLE
I 've change 0.72&0.62 pytorch3d, but I still have this problem

### ISSUE THREAD

**Issue by wefwwef4** [facebookresearch/pytorch3d#1564]
Traceback (most recent call last):
  File "E:/InterWild-main/demo/demo.py", line 28, in <module>
    from common.utils.vis import save_obj, render_mesh_orthogonal
  File "E:\InterWild-main\common\utils\vis.py", line 18, in <module>
    from pytorch3d.renderer import (
  File "e:\pytorch3d-0.6.2\pytorch3d\renderer\__init__.py", line 7, in <module>
    from .blending import (
  File "e:\pytorch3d-0.6.2\pytorch3d\renderer\blending.py", line 11, in <module>
    from pytorch3d import _C
ImportError: DLL load failed while importing _C: cannot found。

**Comment by wefwwef4** [comment]
(pytorch) E:\InterWild-main>pip list
Package                  Version            Editable project location
------------------------ ------------------ -------------------------
absl-py                  1.4.0
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    23.1.0
backcall                 0.2.0
beautifulsoup4           4.12.2
black                    23.3.0
bleach                   6.0.0
boto3                    1.26.113
botocore                 1.29.113
cachetools               5.3.0
certifi                  2023.5.7
cffi                     1.15.1
charset-normalizer       3.1.0
chumpy                   0.70
click                    8.1.3
cloudpickle              2.2.1
cnn-finetune             0.6.0
colorama                 0.4.6
comm                     0.1.3
contourpy                1.0.7
cycler                   0.11.0
cytoolz                  0.12.0
dask                     2022.7.0
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
executing                1.2.0
fastjsonschema           2.16.3
filelock                 3.12.2
flake8                   6.0.0
flake8-bugbear           23.6.5
flake8-comprehensions    3.12.0
flatbuffers              23.5.26
fonttools                4.39.3
fqdn                     1.5.1
fsspec                   2023.4.0
fvcore                   0.1.5.post20210915
google-auth              2.17.1
google-auth-oauthlib     1.0.0
grpcio                   1.53.0
idna                     3.4
imagecodecs              2021.8.26
imageio                  2.26.0
importlib-metadata       6.1.0
importlib-resources      5.12.0
iopath                   0.1.9
ipykernel                6.22.0
ipython                  8.12.0
ipython-genutils         0.2.0
ipywidgets               8.0.6
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
jmespath                 1.0.1
joblib                   1.2.0
jsonpointer              2.3
jsonschema               4.17.3
jupyter_client           8.2.0
jupyter-console          6.6.3
jupyter_core             5.3.0
jupyter-events           0.6.3
jupyter_server           2.5.0
jupyter_server_terminals 0.4.4
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.7
kiwisolver               1.4.4
kornia                   0.6.12
libcst                   1.0.1
locket                   1.0.0
Markdown                 3.4.3
MarkupSafe               2.1.2
matplotlib               3.7.1
matplotlib-inline        0.1.6
mccabe                   0.7.0
mediapipe                0.10.1
mistune                  2.0.5
mkl-fft                  1.3.6
mkl-random               1.2.2
mkl-service              2.4.0
moreorless               0.4.0
mpmath                   1.3.0
munch                    2.5.0
mypy-extensions          1.0.0
nbclassic                0.5.5
nbclient                 0.7.3
nbconvert                7.3.1
nbformat                 5.8.0
nest-asyncio             1.5.6
networkx                 2.8.4
notebook                 6.5.4
notebook_shim            0.2.2
numpy                    1.24.2
oauthlib                 3.2.2
opencv-contrib-python    4.7.0.72
opencv-python            4.7.0.72
packaging                23.1
pandas                   2.0.0
pandocfilters            1.5.0
parso                    0.8.3
partd                    1.2.0
pathspec                 0.11.1
pickleshare              0.7.5
Pillow                   9.4.0
pip                      23.0.1
pkgutil_resolve_name     1.3.10
platformdirs             3.2.0
plotly                   5.14.1
plyfile                  0.7.2
portalocker              1.4.0
pretrainedmodels         0.7.4
progress                 1.5
prometheus-client        0.16.0
prompt-toolkit           3.0.38
protobuf                 3.20.3
psutil                   5.9.4
pure-eval                0.2.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycodestyle              2.10.0
pycparser                2.21
pyflakes                 3.0.1
Pygments                 2.15.0
pynput                   1.7.6
pyparsing                3.0.9
pyperclip                1.8.1
pypiwin32                223
pyrsistent               0.19.3
python-dateutil          2.8.2
python-json-logger       2.0.7
pytorch3d                0.6.2              e:\pytorch3d-0.6.2
pytz                     2023.3
PyWavelets               1.4.1
pywin32                  306
pywinpty                 2.0.10
PyYAML                   6.0
pyzmq                    25.0.2
qtconsole                5.4.2
QtPy                     2.3.1
regex                    2023.3.23
requests                 2.28.2
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rsa                      4.9
s3transfer               0.6.0
scikit-image             0.19.3
scikit-learn             1.2.2
scipy                    1.10.1
Send2Trash               1.8.0
setuptools               66.0.0
sip                      4.19.13
six                      1.16.0
smplx                    0.1.28
sniffio                  1.3.0
sounddevice              0.4.6
soupsieve                2.4.1
stack-data               0.6.2
stdlibs                  2022.10.9
sympy                    1.12
tabulate                 0.9.0
tenacity                 8.2.2
tensorboard              2.12.1
tensorboard-data-server  0.7.0
tensorboard-plugin-wit   1.8.1
tensorboardX             2.2
termcolor                2.3.0
terminado                0.17.1
threadpoolctl            3.1.0
tifffile                 2021.7.2
tinycss2                 1.2.1
toml                     0.10.2
tomli                    2.0.1
toolz                    0.12.0
torch                    1.9.0+cu111
torchaudio               0.9.0
torchgeometry            0.1.2
torchsummary             1.5.1
torchvision              0.10.0+cu111
tornado                  6.2
tqdm                     4.65.0
trailrunner              1.4.0
traitlets                5.9.0
typing_extensions        4.5.0
typing-inspect           0.9.0
tzdata                   2023.3
uri-template             1.2.0
urllib3                  1.26.15
usort                    1.0.7
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.5.1
Werkzeug                 2.2.3
wheel                    0.38.4
widgetsnbextension       4.0.7
wincertstore             0.2
wxPython                 4.2.1
yacs                     0.1.8
zipp                     3.15.0

**Comment by bottler** [comment]
This comes from a build of pytorch3d which is not built properly, or built with a different pytorch version than the one you have. How exactly did you install pytorch3d?
