### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by IAM-P-LP** [facebookresearch/pytorch3d#1683]
I was trying to load a .obj file using load_obj() function of pytorch3d.I am getting the below error.Can you please advice on how to solve this?

Traceback (most recent call last):
  File "/home/synthetic_data_generator/main.py", line 119, in <module>
    main()
  File "/home/synthetic_data_generator/main.py", line 115, in main
    dataset.get_images()
  File "/home/synthetic_data_generator/main.py", line 40, in get_images
    image = self.renger_obj.get_image(elev_angle, azim_angle)
  File "/home/synthetic_data_generator/render.py", line 218, in get_image
    mesh = self.get_mesh()
  File "/home/synthetic_data_generator/render.py", line 133, in get_mesh
    verts, faces, aux = load_obj(
  File "/home/miniconda3/envs/poseapp/lib/python3.9/site-packages/pytorch3d/io/obj_io.py", line 224, in load_obj
    return _load_obj(
  File "/home/miniconda3/envs/poseapp/lib/python3.9/site-packages/pytorch3d/io/obj_io.py", line 650, in _load_obj
    face_material_names = np.array(material_names)[idx]  # (F,)
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by bottler** [comment]
Could it be that our function `load_obj` is being called with `create_texture_atlas=True` on an obj file with no texture data? What do you get if you call it with `create_texture_atlas=False` on the same file? 

Do you need texture data out of this file? And do you know if there is texture data in the file? Feel free to share the data.

**Comment by IAM-P-LP** [comment]
Hi,
when I use create_texture_atlas=False, it throws this error
 File "/home/miniconda3/envs/poseapp/lib/python3.9/site-packages/pytorch3d/renderer/mesh/textures.py", line 379, in __init__
    raise ValueError(msg)
ValueError: Expected atlas to be a list of tensors of shape (F, R, R, C) with the same value of R. 
I have attached the files.Please feel free to go through.
https://drive.google.com/drive/folders/1y_12gEvObi2riuaDgE0i2nh3hHkX3Tus?usp=sharing

**Comment by bottler** [comment]
I missed this. I think you can follow the logic in the code for what happens when usemtl is not specified. I think it should be easy to modify the data to make this work.
