### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Dumeowmeow** [facebookresearch/pytorch3d#1861]
When I try to use pytorch3d in a project, It gives the following error:
Warning:
Unable to load the following plugins:

    libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.
Cannot load library /home/zl/anaconda3/envs/unique3d/lib/python3.11/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)

Traceback (most recent call last):
File "/home/zl/anaconda3/envs/unique3d/lib/python3.11/runpy.py", line 198, in _run_module_as_main
return _run_code(code, main_globals, None,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zl/anaconda3/envs/unique3d/lib/python3.11/runpy.py", line 88, in _run_code
exec(code, run_globals)
File "/home/zl/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/main.py", line 39, in
cli.main()
File "/home/zl/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
run()
File "/home/zl/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
runpy.run_path(target, run_name="main")
File "/home/zl/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
return _run_module_code(code, init_globals, run_name,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/zl/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "/home/zl/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
exec(code, run_globals)
File "/home/zl/yyc_workspace/dff_workspace/Unique3D/app/gradio_local.py", line 20, in
from app.gradio_3dgen import create_ui as create_3d_ui
File "/home/zl/yyc_workspace/dff_workspace/Unique3D/app/gradio_3dgen.py", line 6, in
from app.custom_models.mvimg_prediction import run_mvprediction
File "/home/zl/yyc_workspace/dff_workspace/Unique3D/app/custom_models/mvimg_prediction.py", line 10, in
from scripts.utils import session, simple_preprocess
File "/home/zl/yyc_workspace/dff_workspace/Unique3D/scripts/utils.py", line 7, in
from pytorch3d.renderer import TexturesVertex
File "/home/zl/anaconda3/envs/unique3d/lib/python3.11/site-packages/pytorch3d/renderer/init.py", line 9, in
from .blending import (
File "/home/zl/anaconda3/envs/unique3d/lib/python3.11/site-packages/pytorch3d/renderer/blending.py", line 12, in
from pytorch3d import _C
ImportError: /home/zl/anaconda3/envs/unique3d/lib/python3.11/site-packages/pytorch3d/_C.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

my environment is as follows:
Package Version

accelerate 0.34.0
addict 2.4.0
aiofiles 23.2.1
aiohappyeyeballs 2.4.0
aiohttp 3.10.5
aiosignal 1.3.1
annotated-types 0.7.0
antlr4-python3-runtime 4.9.3
anyio 4.4.0
attrs 24.2.0
certifi 2024.8.30
charset-normalizer 3.3.2
click 8.1.7
coloredlogs 15.0.1
contourpy 1.3.0
cycler 0.12.1
dataclasses-json 0.6.7
datasets 2.21.0
Deprecated 1.2.14
diffusers 0.27.2
dill 0.3.8
docker-pycreds 0.4.0
fastapi 0.112.2
ffmpy 0.4.0
filelock 3.15.4
fire 0.6.0
flatbuffers 24.3.25
fonttools 4.53.1
frozenlist 1.4.1
fsspec 2024.6.1
fvcore 0.1.5.post20221221
gitdb 4.0.11
GitPython 3.1.43
gradio 4.42.0
gradio_client 1.3.0
h11 0.14.0
hf_transfer 0.1.8
httpcore 1.0.5
httpx 0.27.2
huggingface-hub 0.24.6
humanfriendly 10.0
idna 3.8
imageio 2.35.1
importlib_metadata 8.4.0
importlib_resources 6.4.4
iopath 0.1.10
jaxtyping 0.2.34
Jinja2 3.1.3
jsonschema 4.23.0
jsonschema-specifications 2023.12.1
kiwisolver 1.4.5
lazy_loader 0.4
llvmlite 0.43.0
markdown-it-py 3.0.0
MarkupSafe 2.1.5
marshmallow 3.22.0
matplotlib 3.9.2
mdurl 0.1.2
mmcv-full 1.7.2
mpmath 1.3.0
multidict 6.0.5
multiprocess 0.70.16
mypy-extensions 1.0.0
networkx 3.2.1
ninja 1.11.1.1
numba 0.60.0
numpy 2.0.2
nvdiffrast 0.3.1
nvidia-cublas-cu12 12.1.3.1
nvidia-cuda-cupti-cu12 12.1.105
nvidia-cuda-nvrtc-cu12 12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12 8.9.2.26
nvidia-cufft-cu12 11.0.2.54
nvidia-curand-cu12 10.3.2.106
nvidia-cusolver-cu12 11.4.5.107
nvidia-cusparse-cu12 12.1.0.106
nvidia-nccl-cu12 2.20.5
nvidia-nvjitlink-cu12 12.6.68
nvidia-nvtx-cu12 12.1.105
omegaconf 2.3.0
onnxruntime 1.19.0
onnxruntime-gpu 1.19.0
opencv-python 4.10.0.84
opencv-python-headless 4.10.0.84
orjson 3.10.7
ort-nightly-gpu 1.15.0.dev20230502003
packaging 24.1
pandas 2.2.2
peft 0.12.0
pillow 10.4.0
pip 24.2
platformdirs 4.2.2
pooch 1.8.2
portalocker 2.10.1
protobuf 5.28.0
psutil 6.0.0
pyarrow 17.0.0
pydantic 2.8.2
pydantic_core 2.20.1
pydub 0.25.1
pygltflib 1.16.2
Pygments 2.18.0
PyMatting 1.1.12
pymeshlab 2023.12
pyparsing 3.1.4
python-dateutil 2.9.0.post0
python-multipart 0.0.9
pytorch3d 0.7.7
pytz 2024.1
PyYAML 6.0.2
referencing 0.35.1
regex 2024.7.24
rembg 2.0.59
requests 2.32.3
rich 13.8.0
rpds-py 0.20.0
ruff 0.6.3
safetensors 0.4.4
scikit-image 0.24.0
scipy 1.14.1
semantic-version 2.10.0
sentry-sdk 2.13.0
setproctitle 1.3.3
setuptools 72.1.0
shellingham 1.5.4
six 1.16.0
smmap 5.0.1
sniffio 1.3.1
starlette 0.38.4
sympy 1.12
tabulate 0.9.0
termcolor 2.4.0
tifffile 2024.8.30
tokenizers 0.19.1
tomli 2.0.1
tomlkit 0.12.0
torch 2.3.1
torch_scatter 2.1.2
torchaudio 2.3.1+cu121
torchvision 0.18.1+cu121
tqdm 4.66.5
transformers 4.44.2
trimesh 4.4.8
triton 2.3.1
typeguard 2.13.3
typer 0.12.5
typing_extensions 4.12.2
typing-inspect 0.9.0
tzdata 2024.1
urllib3 2.2.2
uvicorn 0.30.6
wandb 0.17.8
websockets 12.0
wheel 0.43.0
wrapt 1.16.0
xformers 0.0.27
xxhash 3.5.0
yacs 0.1.8
yapf 0.40.2
yarl 1.9.7
zipp 3.20.1

How to fix it?

**Comment by bottler** [comment]
This might be a difference between the PyTorch version used to build PyTorch3D and the one present at runtime. it could be quite subtle difference. If you are building PyTorch3D from source, please make sure to do it in the very same environment where you are running it. 

This might be a debug environment where everything needs to be built from source and maybe something has gone wrong there.
