### ISSUE TITLE
Windows Install wrong.

### ISSUE THREAD

**Issue by LiYan-pro** [facebookresearch/pytorch3d#1917]
## 🐛 Bugs / Unexpected behaviors
I installed pytorch3d on Windows with conda enviroment.
But when I use `python3 -m unittest discover -v -s tests -t .` for test ,I meet this error:

```
test_get_item (tests.test_volumes.TestVolumes) ... ok
test_locator_init (tests.test_volumes.TestVolumes) ... ok
test_to (tests.test_volumes.TestVolumes)
Test the moving of the volumes from/to gpu and cpu ... D:\code\other\pytorch3d\tests\common_testing.py:85: UserWarning:

TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()

ok

======================================================================
ERROR: test_no_import_cycles (tests.implicitron.test_build.TestBuild) (name='pytorch3d.common\\compat')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\other\pytorch3d\tests\implicitron\test_build.py", line 51, in test_no_import_cycles
    importlib.import_module(module)
  File "E:\miniconda\envs\foundationpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytorch3d.common\\compat'

======================================================================
ERROR: test_no_import_cycles (tests.implicitron.test_build.TestBuild) (name='pytorch3d.common\\datatypes')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\other\pytorch3d\tests\implicitron\test_build.py", line 51, in test_no_import_cycles
    importlib.import_module(module)
  File "E:\miniconda\envs\foundationpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytorch3d.common\\datatypes'

======================================================================
ERROR: test_no_import_cycles (tests.implicitron.test_build.TestBuild) (name='pytorch3d.common\\linear_with_repeat')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\other\pytorch3d\tests\implicitron\test_build.py", line 51, in test_no_import_cycles
    importlib.import_module(module)
  File "E:\miniconda\envs\foundationpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytorch3d.common\\linear_with_repeat'

======================================================================
ERROR: test_no_import_cycles (tests.implicitron.test_build.TestBuild) (name='pytorch3d.common\\workaround\\symeig3x3')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\other\pytorch3d\tests\implicitron\test_build.py", line 51, in test_no_import_cycles
    importlib.import_module(module)
  File "E:\miniconda\envs\foundationpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytorch3d.common\\workaround\\symeig3x3'

======================================================================
ERROR: test_no_import_cycles (tests.implicitron.test_build.TestBuild) (name='pytorch3d.common\\workaround\\utils')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\other\pytorch3d\tests\implicitron\test_build.py", line 51, in test_no_import_cycles
    importlib.import_module(module)
  File "E:\miniconda\envs\foundationpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytorch3d.common\\workaround\\utils'

...

```

### Base Environment:
- Windows 11
- Visual Studio 2019 Developer Command Prompt v16.11.32
- Cuda compilation tools, release 11.8, V11.8.89
- gcc 13.1.0
- conda 23.11.0
- pip 24.3.1
- Python 3.9.20
- torch 2.0.0+cu118
- torchvision 0.15.1+cu118
- cub-2.0.0
- pinocchio 3.3.0

### Installtion Proccess:
```
cd pytorch3d-0.7.7
pip install -e .
```

### Full Conda Environment
```
#
# Name                    Version                   Build  Channel
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.11.7                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albucore                  0.0.20                   pypi_0    pypi
albumentations            1.4.2                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.6.2.post1              pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0
arrow                     1.3.0                    pypi_0    pypi
assimp                    5.4.3                hf1e84b2_0    conda-forge
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4            py39haa95532_0
async-timeout             5.0.1                    pypi_0    pypi
attrs                     24.2.0           py39haa95532_0
babel                     2.16.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.12.3           py39haa95532_0
black                     24.10.0                  pypi_0    pypi
bleach                    6.2.0            py39haa95532_0
blinker                   1.9.0                    pypi_0    pypi
blurhash                  1.1.4                    pypi_0    pypi
bokeh                     3.4.0                    pypi_0    pypi
boost                     0.1                      pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
brotli                    1.1.0                    pypi_0    pypi
brotli-python             1.0.9            py39hd77b12b_8
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.9.24            haa95532_0
casadi                    3.6.7            py39h9d1c3e3_0    conda-forge
certifi                   2024.8.30        py39haa95532_0
cffi                      1.17.1           py39h827c3e9_0
charset-normalizer        3.4.0                    pypi_0    pypi
cli11                     2.4.2                he0c23c2_0    conda-forge
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
console_bridge            1.0.2                h5362a0b_1    conda-forge
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dash                      2.18.2                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
debugpy                   1.8.9                    pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
dlfcn-win32               1.4.1                h63175ca_0    conda-forge
docker-pycreds            0.4.0                    pypi_0    pypi
eigen                     3.4.0                h91493d7_0    conda-forge
eigenpy                   3.10.1          np20py39h9d35a09_0    conda-forge
einops                    0.7.0                    pypi_0    pypi
et-xmlfile                2.0.0                    pypi_0    pypi
eval-type-backport        0.2.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
flake8                    7.1.1                    pypi_0    pypi
flake8-bugbear            24.10.31                 pypi_0    pypi
flake8-comprehensions     3.16.0                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.55.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               hdaf720e_2    conda-forge
freetype-py               2.5.1                    pypi_0    pypi
frozenlist                1.5.0                    pypi_0    pypi
fsspec                    2024.10.0                pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
fvcore                    0.1.5.post20221221    pyhd8ed1ab_0    conda-forge
g4f                       0.2.7.1                  pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
glib                      2.82.2               h7025463_0    conda-forge
glib-tools                2.82.2               h4394cf3_0    conda-forge
gputil                    1.4.0                    pypi_0    pypi
greenlet                  3.1.1                    pypi_0    pypi
gst-plugins-base          1.24.7               hb0a98b8_0    conda-forge
gstreamer                 1.24.7               h5006eae_0    conda-forge
h11                       0.14.0           py39haa95532_0
h5py                      3.10.0                   pypi_0    pypi
hpp-fcl                   2.4.5            py39hd30bc07_8    conda-forge
httpcore                  1.0.7                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.26.2                   pypi_0    pypi
icu                       75.1                 he0c23c2_0    conda-forge
idna                      3.10                     pypi_0    pypi
imageio                   2.34.0                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        8.5.0            py39haa95532_0
importlib-resources       6.4.5                    pypi_0    pypi
importlib_metadata        8.5.0                hd3eb1b0_0
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
iopath                    0.1.10                   pypi_0    pypi
ipopt                     3.14.16             hfa42872_10    conda-forge
ipykernel                 6.29.5           py39haa95532_0
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.2            py39haa95532_0
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.2                   pypi_0    pypi
jinja2                    3.1.4            py39haa95532_1
joblib                    1.3.2                    pypi_0    pypi
json5                     0.9.28                   pypi_0    pypi
jsonpatch                 1.33                     pypi_0    pypi
jsonpointer               3.0.0                    pypi_0    pypi
jsonschema                4.23.0           py39haa95532_0
jsonschema-specifications 2024.10.1                pypi_0    pypi
jupyter                   1.0.0            py39haa95532_9
jupyter-client            8.6.3                    pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.14.2                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyter_client            8.6.0            py39haa95532_0
jupyter_console           6.6.3            py39haa95532_0
jupyter_core              5.7.2            py39haa95532_0
jupyter_events            0.10.0           py39haa95532_0
jupyter_server            2.14.1           py39haa95532_0
jupyter_server_terminals  0.4.4            py39haa95532_1
jupyterlab                4.1.5                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.27.3           py39haa95532_0
jupyterlab_widgets        3.0.10           py39haa95532_0
kiwisolver                1.4.7                    pypi_0    pypi
kornia                    0.7.2                    pypi_0    pypi
kornia-rs                 0.1.7                    pypi_0    pypi
krb5                      1.21.3               hdf4eb48_0    conda-forge
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              25_win64_mkl    conda-forge
libboost                  1.86.0               h444863b_2    conda-forge
libboost-devel            1.86.0               h91493d7_2    conda-forge
libboost-headers          1.86.0               h57928b3_2    conda-forge
libboost-python           1.86.0           py39h8f1c5a3_2    conda-forge
libboost-python-devel     1.86.0           py39hcb5f9c0_2    conda-forge
libcblas                  3.9.0              25_win64_mkl    conda-forge
libclang13                19.1.4          default_ha5278ca_0    conda-forge
libcst                    1.5.1                    pypi_0    pypi
libdeflate                1.22                 h2466b09_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libglib                   2.82.2               h7025463_0    conda-forge
libgz-cmake3              3.5.3                he0c23c2_0    conda-forge
libgz-math7               7.5.1                he0c23c2_2    conda-forge
libgz-tools2              2.0.1                h9fbcf1e_0    conda-forge
libgz-utils2              2.2.0                he0c23c2_0    conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_3    conda-forge
libintl-devel             0.22.5               h5728263_3    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              25_win64_mkl    conda-forge
libogg                    1.3.5                h2bbff1b_1
libosqp                   0.6.3                he0c23c2_1    conda-forge
libpng                    1.6.44               h3ca93ac_0    conda-forge
libqdldl                  0.1.7                h63175ca_0    conda-forge
libsdformat14             14.5.0               hf143461_0    conda-forge
libsodium                 1.0.18               h62dcd97_0
libsqlite                 3.47.0               h2466b09_1    conda-forge
libtiff                   4.7.0                hfc51747_1    conda-forge
libvorbis                 1.3.7                he774522_0
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 h013a479_1    conda-forge
libxml2                   2.13.5               h442d1da_0    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
llvmlite                  0.42.0                   pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                3.0.2                    pypi_0    pypi
mastodon-py               1.8.1                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
meshcat                   0.3.2                    pypi_0    pypi
meson                     1.6.0                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mkl                       2024.2.2            h66d3029_14    conda-forge
moreorless                0.4.0                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.1.0                    pypi_0    pypi
mumps-seq                 5.7.3                h7c2359a_5    conda-forge
mypy-extensions           1.0.0                    pypi_0    pypi
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.4           py39haa95532_0
nbformat                  5.10.4           py39haa95532_0
nest-asyncio              1.6.0            py39haa95532_0
networkx                  3.2.1                    pypi_0    pypi
ninja                     1.11.1.2                 pypi_0    pypi
nodejs                    0.1.1                    pypi_0    pypi
notebook                  7.2.2            py39haa95532_1
notebook-shim             0.2.4                    pypi_0    pypi
numba                     0.59.1                   pypi_0    pypi
numpy                     1.26.4           py39hddb5d58_0    conda-forge
nvdiffrast                0.3.3                    pypi_0    pypi
objaverse                 0.1.7                    pypi_0    pypi
octomap                   1.10.0               hc790b64_0    conda-forge
omegaconf                 2.3.0                    pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-contrib-python     4.9.0.80                 pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.4.0                h2466b09_0    conda-forge
optional-django           0.1.0                    pypi_0    pypi
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.2                     pypi_0    pypi
panda3d                   1.10.14                  pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pcre2                     10.44                h3d7b363_2    conda-forge
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.1.0                    pypi_0    pypi
pinocchio                 3.3.0            py39hf390009_1    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
platformdirs              4.3.6                    pypi_0    pypi
plotly                    5.20.0                   pypi_0    pypi
ply                       3.11             py39haa95532_0
portalocker               3.0.0            py39hcbf5309_0    conda-forge
prometheus_client         0.21.0           py39haa95532_0
prompt-toolkit            3.0.48                   pypi_0    pypi
prompt_toolkit            3.0.43               hd3eb1b0_0
propcache                 0.2.0                    pypi_0    pypi
protobuf                  4.25.5                   pypi_0    pypi
proxsuite                 0.6.7            py39h2b77a98_1    conda-forge
psutil                    6.1.0                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                h2466b09_4    conda-forge
pure-eval                 0.2.3                    pypi_0    pypi
pure_eval                 0.2.2              pyhd3eb1b0_0
py-cpuinfo                9.0.0                    pypi_0    pypi
py-spy                    0.3.14                   pypi_0    pypi
pyarrow                   18.0.0                   pypi_0    pypi
pybind11                  2.12.0                   pypi_0    pypi
pybullet                  3.2.6                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycodestyle               2.12.1                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.21.0                   pypi_0    pypi
pydantic                  2.10.1                   pypi_0    pypi
pydantic-core             2.27.1                   pypi_0    pypi
pyflakes                  3.2.0                    pypi_0    pypi
pyglet                    1.5.28                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyngrok                   7.2.1                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyopengl-accelerate       3.1.7                    pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pypng                     0.20220715.0             pypi_0    pypi
pyqt                      5.15.10          py39hd77b12b_0
pyqt5-sip                 12.13.0          py39h2bbff1b_0
pyrender                  0.1.45                   pypi_0    pypi
pysdf                     0.1.9                    pypi_0    pypi
pysocks                   1.7.1            py39haa95532_0
python                    3.9.20          hfaddaf0_1_cpython    conda-forge
python-dateutil           2.9.0post0       py39haa95532_2
python-fastjsonschema     2.20.0           py39haa95532_0
python-json-logger        2.0.7            py39haa95532_0
python-magic-bin          0.4.14                   pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch3d                 0.7.7                     dev_0    <develop>
pytz                      2024.2                   pypi_0    pypi
pywin32                   308                      pypi_0    pypi
pywinpty                  2.0.14                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     26.2.0                   pypi_0    pypi
qhull                     2020.2               hc790b64_5    conda-forge
qt-main                   5.15.15              h264fbc2_0    conda-forge
qtconsole                 5.6.0            py39haa95532_0
qtpy                      2.4.1            py39haa95532_0
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3           py39haa95532_1
retrying                  1.3.4                    pypi_0    pypi
rfc3339-validator         0.1.4            py39haa95532_0
rfc3986-validator         0.1.1            py39haa95532_0
roma                      1.4.4                    pypi_0    pypi
rpds-py                   0.21.0                   pypi_0    pypi
rtree                     1.2.0                    pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.12                   pypi_0    pypi
ruby                      3.3.6                h79e22a9_0    conda-forge
safetensors               0.4.5                    pypi_0    pypi
scikit-image              0.22.0                   pypi_0    pypi
scikit-learn              1.4.1.post1              pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
sentry-sdk                2.19.0                   pypi_0    pypi
setproctitle              1.3.4                    pypi_0    pypi
setuptools                75.6.0                   pypi_0    pypi
shapely                   2.0.6                    pypi_0    pypi
simde                     0.8.2                hc790b64_0    conda-forge
simplejson                3.19.2                   pypi_0    pypi
simsimd                   6.1.1                    pypi_0    pypi
sip                       6.7.12           py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sqlalchemy                2.0.36                   pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
stack-data                0.6.3                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0
stdlibs                   2024.10.25               pypi_0    pypi
stringzilla               3.10.10                  pypi_0    pypi
sympy                     1.13.3                   pypi_0    pypi
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.13.0            hc790b64_0    conda-forge
tenacity                  9.0.0                    pypi_0    pypi
termcolor                 2.5.0              pyhd8ed1ab_0    conda-forge
terminado                 0.18.1                   pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
timm                      0.9.16                   pypi_0    pypi
tinycss2                  1.4.0                    pypi_0    pypi
tinyxml2                  10.0.0               h63175ca_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.1.0                    pypi_0    pypi
torch                     2.0.0+cu118              pypi_0    pypi
torchaudio                2.0.1+cu118              pypi_0    pypi
torchnet                  0.0.4                    pypi_0    pypi
torchvision               0.15.1+cu118             pypi_0    pypi
tornado                   6.4.2                    pypi_0    pypi
tqdm                      4.67.1             pyhd8ed1ab_0    conda-forge
trailrunner               1.4.0                    pypi_0    pypi
traitlets                 5.14.3           py39haa95532_0
transformations           2024.6.1                 pypi_0    pypi
trimesh                   4.2.2                    pypi_0    pypi
types-python-dateutil     2.9.0.20241003           pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing_extensions         4.11.0           py39haa95532_0
tzdata                    2024.2                   pypi_0    pypi
u-msgpack-python          2.8.0                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
ultralytics               8.0.120                  pypi_0    pypi
ultralytics-thop          2.0.12                   pypi_0    pypi
urdfdom                   4.0.1                h3a023e0_0    conda-forge
urdfdom_headers           1.1.2                hc790b64_0    conda-forge
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.2.3            py39haa95532_0
usort                     1.0.8.post1              pypi_0    pypi
vc                        14.40                h2eaa2aa_1
vc14_runtime              14.42.34433         he29a5d6_23    conda-forge
videoio                   0.2.8                    pypi_0    pypi
visdom                    0.2.4                    pypi_0    pypi
vs2015_runtime            14.42.34433         hdffcdeb_23    conda-forge
wandb                     0.16.5                   pypi_0    pypi
warp-lang                 1.0.2                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 24.11.1                  pypi_0    pypi
webdataset                0.2.86                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0            py39haa95532_0
werkzeug                  3.0.6                    pypi_0    pypi
wheel                     0.45.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.13                   pypi_0    pypi
win32-setctime            1.1.0                    pypi_0    pypi
win_inet_pton             1.1.0            py39haa95532_0
winpty                    0.4.3                         4
xatlas                    0.0.9                    pypi_0    pypi
xlsxwriter                3.2.0                    pypi_0    pypi
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xyzservices               2024.9.0                 pypi_0    pypi
xz                        5.2.6                h8d14728_0    conda-forge
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yarl                      1.18.0                   pypi_0    pypi
zeromq                    4.3.5                hd77b12b_0
zipp                      3.21.0           py39haa95532_0
zlib                      1.3.1                h2466b09_2    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge

```

**Comment by bottler** [comment]
Not all the tests are currently passing, even on a perfect install. I suspect your install is fine.

- A small number, less than 6, are known to be numerically unstable.
- The test_no_import_cycles cases don't pass and this is known to be a test problem not a library problem. A partial cause is a change in torchvision a while back which I do not understand. In your case, you are observing that they have a more fundamental problem on windows: in [this line](https://github.com/facebookresearch/pytorch3d/blob/main/tests/test_build.py#L99) and [this line](https://github.com/facebookresearch/pytorch3d/blob/main/tests/implicitron/test_build.py#L48) the `"/"` should be replaced by `os.sep`. If these failures are a problem for you, feel free to send a PR for that change, or to send a PR commenting out both of those test_build functions. I don't think fixing the separator will actually fully fix the test.
