### ISSUE TITLE
ERROR: Failed building wheel for pytorch3d

### ISSUE THREAD

**Issue by pp350565935** [facebookresearch/pytorch3d#1920]
## 🐛 Bugs / Unexpected behaviors

ERROR: Failed building wheel for pytorch3d

## Instructions To Reproduce the Issue:

Hi, I'm encountering issues while trying to install pytorch3d on Ubuntu.

I've seen other people have had similar issues and have followed several recommended solutions, but the problem persists. Can you please point out if I'm missing something or which specific step I should be paying attention to?

Thank you for your help!

I used pip install git+https://github.com/facebookresearch/pytorch3d.git@v0.6.2 to install pytorch3d.

Here are my errors, I deleted some of the duplicates
File "/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/setuptools/_distu

----------------------------------------------------------------------------------------------------------------------------
(SPARK) root@DESKTOP-SP:~# pip install git+https://github.com/facebookresearch/pytorch3d.git@v0.6.2
Collecting git+https://github.com/facebookresearch/pytorch3d.git@v0.6.2
  Cloning https://github.com/facebookresearch/pytorch3d.git (to revision v0.6.2) to /tmp/pip-req-build-d6qs4fxc
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/pytorch3d.git /tmp/pip-req-build-d6qs4fxc
  Running command git checkout -q 2bd65027ca5c3b87b77d4f05b8eacae58d8d106f
  Resolved https://github.com/facebookresearch/pytorch3d.git to commit 2bd65027ca5c3b87b77d4f05b8eacae58d8d106f
  Preparing metadata (setup.py) ... done
Collecting fvcore (from pytorch3d==0.6.2)
  Using cached fvcore-0.1.5.post20221221-py3-none-any.whl
Requirement already satisfied: iopath in /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages (from pytorch3d==0.6.2) (0.1.9)
Requirement already satisfied: numpy in /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages (from fvcore->pytorch3d==0.6.2) (1.24.4)
Collecting yacs>=0.1.6 (from fvcore->pytorch3d==0.6.2)
  Using cached yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)
Requirement already satisfied: pyyaml>=5.1 in /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages (from fvcore->pytorch3d==0.6.2) (6.0.2)
Requirement already satisfied: tqdm in /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages (from fvcore->pytorch3d==0.6.2) (4.66.5)
Collecting termcolor>=1.1 (from fvcore->pytorch3d==0.6.2)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: Pillow in /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages (from fvcore->pytorch3d==0.6.2) (11.0.0)
Collecting tabulate (from fvcore->pytorch3d==0.6.2)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: portalocker in /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages (from iopath->pytorch3d==0.6.2) (2.3.0)
Using cached termcolor-2.5.0-py3-none-any.whl (7.8 kB)
Using cached yacs-0.1.8-py3-none-any.whl (14 kB)
Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Building wheels for collected packages: pytorch3d
  Building wheel for pytorch3d (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [337 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-39/pytorch3d
      copying pytorch3d/__init__.py -> build/lib.linux-x86_64-cpython-39/pytorch3d
      creating build/lib.linux-x86_64-cpython-39/projects
      copying projects/__init__.py -> build/lib.linux-x86_64-cpython-39/projects
      creating build/lib.linux-x86_64-cpython-39/pytorch3d/vis
      copying pytorch3d/vis/plotly_vis.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/vis
      copying pytorch3d/vis/texture_vis.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/vis
      copying pytorch3d/vis/__init__.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/vis
      creating build/lib.linux-x86_64-cpython-39/pytorch3d/transforms
      copying pytorch3d/transforms/se3.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/transforms
      copying pytorch3d/transforms/math.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/transforms
      copying pytorch3d/transforms/transform3d.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/transforms
      copying pytorch3d/transforms/so3.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/transforms
      copying pytorch3d/transforms/rotation_conversions.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/transforms
      copying pytorch3d/transforms/__init__.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/transforms
      creating build/lib.linux-x86_64-cpython-39/pytorch3d/loss
      copying pytorch3d/loss/point_mesh_distance.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/loss
      copying pytorch3d/loss/chamfer.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/loss
      copying pytorch3d/loss/mesh_edge_loss.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/loss
      copying pytorch3d/loss/mesh_normal_consistency.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/loss
      copying pytorch3d/loss/mesh_laplacian_smoothing.py -> build/lib.linux-x86_64-cpython-39/pytorch3d/loss
      ........
          running build_ext
           creating /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/rasterize_meshes
      creating /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/rasterize_points
      creating /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/sample_farthest_points
      creating /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/sample_pdf
      Emitting ninja build file /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/65] /mnt/h/Anaconda/envs/SPARK/bin/nvcc  -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum.cu -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum.o
      /mnt/h/Anaconda/envs/SPARK/bin/nvcc  -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum.cu -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      In file included from /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum.cu:11:
      /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
       #include <cusolverDn.h>
                ^~~~~~~~~~~~~~
      compilation terminated.
      [2/65] /mnt/h/Anaconda/envs/SPARK/bin/nvcc  -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/alpha_composite.cu -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/alpha_composite.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/alpha_composite.o
  
      In file included from /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/alpha_composite.cu:11:
      /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
       #include <cusolverDn.h>
                ^~~~~~~~~~~~~~
      compilation terminated.
      [3/65] /mnt/h/Anaconda/envs/SPARK/bin/nvcc  -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/blending/sigmoid_alpha_blend.cu -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/blending/sigmoid_alpha_blend.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/blending/sigmoid_alpha_blend.o

      In file included from /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/blending/sigmoid_alpha_blend.cu:10:
      /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
       #include <cusolverDn.h>
                ^~~~~~~~~~~~~~
      compilation terminated.

      FAILED: /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/ball_query/ball_query.o
       In file included from /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/ball_query/ball_query.cu:10:
      /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
       #include <cusolverDn.h>
                ^~~~~~~~~~~~~~
      compilation terminated.
     
      FAILED: /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/weighted_sum.o

      In file included from /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/weighted_sum.cu:11:
      /mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
       #include <cusolverDn.h>
                ^~~~~~~~~~~~~~
      compilation terminated.
      [6/65] c++ -MMD -MF /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/blending/sigmoid_alpha_blend_cpu.o.d -pthread -B /mnt/h/Anaconda/envs/SPARK/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/blending/sigmoid_alpha_blend_cpu.cpp -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/blending/sigmoid_alpha_blend_cpu.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      [7/65] c++ -MMD -MF /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/ball_query/ball_query_cpu.o.d -pthread -B /mnt/h/Anaconda/envs/SPARK/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/ball_query/ball_query_cpu.cpp -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/ball_query/ball_query_cpu.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      [8/65] c++ -MMD -MF /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum_cpu.o.d -pthread -B /mnt/h/Anaconda/envs/SPARK/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum_cpu.cpp -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/norm_weighted_sum_cpu.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      [9/65] c++ -MMD -MF /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/weighted_sum_cpu.o.d -pthread -B /mnt/h/Anaconda/envs/SPARK/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/weighted_sum_cpu.cpp -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/weighted_sum_cpu.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      [10/65] c++ -MMD -MF /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/alpha_composite_cpu.o.d -pthread -B /mnt/h/Anaconda/envs/SPARK/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include -fPIC -O2 -isystem /mnt/h/Anaconda/envs/SPARK/include -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc -I/mnt/h/Anaconda/envs/SPARK/include/cub -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/TH -I/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/include/THC -I/mnt/h/Anaconda/envs/SPARK/include -I/mnt/h/Anaconda/envs/SPARK/include/python3.9 -c -c /tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/alpha_composite_cpu.cpp -o /tmp/pip-req-build-d6qs4fxc/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-d6qs4fxc/pytorch3d/csrc/compositing/alpha_composite_cpu.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
          subprocess.run(
        File "/mnt/h/Anaconda/envs/SPARK/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-d6qs4fxc/setup.py", line 134, in <module>
          setup(
                 _run_ninja_build(
        File "/mnt/h/Anaconda/envs/SPARK/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pytorch3d)

**Comment by hhuzhouhui** [comment]
+1 have you get a solution?    thank!

**Comment by bottler** [comment]
nvcc is missing some CUDA headers. This is a problem with the cuda setup? What is CUDA_HOME, and what is the output of `which nvcc`?

**Comment by pp350565935** [comment]
> nvcc 缺少一些 CUDA 标头。这是 cuda 设置的问题吗？CUDA_HOME 是什么，输出是什么`which nvcc`？

First of all, thank you for your reply.

I think it might be a problem with cuda settings, but I don't know how to solve it

(MonoFaceCompute) weiwei@WEIWEI:/mnt/d/AI_program_TS/YL/pytorch3d-0.6.2$ echo $CUDA_HOME
/mnt/d/AI_System/Anaconda/envs/SPARK

But I use
conda install pytorch3d -c pytorch3d
Installed pytorch3d

But the project I run seems to point to pytorch3d.git@v0.6.2
So I think I may still need to install a specific ytorch3d version

**Comment by pp350565935** [comment]
> +1 have you get a solution? thank!

This is my installation process

conda install -c bottler nvidiacub

conda install -c fvcore -c iopath -c conda-forge fvcore iopath

If the error "subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1" appears

Open pytorch3d/setup.py
Edit

cmdclass={'build_ext': BuildExtension}
to
cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False)}

I used
conda install pytorch3d -c pytorch3d
success Installed pytorch3d

But it seems that only the latest version can be installed
