### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by zhch12121** [facebookresearch/pytorch3d#1926]
Command I run:
pip install "git+https://github.com/facebookresearch/pytorch3d.git"

Python 3.11, Windows 11.

error log (partial):
ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\zhch1\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\utils\cpp_extension.py", line 2105, in _run_ninja_build
          subprocess.run(
        File "C:\Users\zhch1\anaconda3\envs\unique3d-py311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by bottler** [comment]
We can't help much with Windows issues, but much more detail would be needed for anyone to help here. How have you set up the environment? Have you looked at other recent issues which show how people have been successful on Windows.
