### ISSUE TITLE
can't convert CUDA tensor to numpy when joining meshes

### ISSUE THREAD

**Issue by alex-helm** [facebookresearch/pytorch3d#199]
Hi. I'm trying to use join_meshes_as_batch() to create a scene from differently textured meshes which I loaded from .obj with load_objs_as_meshes(). However, I get the error: TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first. I saw issue #175 which seemed related. In my case I'm not sure how to convert to cpu or otherwise solve this. I hope this is a sufficient description. Thank you so much for your help!

**Comment by bottler** [comment]
Can you share a bit more of your code and the traceback of the error please?

**Comment by alex-helm** [comment]
Yes, sorry. I realized I should've included code:

imports

sys.path.append(os.path.abspath(''))
device = torch.device('cuda:0')
torch.cuda.set_device(device)

mesh1 = load_objs_as_meshes(['./data/mesh1.obj'], device=device) mesh1_texture = mesh1.textures.maps_padded()

mesh2 = load_objs_as_meshes(['./data/mesh2.obj'], device=device) mesh2_texture = mesh2.textures.maps_padded()

mesh_batch = join_meshes_as_batch([mesh1, mesh2], include_textures=True)

etc.


Also, here is the traceback:

Traceback (most recent call last):
  File "run.py", line 74, in <module>
    renderer.renderSceneTextured(0)
  File "/home/user/bayesian-scene-illusions/render_sampled_scenes/SceneRenderer.py", line 51, in renderSceneTextured
    mesh_batch = join_meshes_as_batch([mesh1, mesh2], include_textures=True)
  File "/home/user/conda_envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/structures/meshes.py", line 1446, in join_meshes_as_batch
    tex = Textures(**kwargs)
  File "/home/user/conda_envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/structures/textures.py", line 117, in __init__
    maps = _pad_texture_maps(maps)
  File "/home/user/conda_envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/structures/textures.py", line 45, in _pad_texture_maps
    image = resize(image.permute(2, 0, 1)).permute(1, 2, 0)
  File "/home/user/conda_envs/pytorch3d/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/home/user/conda_envs/pytorch3d/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 136, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/home/user/conda_envs/pytorch3d/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 142, in to_pil_image
    npimg = np.transpose(pic.numpy(), (1, 2, 0))
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Thank you!

**Comment by bottler** [comment]
I think you have the same issue as #175. This has been fixed since the latest release. If you can install a nightly build then you should be fine. 

If you can't, then as a workaround you can load the meshes on cpu, join them, and then move them to the GPU.

Fix is https://github.com/facebookresearch/pytorch3d/commit/0c595dcf5b715ea1321825e0fe92ffa74e798d4f
