### ISSUE TITLE
How to rendering with multi-gpu by using torch.nn.DataParallel

### ISSUE THREAD

**Issue by ocean1100** [facebookresearch/pytorch3d#213]
I've defined a model, which includes a renderer as its attribute, rendering in forward, like this,

    class Net1(nn.Module): 
        def __init__(self, cam_cnt, image_size, base_mesh, uv_coords, uv_tri, device): 
            super(Net1, self).__init__() 
            self.device = device 
            self.renderer = self._init_render(device) 

        def forward(self, cam_paras, target_images):
            cam_ids = cam_paras['cam_ids'].squeeze()
            focal_length = cam_paras['focal_length']
            principal_point = cam_paras['principal_point']
            R = cam_paras['R']
            T = cam_paras['T']
            assert len(cam_ids) == len(target_images)
            cameras = SfMPerspectiveCameras(focal_length=focal_length,
                                        principal_point=principal_point, R=R, T=T, device=self.device)
            N = len(cam_ids)
            meshes = self.mesh_block(N)
            _img, _pix_to_face = self.renderer(meshes, cameras=cameras)

        def _init_render(self, device):
            raster_settings = RasterizationSettings(
                    image_size=max(cfg.dataset.image_size), 
                    blur_radius=0.0, 
                    faces_per_pixel=1, 
                    bin_size=0,  # this setting controls whether naive or coarse-to-fine rasterization is used
                    max_faces_per_bin=None,  # this setting is for coarse rasterization
                    perspective_correct=False
               )
            lights = DirectionalLights(
                device=device,
                direction=[[0.0, 0.0, -3.0]],
                ambient_color=((1.0, 1.0, 1.0),),
                diffuse_color=((0.0, 0.0, 0.0),),
                specular_color=((0.0, 0.0, 0.0),),)
                materials = Materials(
                device=device,
                ambient_color=((1, 1, 1),),
                diffuse_color=((1, 1, 1),),
                specular_color=((0, 0, 0),),
                shininess=120,
            )
            renderer = MyMeshRenderer(
                    rasterizer=MeshRasterizer(
                        cameras=None, 
                        raster_settings=raster_settings
                    ),
                    shader=TexturedSoftPhongShader(
                        cameras=None,
                        lights=lights,
                        materials=materials,
                    ),
            )

Then, torch.nn.DataParallel is used to make model parallel on multi-gpu, but torch.nn.DataParallel can only replicate model._modules, parameters and buffers to multi-gpu, while the lights and materials which are TensorProperties cannot be replicated, how to solve it? Thank you.

**Comment by gkioxari** [comment]
You should not use `self.device` to set the device in the forward pass. Note that this is general advice and not specific to PyTorch3D. Instead you should use the device your inputs to forward live in.

**Comment by ocean1100** [comment]
> You should not use `self.device` to set the device in the forward pass. Note that this is general advice and not specific to PyTorch3D. Instead you should use the device your inputs to forward live in.

Here's the error:
```
 File "train1.py", line 72, in train   
    train_dataloader = DataLoader(train_data, batch_size=8, shuffle=False,   
 collate_fn=train_data.collate_fn, num_workers=8)    
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/optim/lbfgs.py",  
   line 307, in step    
    orig_loss = closure()   
  File "train1.py", line 103, in closure    
    pred_pix, pre_tex, sigma = net(cam_paras, target_images)  
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/xx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Projects/dense_projects/face-profile-sdk/neural-face-profiling/optimizing/network/nfpnet1.py", line 129, in forward
    _img, _pix_to_face = self.renderer(meshes, cameras=cameras)
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Projects/dense_projects/face-profile-sdk/neural-face-profiling/optimizing/network/nfp_mesh_renderer.py", line 53, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shader.py", line 239, in forward
    materials=materials,
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shading.py", line 80, in phong_shading
    pixel_coords, pixel_normals, lights, cameras, materials
  File "/home/xxx/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shading.py", line 35, in _apply_lighting
    diffuse_color = materials.diffuse_color * light_diffuse
RuntimeError: expected device cuda:0 but got device cuda:1
```

If I change the materials' and lights' device in forward by 
```
materials = kwargs.get("materials", self.renderer.shader.materials).to(target_images.device)
lights = kwargs.get("lights", self.renderer.shader.lights).to(target_images.device)
```
then it's not work either because the nn.DataParallel didn't replicate the `materials.diffuse_color`, 
the replicated models own the same diffuse_color memory address,
```
(Pdb) id(modules[0].renderer.shader.materials.diffuse_color)
140429256672752
(Pdb) id(modules[1].renderer.shader.materials.diffuse_color)
140429256672752
```
maybe the only way to solve it is to custom a dataparallel while handling the TensorProperties type ? Or use other parallel techs like nn.DistributedDataParallel?

**Comment by ocean1100** [comment]
Sorry for commenting so late. And thanks to you guys, I've solved this problem using nn.DistributedDataParallel, it works fine now.
