### ISSUE TITLE
Build Pytorch3d against Manually Installed PyTorch 1.6.0?

### ISSUE THREAD

**Issue by jiapei100** [facebookresearch/pytorch3d#239]
Hi, I successfully built **pytorch3d**, but duing the installation, it seems up-to-date **pytorch3d** keeps searching `torch==1.5.0`. However, I've **ALREADY** manually installed **PyTorch 1.6.0**. Just wonder where I can change this **==** to **>=** and directly use the manually installed **PyTorch 1.6.0** ????

```console
...
Extracting pytorch3d-0.2.0-py3.6-linux-x86_64.egg to /home/longervision/.local/lib/python3.6/site-packages
pytorch3d 0.2.0 is already the active version in easy-install.pth

Installed /home/longervision/.local/lib/python3.6/site-packages/pytorch3d-0.2.0-py3.6-linux-x86_64.egg
Processing dependencies for pytorch3d==0.2.0
Searching for torch==1.5.0
Reading https://pypi.org/simple/torch/
Downloading https://files.pythonhosted.org/packages/13/70/54e9fb010fe1547bc4774716f11ececb81ae5b306c05f090f4461ee13205/torch-1.5.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=dfaac4c5d27ac80705956743c34fb1ab5fb37e1646a6c8e45f05f7e739f6ea7c
...
```

Thank you very much
Pei

**Comment by bottler** [comment]
Can you explain in more detail what you have done? What program's output is pasted here?

**Comment by jiapei100** [comment]
@bottler 
Oh, Hi, yes...
- For **pytorch3d**, I only did ` python setup.py build` and trying to install with `python setup.py install`, but failed with the above message, nothing **failed** yet, but did you see? It starts installing **torch-1.5.0** automatically, which is **NOT** what I want.

```console
Searching for torch==1.5.0
Reading https://pypi.org/simple/torch/
Downloading https://files.pythonhosted.org/packages/13/70/54e9fb010fe1547bc4774716f11ececb81ae5b306c05f090f4461ee13205/torch-1.5.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=dfaac4c5d27ac80705956743c34fb1ab5fb37e1646a6c8e45f05f7e739f6ea7c
```

- For **PyTorch**, I had successfully installed the **up-to-date** version **1.6.0** **ALREADY**. That is why I seriously do **NOT** expect the auto-installation of **PyTorch 1.5.0** again, which is going to replace the exisiting **PyTorch 1.6.0**.

The reason that cause the above symptom is clearly from **PyTorch3d**, right? I believe there must be a place for me to specify using **already installed torch 1.6.0** instead of **searching for torch==1.5.0 and downloading from the Internet again and again** ....

**Comment by bottler** [comment]
There's a lot I don't understand here. Pytorch 1.5 is the latest release and you have somehow installed got a newer bleeding-edge installation, but I don't know why it's not happy with that. It sounds like the 1.6 can be found - because it was used in the compilation of pytorch3d.

However, how about trying `pip install --no-deps -e .` instead of `python setup.py install`?
It would be interesting to see the full output of both commands and also of `pip list`.

**Comment by jiapei100** [comment]
```console
 7   master  ✔  pip install --no-deps -e .                                                                                  ✱  /media/longervision/Seagate/OpenSource/00_bigcompanies/facebook/pytorch3d 
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///media/longervision/Seagate/OpenSource/00_bigcompanies/facebook/pytorch3d
Installing collected packages: pytorch3d
  Attempting uninstall: pytorch3d
    Found existing installation: pytorch3d 0.2.0
    Uninstalling pytorch3d-0.2.0:
      Successfully uninstalled pytorch3d-0.2.0
  Running setup.py develop for pytorch3d
Successfully installed pytorch3d
```

Solved???

**Comment by jiapei100** [comment]
My purpose of manually building **pytorch3** is actually for **meshrcnn**. Now, it seems still problematic:


```console
 36   master  ✔  pip install --no-deps -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file://....../meshrcnn
Installing collected packages: meshrcnn
  Attempting uninstall: meshrcnn
    Found existing installation: meshrcnn 1.0
    Uninstalling meshrcnn-1.0:
      Successfully uninstalled meshrcnn-1.0
  Running setup.py develop for meshrcnn
Successfully installed meshrcnn
Traceback (most recent call last):
  File "~/.local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 75, in main
    return command.main(cmd_args)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 114, in main
    return self._main(args)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 226, in _main
    self.handle_pip_version_check(options)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 155, in handle_pip_version_check
    timeout=min(5, options.timeout)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 100, in _build_session
    index_urls=self._get_index_urls(options),
  File "~/.local/lib/python3.6/site-packages/pip/_internal/network/session.py", line 249, in __init__
    self.headers["User-Agent"] = user_agent()
  File "~/.local/lib/python3.6/site-packages/pip/_internal/network/session.py", line 159, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "~/.local/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 634, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1983, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
    return self._has(path)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1854, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1731, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1688, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '~/.local/lib/python3.6/site-packages/meshrcnn-1.0-py3.6.egg'
```

**Comment by bottler** [comment]
(Quite possibly the pytorch3d installation succeeded. The question is does pytorch3d work? It would be interesting to know if you can run the tests or a tutorial. )

I don't know what happened with meshrcnn but it might also have worked. You can try importing meshrcnn in python, and you can try looking for meshrcnn things in `~/.local/lib/python3.6/site-packages`

**Comment by jiapei100** [comment]
@bottler 
Hey, @bottler , can you please take a look at [https://github.com/facebookresearch/meshrcnn/issues/40](https://github.com/facebookresearch/meshrcnn/issues/40) ?

**Comment by jiapei100** [comment]
Yes, @bottler 
The final solution is as suggested by you:

`pip install --no-deps --prefix=/home/longervision/.local/ . `

Thank you ....
