### ISSUE TITLE
How do I install PyTorch3D on Windows 10; CUDA 10.2; Python 3.7; Pytorch 1.5?

### ISSUE THREAD

**Issue by RyanStark223232** [facebookresearch/pytorch3d#256]
I have done the following steps according to INSTALL.md provided by Pytorch3D

1. On Anaconda Prompt
conda create -n pytorch3d python=3.7
conda activate pytorch3d
conda install -c pytorch pytorch torchvision cudatoolkit=10.2
conda install -c conda-forge -c fvcore fvcore
git clone https://github.com/facebookresearch/pytorch3d.git

2. On x64 Native Tools Command Prompt for VS 2019
cd pytorch3d
activate pytorch3d
python setup.py install

And then I got the following error message

C:\Users\wongh\pytorch3d>python setup.py install
running install
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pytorch3d._C' extension
b'F\x00i\x00l\x00e\x00s\x00\\\x00J\x00a\x00v\x00a\x00\\\x00j\x00d\x00k\x00-\x001\x004\x00\\\x00b\x00i\x00n\x00 \x00w\x00a\x00s\x00 \x00u\x00n\x00e\x00x\x00p\x00e\x00c\x00t\x00e\x00d\x00 \x00a\x00t\x00 \x00t\x00h\x00i\x00s\x00 \x00t\x00i\x00m\x00e\x00.\x00\r\x00\n\x00'
Traceback (most recent call last):
  File "setup.py", line 100, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\wongh\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\wongh\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\wongh\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\wongh\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\wongh\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\wongh\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\wongh\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\wongh\anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\wongh\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\wongh\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\wongh\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\wongh\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\wongh\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\wongh\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\wongh\anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\wongh\anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\wongh\anaconda3\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\wongh\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 521, in win_wrap_ninja_compile
    self.compiler.initialize()
  File "C:\Users\wongh\anaconda3\lib\distutils\_msvccompiler.py", line 239, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
    return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
  File "C:\Users\wongh\anaconda3\lib\site-packages\setuptools\msvc.py", line 1623, in return_env
    if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
  File "C:\Users\wongh\anaconda3\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Thank you for your patience and time

**Comment by bottler** [comment]
I don't really know what is happening here. The weird string being printed just before the traceback seems to be a funny encoding of `Files\java\jdk-14\bin was unexpected at this time`. Let's assume that something somewhere is not happy with spaces in filenames, which are being supplied somewhere. Perhaps start by looking at environment variables like `PYTHONPATH`, `PATH` and `JAVA_HOME`. If they contain filenames / paths with spaces, try removing them (if they are superfluous) or replacing them with the equivalent 8.3 path / short path. 

There is some advice for finding 8.3 paths [here](https://superuser.com/a/728792/706576).

**Comment by bottler** [comment]
It is also possible that this issue is ninja-specific. You could try editing the line `if os.getenv("PYTORCH3D_NO_NINJA", "0") == "1":` in `setup.py` to `if 1:` and see if that fixes it. This makes the build use the older build system.

**Comment by RyanStark223232** [comment]
Thank you for your reply.
I have tested both possible solutions that you suggest, but unfortunately, neither of them work. On the other hand, I have found a workaround buy installing pytorch3d using the Ubuntu subsystem on Windows, and I will probably keep using that onwards. Regardless, thank you for your time :)
