### ISSUE TITLE
PyTorch3D with torch.nn.DataParallel 

### ISSUE THREAD

**Issue by Gaozhongpai** [facebookresearch/pytorch3d#271]
## 🐛 Bugs / Unexpected behaviors

```
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda101_1572909250636/work/interface_cuda/interface.cpp:944
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda101_1572909250636/work/interface_cuda/interface.cpp:945
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda101_1572909250636/work/interface_cuda/interface.cpp:946
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    trainer.train()
  File "/home/pai/Desktop/code/unsup3dface/unsup3d/trainer.py", line 136, in train
    metrics = self.run_epoch(self.train_loader, epoch)
  File "/home/pai/Desktop/code/unsup3dface/unsup3d/trainer.py", line 169, in run_epoch
    m = self.model(input_im, mask, id_code, landmark)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pai/Desktop/code/unsup3dface/unsup3d/model3d.py", line 305, in forward
    self.recon_im_neutr = renderer(meshes_neutral)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/pytorch3d/renderer/mesh/renderer.py", line 67, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shader.py", line 207, in forward
    materials=materials,
  File "/home/pai/miniconda3/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shading.py", line 108, in gouraud_shading
    vertex_colors = meshes.textures.verts_rgb_packed()
  File "/home/pai/miniconda3/lib/python3.7/site-packages/pytorch3d/structures/textures.py", line 232, in verts_rgb_packed
    split_size=self._num_verts_per_mesh,
  File "/home/pai/miniconda3/lib/python3.7/site-packages/pytorch3d/structures/utils.py", line 220, in padded_to_packed
    for (i, v) in enumerate(split_size)
  File "/home/pai/miniconda3/lib/python3.7/site-packages/pytorch3d/structures/utils.py", line 220, in <listcomp>
    for (i, v) in enumerate(split_size)
RuntimeError: parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by Gaozhongpai** [comment]
This is related to the issue: https://github.com/facebookresearch/pytorch3d/issues/267#issue-655564919

**Comment by bottler** [comment]
Please can you provide complete code?

**Comment by gkioxari** [comment]
We won't be able to help you if you don't provide reproducible code? How are we supposed to guess what is going on from this stack trace? We are no magicians. In the future, such issues will be closed immediately.

**Comment by nikhilaravi** [comment]
Please also provide a clear description of your use case and environment.

**Comment by Gaozhongpai** [comment]
> We won't be able to help you if you don't provide reproducible code. How are we supposed to guess what is going on from this stack trace? We are no magicians. In the future, such issues will be closed immediately.

Thank you for your reply. I think this issue is the same as this one https://github.com/facebookresearch/pytorch3d/issues/267#issuecomment-657702547. Please check the example code provided by @fanfanda.
