### ISSUE TITLE
tutorial: render textured meshes - AttributeError: 'NoneType' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by vpolflie** [facebookresearch/pytorch3d#301]
## 🐛 Bugs / Unexpected behaviors
Hi,

I am trying to run the render textured meshes in a python script and I got the following error: 

AttributeError: 'NoneType' object has no attribute 'reshape'

## Instructions To Reproduce the Issue:

I currently have the following code and I am using the cow.obj/mtl/texture that the tutorial provides.

### Code

```
import os
import torch
import matplotlib.pyplot as plt
from skimage.io import imread

# Util function for loading meshes
from pytorch3d.io import load_objs_as_meshes, load_obj

# Data structures and functions for rendering
from pytorch3d.structures import Meshes, Textures
from pytorch3d.renderer import (
    look_at_view_transform,
    OpenGLPerspectiveCameras,
    PointLights,
    DirectionalLights,
    Materials,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    SoftPhongShader
)

# add path for demo utils functions
import sys
import os
sys.path.append(os.path.abspath(''))

from plot_image_grid import image_grid

# Setup
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")

# Set paths
#DATA_DIR = "./Assets/Low_Poly/eighth_clothes_hair"
#obj_filename = os.path.join(DATA_DIR, "eighth_clothes_hair.obj")
DATA_DIR = "./Assets/Cow"
obj_filename = os.path.join(DATA_DIR, "cow.obj")


# Load obj file
mesh = load_objs_as_meshes([obj_filename], device=device)

# Initialize an OpenGL perspective camera.
# With world coordinates +Y up, +X left and +Z in, the front of the cow is facing the -Z direction.
# So we move the camera by 180 in the azimuth direction so it is facing the front of the cow.
R, T = look_at_view_transform(2.7, 0, 180)
cameras = OpenGLPerspectiveCameras(device=device, R=R, T=T)

# Define the settings for rasterization and shading. Here we set the output image to be of size
# 512x512. As we are rendering images for visualization purposes only we will set faces_per_pixel=1
# and blur_radius=0.0. We also set bin_size and max_faces_per_bin to None which ensure that
# the faster coarse-to-fine rasterization method is used. Refer to rasterize_meshes.py for
# explanations of these parameters. Refer to docs/notes/renderer.md for an explanation of
# the difference between naive and coarse-to-fine rasterization.
raster_settings = RasterizationSettings(
    image_size=512,
    blur_radius=0.0,
    faces_per_pixel=1,
)

# Place a point light in front of the object. As mentioned above, the front of the cow is facing the
# -z direction.
lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])

# Create a phong renderer by composing a rasterizer and a shader. The textured phong shader will
# interpolate the texture uv coordinates for each vertex, sample from a texture image and
# apply the Phong lighting model
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device,
        cameras=cameras,
        lights=lights
    )
)

images = renderer(mesh)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off")
plt.axis("off")
plt.show()
```
### Run Command

I just ran the script with:
python render.py

### Log

```
anaconda3/envs/pytorch-3d/lib/python3.8/site-packages/pytorch3d/io/obj_io.py:70: UserWarning: Faces have invalid indices
  warnings.warn("Faces have invalid indices")
Traceback (most recent call last):
  File "/snap/pycharm-community/207/plugins/python-ce/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/207/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/vpolflie/projects/pytorch-3D/render.py", line 84, in <module>
    images = renderer(mesh)
  File "/home/vpolflie/anaconda3/envs/pytorch-3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vpolflie/anaconda3/envs/pytorch-3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 67, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/vpolflie/anaconda3/envs/pytorch-3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vpolflie/anaconda3/envs/pytorch-3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 98, in forward
    texels = interpolate_vertex_colors(fragments, meshes)
  File "/home/vpolflie/anaconda3/envs/pytorch-3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/texturing.py", line 107, in interpolate_vertex_colors
    vertex_textures = meshes.textures.verts_rgb_padded().reshape(-1, 3)  # (V, C)
AttributeError: 'NoneType' object has no attribute 'reshape'
python-BaseException

```

**Comment by vpolflie** [comment]
A similar issue seems to have occurred in #293 however his solution of reinstalling the library didn't yield any results.

**Comment by vpolflie** [comment]
Apparently the updates aren't pushed yet to the the stable builds. This issue can be solved by installing the nightly build

**Comment by ashwath98** [comment]
Hey, were you able to get render.py working, rn after nightly install I'm getting the following error

 from pytorch3d.structures import Textures
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Textures' from 'pytorch3d.structures' (C:\Users\shett\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\structures\__init__.py)

**Comment by vpolflie** [comment]
Just remove the import:

`from pytorch3d.structures import Meshes, Textures`

--->

`from pytorch3d.structures import Meshes`
