### ISSUE TITLE
Pytorch3D requires python version >=3.5 and <3.6

### ISSUE THREAD

**Issue by alexzhou907** [facebookresearch/pytorch3d#321]
When calling " conda install pytorch3d -c pytorch3d-nightly " I am getting the following error specifying python version constraint.

```
Specifications:

  - pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

```

I thought Pytorch3D supports version >=3.6? I was originally using python 3.6 and has some packages that only work with this python version. Is this the expected behavior?

**Comment by bottler** [comment]
Please paste the output of `conda list` and `conda info`.

**Comment by alexzhou907** [comment]
This is a fresh environment install

conda list:

```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py36_0
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
ncurses                   6.2                  he6710b0_1
openssl                   1.1.1g               h7b6447c_0
pip                       20.2.2                   py36_0
python                    3.6.10               h7579374_2
readline                  8.0                  h7b6447c_0
setuptools                49.6.0                   py36_0
sqlite                    3.32.3               h62c20be_0
tk                        8.6.10               hbc83047_0
wheel                     0.34.2                   py36_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3

```

conda info:

```
     active environment : pytorch3d
    active env location : /viscam/u/alexzhou907/anaconda3/envs/pytorch3d
            shell level : 2
       user config file : /sailhome/alexzhou907/.condarc
 populated config files :
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.23
       base environment : /viscam/u/alexzhou907/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /viscam/u/alexzhou907/anaconda3/pkgs
                          /sailhome/alexzhou907/.conda/pkgs
       envs directories : /viscam/u/alexzhou907/anaconda3/envs
                          /sailhome/alexzhou907/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.4.0-137-generic ubuntu/16.04.5 glibc/2.23
                UID:GID : 20375:100
             netrc file : None
           offline mode : False

```

**Comment by bottler** [comment]
You need to install the dependencies of pytorch3d, as explained in https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md.

**Comment by alexzhou907** [comment]
After installing the dependencies, running "conda install pytorch3d -c pytorch3d" gives

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.                                                                                                     failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==10.2=0

Your installed version is: 10.2


```

Running "conda install pytorch3d -c pytorch3d-nightly" works, but if I run python and "from pytorch3d.renderer import TexturesAtlas", I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/viscam/u/alexzhou907/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/viscam/u/alexzhou907/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

```

**Comment by bottler** [comment]
There are a few issues here.

I am pretty sure that you will be ok to install in a new environment. Assuming you want to stay with python 3.6 and cuda 10.1, this works for me right now and gives me an install which doesn't fail to import.

```
conda create -p /path/to/foo python=3.6
conda activate /path/to/foo
conda install -c pytorch cudatoolkit=10.1 pytorch=1.6.0 torchvision
conda install -c conda-forge fvcore
conda install -c pytorch3d-nightly pytorch3d
```

If I change this, and try to install fvcore before pytorch, then pytorch fails to install today - or, if I don't specify the version, gives me an old version. I think this is something to do with blas versions and some new release of something. Specifying the current version of pytorch is probably optional here.

Trying to use `conda install -c pytorch3d pytorch3d` will not work with the latest pytorch as the latter is too new.

I think something strange has happened to your environment, and I suggest trying these steps. Is it possible you tried a pip install of pytorch3d? It looks like you have a build of pytorch3d which is expecting a cpu-only build of pytorch.

**Comment by bottler** [comment]
I am closing this as I think it is very specific and the oddities observed are now history.
