### ISSUE TITLE
How can I render a mesh to an image without textures?

### ISSUE THREAD

**Issue by WMCh** [facebookresearch/pytorch3d#333]
Hi, I tried to render meshes without textures using the codes in the tutorials, but failed because the shader samples the textures of meshes by default.
```
Traceback (most recent call last):
  File "e:/code/python/Test/render_textured_meshes.py", line 81, in <module>
    images = renderer(mesh)
  File "D:\programs\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\programs\Anaconda3\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\renderer.py", line 49, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "D:\programs\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\programs\Anaconda3\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\shader.py", line 108, in forward
    texels = meshes.sample_textures(fragments)
  File "D:\programs\Anaconda3\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\structures\meshes.py", line 1500, in sample_textures
    raise ValueError("Meshes does not have textures")
ValueError: Meshes does not have textures
```
In short, how can I simply render a mesh without textures? Or if I modify the source code, will there be any bad effects? Looking forward to you reply, thank you!

**Comment by qiuyu96** [comment]
> Shaders require textures. Otherwise what are you shading?! This is also shown in the table at the bottom of the notes here
> 
> https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md
> 
> The only shader that doesn't require texture is the `SoftSilhouetteShader` which returns the silhouette of the object.
> If you want to shade your object but it doesn't have textures then you can assign it arbitrary RGB textures, e.g. white (1.0, 1.0, 1.0)

How to assign mesh's texture with arbitrary RGB textures? Thanks a lot!

**Comment by qiuyu96** [comment]
> Hi, I tried to render meshes without textures using the codes in the tutorials, but failed because the shader samples the textures of meshes by default.
> 
> ```
> Traceback (most recent call last):
>   File "e:/code/python/Test/render_textured_meshes.py", line 81, in <module>
>     images = renderer(mesh)
>   File "D:\programs\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "D:\programs\Anaconda3\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\renderer.py", line 49, in forward
>     images = self.shader(fragments, meshes_world, **kwargs)
>   File "D:\programs\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "D:\programs\Anaconda3\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\shader.py", line 108, in forward
>     texels = meshes.sample_textures(fragments)
>   File "D:\programs\Anaconda3\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\structures\meshes.py", line 1500, in sample_textures
>     raise ValueError("Meshes does not have textures")
> ValueError: Meshes does not have textures
> ```
> 
> In short, how can I simply render a mesh without textures? Or if I modify the source code, will there be any bad effects? Looking forward to you reply, thank you!

I think this url https://github.com/facebookresearch/pytorch3d/issues/51 will give you the answer.
