### ISSUE TITLE
transofrm3d gives weird Rotation matrix for some angles 

### ISSUE THREAD

**Issue by ajhamdi** [facebookresearch/pytorch3d#350]
## 🐛 Bugs / Unexpected behaviors

When running the following minimal code:
```python
import numpy as np
from pytorch3d.renderer import ( look_at_view_transform, look_at_rotation, MeshRenderer, MeshRasterizer, BlendParams,
, HardPhongShader, PointLights, SoftPhongShader)

R, T = look_at_view_transform(dist=2.2, elev=torch.from_numpy(np.array([-35,35,35]))
, azim=torch.from_numpy(np.array([-60,60,180])))
cameras = OpenGLPerspectiveCameras(device="cpu", R=R, T=T)

cameras.get_camera_center() 
```

 I get the following error 

```
/home/hamdiaj/anaconda3/envs/mytorch3d/lib/python3.7/site-packages/pytorch3d/transforms/transform3d.py:706: UserWarning: R is not a valid rotation matrix
  warnings.warn(msg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hamdiaj/anaconda3/envs/mytorch3d/lib/python3.7/site-packages/pytorch3d/renderer/cameras.py", line 123, in get_camera_center
    P = w2v_trans.inverse().get_matrix()
  File "/home/hamdiaj/anaconda3/envs/mytorch3d/lib/python3.7/site-packages/pytorch3d/transforms/transform3d.py", line 253, in inverse
    i_matrix = self._get_matrix_inverse()
  File "/home/hamdiaj/anaconda3/envs/mytorch3d/lib/python3.7/site-packages/pytorch3d/transforms/transform3d.py", line 223, in _get_matrix_inverse
    return torch.inverse(self._matrix)
RuntimeError: inverse_cpu: For batch 0: U(1,1) is zero, singular U.

```

**Comment by bottler** [comment]
Which versions of numpy, torch and pytorch3d are you using? The following is complete code snippet and runs for me with a pytorch3d from last week.

```
import torch 
import numpy as np
from pytorch3d.renderer.cameras import OpenGLPerspectiveCameras
from pytorch3d.renderer import look_at_view_transform

R, T = look_at_view_transform(
    dist=2.2,
    elev=torch.from_numpy(np.array([-35,35,35])),
    azim=torch.from_numpy(np.array([-60,60,180])))

cameras = OpenGLPerspectiveCameras(device="cpu", R=R, T=T)

cameras.get_camera_center()
```

**Comment by ajhamdi** [comment]
The problem happened when I had 
```
pytorch == 1.5.0
numpy  ==1.18.4

```
