### ISSUE TITLE
How to install pytorch3d on windows10?

### ISSUE THREAD

**Issue by AlbertoWang** [facebookresearch/pytorch3d#388]
## ❓ Questions on how to use PyTorch3D

How can I install pytorch3d on windows10 PC?
When I install, terminal shows:
`No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
running install
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
E:\ProgramStation\anaconda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'pytorch3d._C' extension
Emitting ninja build file E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:E:\ProgramStation\anaconda\envs\pytorch3d\lib\site-packages\torch\lib /LIBPATH:E:\ProgramStation\anaconda\envs\pytorch3d\libs /LIBPATH:E:\ProgramStation\anaconda\envs\pytorch3d\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit__C E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\ext.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\blending\sigmoid_alpha_blend_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\compositing\alpha_composite_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\compositing\norm_weighted_sum_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\compositing\weighted_sum_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\face_areas_normals\face_areas_normals_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\gather_scatter\gather_scatter_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\knn\knn_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\packed_to_padded_tensor\packed_to_padded_tensor_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\point_mesh\point_mesh.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\rasterize_meshes\rasterize_meshes_cpu.obj E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\rasterize_points\rasterize_points_cpu.obj /OUT:build\lib.win-amd64-3.7\pytorch3d\_C.cp37-win_amd64.pyd /IMPLIB:E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\_C.cp37-win_amd64.lib
fatal error C1905: 前端和后端不兼容(必须以同一处理器为目标)。
LINK : fatal error LNK1257: 代码生成失败
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\link.exe' failed with exit status 1257`

So does it mean pytorch3d can not be installed on windows10?
It seems that the problem is caused by the VS or something else?

**Comment by bottler** [comment]
It says "no CUDA runtime found.". Are you trying to use cuda or just install the CPU version. If you want to use CUDA, please make sure you have installed it, and that you are working in a conda environment where pytorch alongside the relevant cudatoolkit is installed.

If you are not using cuda, you need to have visual studio 2019 and be in its version of the command line (specifically x64). How did you get to your command line?

**Comment by AlbertoWang** [comment]
I have installed CUDA, as it shows in next line:`using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1' running install running`
My CUDA version is 10.1, and I can see that from the command line:
```bash
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243
```
And my command line is run from _x64 Native Tools Command Prompt for VS 2019_

I install torch and torchvision from pytorch website using **conda**

**Comment by AlbertoWang** [comment]
And version of installed torch and torchvision are listed as follows
```bash
>>> import torch
>>> import torchvision
>>> print(torch.__version__)
1.6.0
>>> print(torchvision.__version__)
0.7.0
>>> quit()
```

**Comment by AlbertoWang** [comment]
I reinstalled torch and install pytorch3d again, now the erros goes like this:
```bash
[25/25] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IE:\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc -IE:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\include -IE:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\include\torch\csrc\api\include -IE:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\include\TH -IE:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IE:\ProgramStation\anaconda\envs\torch\include -IE:\ProgramStation\anaconda\envs\torch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c E:\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\knn\knn.cu -o E:\ProgramStation\pytorch3d-0.2.5\build\temp.win-amd64-3.7\Release\ProgramStation\pytorch3d-0.2.5\pytorch3d\csrc\knn\knn.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
E:/ProgramStation/anaconda/envs/torch/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

E:/ProgramStation/anaconda/envs/torch/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

knn.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "E:\ProgramStation\anaconda\envs\torch\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 100, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "E:\ProgramStation\anaconda\envs\torch\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 631, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "E:\ProgramStation\anaconda\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Comment by bottler** [comment]
I can't see an actual error message. I don't really know what to suggest. 
Does it take a long time to produce the error? Does nvcc use a lot of memory just before the error?

**Comment by bottler** [comment]
You will need to make various changes to pytorch to build, if you haven't already - see https://github.com/facebookresearch/pytorch3d/issues/323 - but I think you are stuck on something else at the moment.

**Comment by grau4** [comment]
Hi, 
I'm not sure if this is gonna be helpful to anyone, or whether it's obvious, but it helped me to get the installation done on Windows after many trials.

The compilation errors "RuntimeError: Error compiling objects for extension" indicated above by @AlbertoWang persist sometimes even when you do the patches and update your VS compilers. I tried all possible and reasonable permutations indicated in the INSTALL guide (pytorch 1.6 with CUDA 10.2, pytorch1.4 with CUDA 10.1, etc ) and nothing worked.

I noticed that during compilation ALL folders in the "\NVIDIA GPU Computing Toolkit\CUDA\" are listed to assemble a command line, which is then used to compile some CUDA/C files. As a consequence, regardless of whether you set the right CUDA version on your path variable, if you have several CUDA versions installed these will ALL be used for compilation and hence the error. This means that setup.py does not detect the environment's CUDA version to be used, but rather whichever(s) you have currently in your CUDA folder.

A simple hack I found was to move the unnecessary CUDA versions from "\NVIDIA GPU Computing Toolkit\CUDA\" to a temp/ folder before running "python setup.py install" and keep only the one you used to setup the pytorch3d environment. That solved the bug and  made the installation run successfully. After compilation you can move them back safely to the CUDA directory.

**Comment by thavlik** [comment]
@grau4 thank you!!! This was messing me up as well!

Also, don't forget to mod the pytorch source code LOL

**Comment by nikhilaravi** [comment]
@AlbertoWang do you still have any questions or can this issue be closed?
