### ISSUE TITLE
How to install PyTorch3D on Windows 10

### ISSUE THREAD

**Issue by yuhaoooo** [facebookresearch/pytorch3d#449]
## How to install PyTorch3D on Windows 10 PC?

Hi, I encouter some problems when compiling the PyTorch3D 0.3.0 on Windows 10 PC. There is some information to help you locate the problems.

### Software Version
Python: 3.8.5
PyTorch: 1.7.0
CUDA: 10.1
Torchvision: 0.8.1
MSVC: Microft Visual Studio 2019, 14.27.29110

### The Compiling Log
The entire log can be found in [Logs](https://github.com/facebookresearch/pytorch3d/files/5542433/logs.txt). Here are some important parts:
```
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    setup(
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 626, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\ProgramData\Anaconda3\envs\new-pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

Could you help me to find way out? Thanks a lot.

**Comment by bottler** [comment]
The specific errors from the logs are unfamiliar to me. They are as follows

```
D:/ProgramData/Anaconda3/envs/new-pytorch/lib/site-packages/torch/include\torch/csrc/jit/ir/ir.h(1347): error: member "torch::jit::ProfileOptionalOp::Kind" may not be initialized
```
and
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/include\xutility(4387): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function
          detected during:
            instantiation of "_OutIt std::_Move_unchecked1(_InIt, _InIt, _OutIt, std::false_type) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]" 

(4403): here
            instantiation of "_OutIt std::_Move_unchecked(_InIt, _InIt, _OutIt) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]" 

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/include\vector(1353): here
            instantiation of "std::vector<_Ty, _Alloc>::iterator std::vector<_Ty, _Alloc>::erase(std::vector<_Ty, _Alloc>::const_iterator) [with _Ty=torch::OrderedDict<std::string, at::Tensor>::Item, _Alloc=std::allocator<torch::OrderedDict<std::string, at::Tensor>::Item>]" 

D:/ProgramData/Anaconda3/envs/new-pytorch/lib/site-packages/torch/include\torch/csrc/api/include/torch/ordered_dict.h(419): here
            instantiation of "void torch::OrderedDict<Key, Value>::erase(const Key &) [with Key=std::string, Value=at::Tensor]" 

D:/ProgramData/Anaconda3/envs/new-pytorch/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/modules/container/parameterdict.h(51): here
```

This may match with errors other people have seen. Note that these things are not specific to pytorch3d, they are problems where the compiler is not liking pytorch headers.
It may be possible to look in those pytorch files and fix the problem (In other versions of pytorch it has been necessary to fix things to make pytorch3d build on windows.

**Comment by yuhaoooo** [comment]
Is there another way to install PyTorch3D in Windows, e.g., gcc (windows) instead of MSVC?

Sorry, I am not familir with these compilers.

**Comment by bottler** [comment]
I don't think changing compilers will provide an easy solution, because I think cuda on windows needs MSVC.

One possible solution would be to go back to pytorch version 1.6.0 (in a new environment) and then you should be able to build pytorch3d using the instructions in Issue #323 .

**Comment by yuhaoooo** [comment]
OK, I will try it.

**Comment by yuhaoooo** [comment]
Tanks a lot, I successfully install PyTorch3D with PyTorch 1.6.0, CUDA 10.1.

In addition, `python/Lib/site-packages/torch/include/torch/csrc/jit/api/module.h`
```
- static CONSTEXPR_EXCEPT_WIN_CUDA bool all_slots = true;
+ static const bool all_slots = true;
```
