### ISSUE TITLE
Crop Pointcloud

### ISSUE THREAD

**Issue by Zumbalamambo** [facebookresearch/pytorch3d#480]
I have a pointcloud along with the camera intrinsic and extrinsic parameters. How can I crop the pointcloud based on these camera parameters using pytorch3d?

**Comment by nikhilaravi** [comment]
@Zumbalamambo what do you mean by crop the pointcloud? Do you only want to retain the points which are visible from the camera?

**Comment by Zumbalamambo** [comment]
@nikhilaravi Yes exactly. I have got the camera matrix and the extrinsic matrix as well.

**Comment by nikhilaravi** [comment]
@Zumbalamambo you can use the PyTorch3D pointcloud rasterizer (with the camera matrices that you have) to rasterize an output image. The output of rasterization are the PointsFragments - from this you can use the `idx` tensor - this gives you the indices of the points in the input Pointcloud which overlap with each pixel in the image.  These are the indices of the visible points. 

If you want only the visible points, in the rasterization settings you can set `points_per_pixel = 1`. If you want all the points within the bounding box that is visible to the camera, you can set `points_per_pixel=50` or something higher and this will give you all the points which overlap with any of the image pixels even if they are occluded. 

Example code (untested)

```
# Init your Pointcloud here
points = torch.ones((N, P, 3))

# Set up cameras
cameras = FoVPerspectiveCameras(device=device, R=R, T=T, K=K)

raster_settings = PointsRasterizationSettings(
    image_size=512, 
    radius = 0.003,
    points_per_pixel = 1 
)


# Create a points rasterizer
rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)

fragments = rasterizer(points)

# These are indices into the points.points_packed() tensor
visible_idxs = torch.unique(fragments.idx)

visible_points = points.points_packed()[visible_idxs]. # (len(visible_idxs), 3))
```

**Comment by bottler** [comment]
Perhaps, in that code, you can set the `image_size` to 1 (i.e. a 1x1 image) and make `points_per_pixel` large enough for all the points, and then get the full set of point indices from the fragments, however occluded they are.

**Comment by Zumbalamambo** [comment]
@nikhilaravi  I tried to load the point cloud as follows,

```
from pytorch3d import io

points = io.load_ply("assets/factory.ply")
```

Unfortunately, it throws the following error,
```

Traceback (most recent call last):
  File "/home/Workspace/main.py", line 2, in <module>
    from pytorch3d.renderer import FoVPerspectiveCameras
  File "/home/anaconda3/envs/open3d/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/anaconda3/envs/open3d/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: /home/anaconda3/envs/open3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

```

**Comment by bottler** [comment]
This is an installation problem. You probably have a mismatch between the pytorch version which pytorch3d was built with and the pytorch version you have installed in that environment. Can you paste/attach the output of `conda list` and explain how you installed?

**Comment by Zumbalamambo** [comment]
@bottler please find the installed librarires as follows,

```
_libgcc_mutex             0.1                        main  
absl-py                   0.11.0                   pypi_0    pypi
astroid                   2.4.2                    py38_0  
astunparse                1.6.3                    pypi_0    pypi
backcall                  0.2.0                      py_0  
backports                 1.0                pyhd3eb1b0_2  
backports.functools_lru_cache 1.6.1              pyhd3eb1b0_0  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.3              pyhb0f4dca_0  
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2020.10.14                    0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.11.8        py38h06a4308_0  
cffi                      1.14.0           py38he30daa8_1  
chardet                   3.0.4           py38h06a4308_1003  
click                     7.1.2                      py_0  
conda                     4.9.1            py38h06a4308_0  
conda-build               3.20.5                   py38_1  
conda-package-handling    1.6.1            py38h7b6447c_0  
conda-verify              3.4.2                      py_1  
cryptography              2.9.2            py38h1ba5d50_0  
cudatoolkit               11.0.221             h6bb024c_0  
cycler                    0.10.0                   py38_0  
dacite                    1.5.1                    pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                    pypi_0    pypi
dlib                      19.21.0                  pypi_0    pypi
expat                     2.2.10               he6710b0_2  
filelock                  3.0.12                     py_0  
flask                     1.1.2                    pypi_0    pypi
flask-socketio            4.3.1                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   py38_1  
fvcore                    0.1.2.post20201209          pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
glib                      2.66.1               h92f7085_0  
glob2                     0.7                        py_0  
google-auth               1.23.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.33.2           py38heead2fc_2    conda-forge
grpcio-tools              1.33.2                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
h5py                      2.10.0                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.9                        py_1  
imageio                   2.9.0                    pypi_0    pypi
imgui                     1.2.0                    pypi_0    pypi
intel-openmp              2020.2                      254  
ipython                   7.18.1           py38h5ca1d4c_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                    pypi_0    pypi
isort                     5.6.4                      py_0  
itsdangerous              1.1.0                    pypi_0    pypi
jedi                      0.17.2                   py38_0  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   h024ee3a_2  
keras                     2.4.3                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.0            py38h2531618_0  
lazy-object-proxy         1.4.3            py38h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.4.2                h62408e4_0  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
liblief                   0.10.1               he6710b0_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.13.0.1             hd408876_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libuv                     1.40.0               h7b6447c_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib-base           3.3.2            py38h817c723_0  
mccabe                    0.6.1                    py38_1  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
multipledispatch          0.6.0                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.2                    pypi_0    pypi
networkx                  2.5                      pypi_0    pypi
ninja                     1.10.2           py38hff7bd54_0  
numpy                     1.18.5                   pypi_0    pypi
numpy-base                1.19.2           py38hfa32c7d_0  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0  
open3d                    0.11.1                   pypi_0    pypi
opencv-contrib-python     4.4.0.46                 pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0  
opt-einsum                3.3.0                    pypi_0    pypi
panda3d                   1.10.7                   pypi_0    pypi
panda3d-viewer            0.4.1                    pypi_0    pypi
pandas                    1.1.4                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.7.0                      py_0  
patchelf                  0.12                 he6710b0_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pillow                    8.0.1            py38he98fc37_0  
pip                       20.0.2                   py38_3  
pkginfo                   1.6.0                    py38_0  
portalocker               2.0.0                    pypi_0    pypi
prompt-toolkit            3.0.8                      py_0  
protobuf                  3.14.0                   pypi_0    pypi
psutil                    5.7.2            py38h7b6447c_0  
ptyprocess                0.6.0              pyhd3eb1b0_2  
py-lief                   0.10.1           py38h403a769_0  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_2  
pygments                  2.7.2              pyhd3eb1b0_0  
pylint                    2.6.0                    py38_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyrr                      0.10.3                   pypi_0    pypi
pyside2                   5.15.2                   pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.3                hcff3b4d_0  
python-dateutil           2.8.1                      py_0  
python-engineio           3.13.2                   pypi_0    pypi
python-libarchive-c       2.9                        py_0  
python-socketio           4.6.0                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.7.0           py3.8_cuda11.0.221_cudnn8.0.3_0    pytorch
pytorch3d                 0.3.0                    pypi_0    pypi
pytz                      2020.1                     py_0  
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1            py38h7b6447c_0  
qimage2ndarray            1.8.3                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0  
redis                     3.5.3                    pypi_0    pypi
requests                  2.23.0                   py38_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
ripgrep                   12.1.1                        0  
rsa                       4.6                      pypi_0    pypi
ruamel_yaml               0.15.87          py38h7b6447c_0  
scikit-image              0.17.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                46.4.0                   py38_0  
shiboken2                 5.15.2                   pypi_0    pypi
simplejson                3.17.2                   pypi_0    pypi
sip                       4.19.13          py38he6710b0_0  
six                       1.14.0           py38h06a4308_0  
soupsieve                 2.0.1                      py_0  
sqlite                    3.31.1               h62c20be_1  
tabulate                  0.8.7                    pypi_0    pypi
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
tensorflow-gpu            2.3.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tifffile                  2020.11.18               pypi_0    pypi
tk                        8.6.8                hbc83047_0  
toml                      0.10.1                     py_0  
torchaudio                0.7.0                      py38    pytorch
torchvision               0.8.1                py38_cu110    pytorch
tornado                   6.0.4            py38h7b6447c_1  
tqdm                      4.46.0                     py_0  
traitlets                 5.0.5                      py_0  
transforms3d              0.3.1                    pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
urllib3                   1.25.8                   py38_0  
wcwidth                   0.2.5                      py_0  
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py38_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
wrapt                     1.11.2           py38h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```

**Comment by bottler** [comment]
Yes. This is a complicated environment. You have PyTorch 1.7.0, which is the latest. But it looks like you have installed the version of PyTorch3D from pypi with `pip install pytorch3d` or something, and that is built with PyTorch 1.6.0. It is safer to install PyTorch3D and its dependencies all through conda which will get these things correct.

You may be able to rescue this environment carefully with something like `pip uninstall fvcore pytorch3d` followed by `conda install -c conda-forge fvcore` and `conda install -c pytorch3d pytorch3d`. The failsafe thing would be to create a new environment as detailed in `INSTALL.md`.

**Comment by nikhilaravi** [comment]
It seems the discussion is no longer about the original issue. Has the original question about cropping been resolved?

**Comment by Zumbalamambo** [comment]
@nikhilaravi no it is not solved

**Comment by nikhilaravi** [comment]
@Zumbalamambo has the installation issue been resolved? What is still unclear the answers to your original question? Please provide more details or close the issue. Thank you!

**Comment by Zumbalamambo** [comment]
The problem still persists but I dont know how to resolve it
