### ISSUE TITLE
Multiview images : RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by btroussel** [facebookresearch/pytorch3d#673]
## 🐛 Bugs / Unexpected behaviors

Hello,

I found a bug which was directly related to the issue #518

## Instructions To Reproduce the Issue:

Unfortunately i cant share data according to my company's rules, but the object file was an obj with its mtl file (no .png):

```
import os
import sys
import json
from tqdm import tqdm
from time import time
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

from skimage.io import imread
import torch
from torchvision.utils import save_image

from pytorch3d.io import load_objs_as_meshes, load_obj
from pytorch3d.structures import Meshes
from pytorch3d.utils import ico_sphere
from pytorch3d.vis.plotly_vis import AxisArgs, plot_batch_individually, plot_scene
from pytorch3d.vis.texture_vis import texturesuv_image_matplotlib
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    HardPhongShader,
    HardGouraudShader,
    TexturesUV,
    TexturesVertex,
    TexturesAtlas,
    PerspectiveCameras,
    BlendParams,
    SoftSilhouetteShader,
    HardFlatShader
)
with open("cam_configuration.json", "r") as file:
    cam_config = json.load(file)


def create_camera(cam_mtx):
    """
    Create the Cameras using camera matrix settings
    
    """
    img_size = [640, 480] # (width, height) of the image
    
    # Camera settings
    fx = cam_mtx[0,0]
    fy = cam_mtx[1,1]
    px = cam_mtx[0,2]
    py = cam_mtx[1,2]
    
    f = torch.tensor((fx, fy), dtype=torch.float32).unsqueeze(0) # dim = (1, 2)
    p = torch.tensor((px, py), dtype=torch.float32).unsqueeze(0) # dim = (1, 2)
    
    cameras = PerspectiveCameras(focal_length=f, principal_point=p, 
                                 image_size=(img_size,), device=device)
    return(cameras)
    
def create_softphong_renderer(device, cameras):
    """
    The Phong shader needs more comoutation but give more accurate results
    Create the phong renderer for a given cam_mtx
        Is differential
    
    """
    # Blending parameters
    # 1e-5 hard blending 
    # 1e-4 soft blending
    blend_params = BlendParams(sigma=1e-5, gamma=1e-5)
        
    raster_settings_soft = RasterizationSettings(
        image_size=[480, 640], 
        blur_radius=np.log(1./1e-5 - 1.)*blend_params.sigma,
        faces_per_pixel=50, 
    )
    
    # Create a soft phong mesh renderer by composing a rasterizer and a shader. 
    renderer = MeshRenderer(
        rasterizer=MeshRasterizer(
            cameras=cameras, 
            raster_settings=raster_settings_soft
        ),
        shader=SoftPhongShader(blend_params=blend_params,
                               device=device,
                               cameras=cameras
                               )
    )
    return(renderer)

def multi_render_object(object_name, renderer, device, l_lights, l_dist, l_elev, l_azim, 
                  do_center=False, do_normalize=False):
    """
    Save the render of an object for multiple viewpoints and lights
        dist : in the 3d model distance metric
        d_elev : delta in degrees
        d_azim : delta in degrees
        l_lights : list of lights
        do_center : isobarycenter
        do_normalize : put the mesh in a sphere of radius 1 preserving proportions
            (speed up optimisations)$
        add_silhouette : add the semantic ground thruth as alpha channel (for hard rendering)
    """
    
    # Load obj file
    obj_path = "./" + object_name + "/model_obj/" + object_name + ".obj"
    object_mesh = load_objs_as_meshes([obj_path],
                                  device=device,
                                  load_textures=True, 
                                  create_texture_atlas=True, 
                                  texture_atlas_size=4,
                                  texture_wrap="repeat")
    
    Path("./" + object_name + "/images").mkdir(exist_ok=True)
                                
    if do_center or do_normalize:
        verts = object_mesh.verts_packed()
        N = verts.shape[0]
        center = verts.mean(0)
        if do_center:
            object_mesh.offset_verts_(-center.expand(N, 3))
        if do_normalize : 
            scale = max((verts - center).abs().max(0)[0])
            object_mesh.scale_verts_((1.0 / float(scale)))
            
    
    
    # Equivalent of nested for loops but with tqdm (not slower)
    params_list = [[dist, elev, azim, lights, lights_index] 
                                             for lights_index, lights in enumerate(l_lights)
                                             for dist in l_dist
                                             for elev in l_elev 
                                             for azim in l_azim]
    for dist, elev, azim, lights, lights_index in tqdm(params_list):  
        
        # Camera position
        R, T = look_at_view_transform(dist, elev, azim, device=device) 
                        
        image = renderer(meshes_world=object_mesh, R=R.to(device), T=T.to(device),
                                          lights=lights)
        
        save_image(image.permute(0,3,1,2).squeeze(), "{}/images/Dist{}_Elev{}_Azim{}_Li{}.png".format(
            object_name, dist, elev, azim, lights_index))
        
if __name__ == '__main__':
    # Normalisation and center is highly recommended 
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
   
    object_name = "object"
    
    cameras = create_camera(cam_mtx=np.array(cam_config['webc_mtx']))
   
    renderer = create_softphong_renderer(device, cameras=cameras)

    print("Création des rendus")
    # Creation du dataset
        
    # TODO : Régler problème avec la librairie pytorch3d lorsque l'on a elev = +/- 90
    # "CUDA error: device-side assert triggered" -> def sample_textures() -> clamp(min=0, ...)
        
    l_dist = [2.5]
    l_elev = np.arange(-90,91,10)
    l_elev[0] = -89.9
    l_elev[-1] = 89.9
    l_azim = np.arange(0, 360, 10)
    l_lights = [PointLights(device=device, location=[[0.0, 0.0, 3.0]]), PointLights(device=device, location=[[0.0, 3.0, 3.0]])]
        
    multi_render_object(object_name=object_name, renderer=renderer, device=device, l_lights=l_lights,
                            l_dist=l_dist, l_elev=l_elev, l_azim=l_azim, do_center=True, do_normalize=True)
```
After using this function which aim was to create a synthetic dataset for an object with a render from different point of view, an error with the SoftPhongRender occured. 

## Here are the logs :
```
  1%|          | 15/1368 [00:01<02:29,  9.07it/s]
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [10598,0,0], thread: [21,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [10598,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [10598,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
  1%|          | 15/1368 [00:02<03:01,  7.45it/s]
Traceback (most recent call last):

  File "D:\Ancrage\poseglassnet\data\image_render.py", line 340, in <module>
    multi_render_object(object_name=object_name, renderer=renderer, device=device, l_lights=l_lights,

  File "D:\Ancrage\poseglassnet\data\image_render.py", line 297, in multi_render_object
    image = renderer(meshes_world=object_mesh, R=R.to(device), T=T.to(device),

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\mesh\renderer.py", line 56, in forward
    images = self.shader(fragments, meshes_world, **kwargs)

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\mesh\shader.py", line 126, in forward
    colors = phong_shading(

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\mesh\shading.py", line 80, in phong_shading
    ambient, diffuse, specular = _apply_lighting(

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\mesh\shading.py", line 32, in _apply_lighting
    camera_position=cameras.get_camera_center(),

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\cameras.py", line 144, in get_camera_center
    w2v_trans = self.get_world_to_view_transform(**kwargs)

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\cameras.py", line 171, in get_world_to_view_transform
    world_to_view_transform = get_world_to_view_transform(R=self.R, T=self.T)

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\cameras.py", line 1250, in get_world_to_view_transform
    R = Rotate(R, device=R.device)

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\transforms\transform3d.py", line 530, in __init__
    _check_valid_rotation_matrix(R, tol=orthogonal_tol)

  File "C:\Users\3DLAB\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\transforms\transform3d.py", line 721, in _check_valid_rotation_matrix
    orthogonal = torch.allclose(R.bmm(R.transpose(1, 2)), eye, atol=tol)

RuntimeError: CUDA error: device-side assert triggered
```
In my search of the bug, i found that :
```
w_xy.unique()
tensor([-9223372036854775808,                    0,                    1,
                           2,                    3], device='cuda:0')
```
An error made the number -9223372036854775808 (in base 2 is equal to −1000000000000000000000000000000000000000000000000000000000000000) appears in w_xy.

## My way to solve the problem
Change the function "def sample_textures(self, fragments, **kwargs) -> torch.Tensor:" of the mesh/textures.py file :
```
w_xy = (bary_w01 * R).to(torch.int64).clamp(max=R - 1)  # (N, H, W, K, 2)
to : 
w_xy = (bary_w01 * R).to(torch.int64).clamp(min=0, max=R - 1)  # (N, H, W, K, 2)
```
I can't tell you if this is the right solution of the problem, but it made the CUDA error to stop while doing the rest of the job.

**Comment by nikhilaravi** [comment]
@btroussel I see that you're using the `TextureAtlas` type for the obj texture - do the material properties in the obj vary for different parts of the object? Otherwise this texture class will be unnecessary and you could just use a simpler option like `TexturesVertex`. 

Also based on the comments in your code is the issue only present when the elevation angle is exactly +/- 90?

**Comment by btroussel** [comment]
Material properties in my obj are indeed varying for different parts of the object. 
The issue relative to the elevation angle equal to +/- 90° is another issue, the bug was still present with this change.

**Comment by nikhilaravi** [comment]
@btroussel are you trying to learn the texture/object shape or just render it? If you are only interested in rendering then clamping is fine as a solution but this will affect gradients if you are trying to backpropagate through the rendering pipeline.
