### ISSUE TITLE
RuntimeError in diffuse(normals, color, direction) when rendering with custom diffuse color.

### ISSUE THREAD

**Issue by Algomorph** [facebookresearch/pytorch3d#681]
## 🐛 Bugs / Unexpected behaviors

When setting the light diffuse properties in accordance with the default values, rendering results in a runtime error.

## Instructions To Reproduce the Issue:

Run the following python code (e.g. name it torus_example_1.py or the like):

```Python
import sys
import typing

import cv2
import numpy as np
import pytorch3d.utils
from pytorch3d.renderer import MeshRenderer, SoftPhongShader, PointLights
from pytorch3d.renderer.cameras import PerspectiveCameras
from pytorch3d.renderer.mesh import MeshRasterizer, RasterizationSettings
import torch

PROGRAM_EXIT_SUCCESS = 0


def make_ndc_intrinsic_matrix(image_size: typing.Tuple[int, int], intrinsic_matrix: np.ndarray) -> torch.Tensor:
    """
    Makes an intrinsic matrix in NDC (normalized device coordinates) coordinate system
    :param image_size: size of the output image, (height, width)
    :param intrinsic_matrix: 3x3 or 4x4 projection matrix of the camera
    :return:
    """

    image_height, image_width = image_size
    half_image_width = image_width // 2
    half_image_height = image_height // 2

    fx_screen = intrinsic_matrix[0, 0]
    fy_screen = intrinsic_matrix[1, 1]
    px_screen = intrinsic_matrix[0, 2]
    py_screen = intrinsic_matrix[1, 2]

    fx = fx_screen / half_image_height
    fy = fy_screen / half_image_height
    px = -(px_screen - half_image_width) / half_image_height
    py = -(py_screen - half_image_height) / half_image_height

    ndc_intrinsic_matrix = torch.tensor([[[fx, 0.0, px, 0.0],
                                          [0.0, fy, py, 0.0],
                                          [0.0, 0.0, 0.0, -1.0],
                                          [0.0, 0.0, -1.0, 0.0]]], dtype=torch.float32)
    return ndc_intrinsic_matrix


def main() -> int:
    image_size = (480, 640)
    # imitates a Kinect v1 or ASUS Xtion Pro camera
    intrinsic_matrix = np.array([[575.548, 0., 323.172, 0.],
                                 [0., 577.46, 236.417, 0.],
                                 [0., 0., 1., 0.],
                                 [0., 0., 0., 1.]])
    ndc_intrinsic_matrix = make_ndc_intrinsic_matrix(image_size, intrinsic_matrix)

    torch_device = torch.device("cuda:0")
    meshes_torch3d: pytorch3d = pytorch3d.utils.torus(0.5, 1.0, 16, 64, device=torch_device)
    meshes_torch3d.textures = pytorch3d.renderer.mesh.TexturesVertex(
        torch.ones_like(meshes_torch3d.verts_list()[0]).unsqueeze(0))

    camera_rotation = torch.eye(3, dtype=torch.float32, device=torch_device).unsqueeze(0)  # (1, 3, 3)
    camera_translation: torch.Tensor = torch.Tensor(np.array([[0.0, 0.0, 3.0]])).to(torch_device)  # (1, 3)

    cameras = PerspectiveCameras(device=torch_device,
                                 R=camera_rotation,
                                 T=camera_translation,
                                 K=ndc_intrinsic_matrix)

    rasterization_settings = RasterizationSettings(image_size=image_size, cull_backfaces=True, cull_to_frustum=True,
                                                   z_clip_value=0.5, faces_per_pixel=1)
    rasterizer = MeshRasterizer(cameras, raster_settings=rasterization_settings)

    lights = PointLights(ambient_color=((1.0, 1.0, 1.0)), diffuse_color=((0.0, 0.0, 0.0)),
                         specular_color=((0.0, 0.0, 0.0)), device=torch_device, location=[[0.0, 0.0, -3.0]])  # fails
    # lights = PointLights(device=torch_device, location=[[0.0, 0.0, -3.0]]) # succeeds

    renderer = MeshRenderer(
        rasterizer=rasterizer,
        shader=SoftPhongShader(
            device=torch_device,
            cameras=cameras,
            lights=lights
        )
    )

    images = renderer(meshes_torch3d)

    # visualization. Comment out if you don't have opencv-python installed (e.g. from PiPI) in your python environment.
    rendered_mesh = images[0, ..., :3].cpu().numpy()
    rendered_mesh_uint8 = (rendered_mesh * 255).astype(np.uint8)
    cv2.imshow("rendered_mesh", rendered_mesh_uint8)
    cv2.waitKey()
    cv2.imwrite("torus_out.png", rendered_mesh_uint8)

    return PROGRAM_EXIT_SUCCESS


if __name__ == '__main__':
    sys.exit(main())

```

You get the error output:
```
Traceback (most recent call last):
  File "/home/algomorph/Workbench/Exercises/PyTorch3DBugScripts/torus_example_1.py", line 96, in <module>
    sys.exit(main())
  File "/home/algomorph/Workbench/Exercises/PyTorch3DBugScripts/torus_example_1.py", line 83, in main
    images = renderer(meshes_torch3d)
  File "/home/algomorph/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/algomorph/.local/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 56, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/algomorph/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/algomorph/.local/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 126, in forward
    colors = phong_shading(
  File "/home/algomorph/.local/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 80, in phong_shading
    ambient, diffuse, specular = _apply_lighting(
  File "/home/algomorph/.local/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 28, in _apply_lighting
    light_diffuse = lights.diffuse(normals=normals, points=points)
  File "/home/algomorph/.local/lib/python3.8/site-packages/pytorch3d/renderer/lighting.py", line 265, in diffuse
    return diffuse(normals=normals, color=self.diffuse_color, direction=direction)
  File "/home/algomorph/.local/lib/python3.8/site-packages/pytorch3d/renderer/lighting.py", line 59, in diffuse
    direction = direction.view(expand_dims)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
The code fails regardless of what values are used for the diffuse, ambient, specular colors, as long as any values are used.

The code succeeds if you uncomment line 72 and comment out 70-71 (see comments in code), resulting in a nicely-rendered torus:
![torus_out](https://user-images.githubusercontent.com/1050606/118725523-0cd82480-b7fe-11eb-99f2-dc554bb318fc.png)

## Version info:
PyTorch3d version: 0.4.0
PyTorch version: 1.8.1

May or may not be related to this bug (not sure): #652

**Comment by Algomorph** [comment]
Never mind, I needed to put the commas in after the inside tuples:
```Python
    lights = PointLights(ambient_color=((0.5, 0.5, 0.5),), diffuse_color=((0.0, 0.0, 0.0),),
                         specular_color=((0.0, 0.0, 0.0),), device=torch_device, location=[[0.0, 0.0, -3.0]])  # fails
```
