### ISSUE TITLE
from pytorch3d import _C ImportError /anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

### ISSUE THREAD

**Issue by bernakabadayi** [facebookresearch/pytorch3d#791]
## Instructions To Reproduce the Issue:

1. Code I run to test installation of Pytorch3d
```
import pytorch3d
from pytorch3d.utils import ico_sphere

```
2. Exact command I run

```
 python pytorch3d_test.py
```

3. Error

```
Traceback (most recent call last):
  File "pytorch3d_test.py", line 2, in <module>
    from pytorch3d.utils import ico_sphere
  File "/home/bkabadayi/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/utils/__init__.py", line 3, in <module>
    from .ico_sphere import ico_sphere
  File "/home/bkabadayi/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/utils/ico_sphere.py", line 5, in <module>
    from pytorch3d.ops.subdivide_meshes import SubdivideMeshes
  File "/home/bkabadayi/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/bkabadayi/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: /home/bkabadayi/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
```
I followed https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md to install the Pytorch3d

4. Conda list output

```
# packages in environment at /home/bkabadayi/anaconda3/envs/pytorch3d:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
argon2-cffi               20.1.0           py38h27cfd23_1
async_generator           1.10               pyhd3eb1b0_0
attrs                     21.2.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bleach                    4.0.0              pyhd3eb1b0_0
ca-certificates           2021.7.5             h06a4308_1
certifi                   2021.5.30        py38h06a4308_0
cffi                      1.14.6           py38h400218f_0
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cudatoolkit               10.2.89              hfd86e86_1
cycler                    0.10.0                   pypi_0    pypi
dbus                      1.13.18              hb2f20db_0
decorator                 5.0.9              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.3                      py38_0
expat                     2.4.1                h2531618_2
fontconfig                2.13.1               h6c09931_0
freetype                  2.10.4               h5ab3b9f_0
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20210804            py38    fvcore
glib                      2.69.0               h5202010_0
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
icu                       58.2                 he6710b0_3
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.10.0           py38h06a4308_0
importlib_metadata        3.10.0               hd3eb1b0_0
intel-openmp              2021.3.0          h06a4308_3350
iopath                    0.1.9                      py38    iopath
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.22.0           py38hb070fc8_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_1
jedi                      0.17.0                   py38_0
jinja2                    3.0.1              pyhd3eb1b0_0
jpeg                      9b                   h024ee3a_2
jsonschema                3.2.0                      py_2
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.7.1            py38h06a4308_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.18               h7b6447c_0
libstdcxx-ng              9.3.0               hd4cf53a_17
libtiff                   4.2.0                h85742a9_0
libuuid                   1.0.3                h1bed415_2
libuv                     1.40.0               h7b6447c_0
libwebp-base              1.2.0                h27cfd23_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.12               h03d6c58_0
lz4-c                     1.9.3                h2531618_0
markupsafe                2.0.1            py38h27cfd23_0
matplotlib                3.4.2                    pypi_0    pypi
mistune                   0.8.4           py38h7b6447c_1000
mkl                       2021.3.0           h06a4308_520
mkl-service               2.4.0            py38h7f8727e_0
mkl_fft                   1.3.0            py38h42c9631_2
mkl_random                1.2.2            py38h51133e4_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py38h06a4308_0
nbformat                  5.1.3              pyhd3eb1b0_0
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.5.1              pyhd3eb1b0_0
networkx                  2.6.2                    pypi_0    pypi
ninja                     1.10.2               hff7bd54_1
notebook                  6.4.0            py38h06a4308_0
numpy                     1.20.3           py38hf144106_0
numpy-base                1.20.3           py38h74d4b33_0
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46                       py_0
opencv-python             4.5.3.56                 pypi_0    pypi
openjpeg                  2.3.0                h05c96fa_1
openssl                   1.1.1k               h27cfd23_0
packaging                 21.0               pyhd3eb1b0_0
pandocfilters             1.4.3            py38h06a4308_1
parso                     0.8.2              pyhd3eb1b0_0
pcre                      8.45                 h295c915_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.3.1            py38h2c7a002_0
pip                       21.2.2           py38h06a4308_0
plotly                    5.1.0                    pypi_0    pypi
portalocker               1.7.0            py38h578d9bd_1    conda-forge
prometheus_client         0.11.0             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyh06a4308_0
prompt_toolkit            3.0.17               hd3eb1b0_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pycparser                 2.20                       py_2
pygments                  2.9.0              pyhd3eb1b0_0
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py38h05f1152_4
pyrsistent                0.17.3           py38h7b6447c_0
python                    3.8.11          h12debd9_0_cpython
python-dateutil           2.8.2              pyhd3eb1b0_0
python_abi                3.8                      2_cp38    conda-forge
pytorch3d                 0.4.0           py38_cu102_pyt171    pytorch3d
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
pyzmq                     20.0.0           py38h2531618_1
qt                        5.9.7                h5867ecd_1
qtconsole                 5.1.0              pyhd3eb1b0_0
qtpy                      1.9.0                      py_0
readline                  8.1                  h27cfd23_0
scikit-image              0.18.2                   pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py38h06a4308_0
sip                       4.19.13          py38he6710b0_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hc218d9a_0
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tenacity                  8.0.1                    pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.9.4            py38h06a4308_0
testpath                  0.5.0              pyhd3eb1b0_0
tifffile                  2021.7.30                pypi_0    pypi
tk                        8.6.10               hbc83047_0
torch                     1.5.0                    pypi_0    pypi
torchvision               0.8.2                py38_cu102    pytorch
tornado                   6.1              py38h27cfd23_0
tqdm                      4.62.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5              pyhd3eb1b0_0
typing_extensions         3.10.0.0           pyh06a4308_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py38_0
xz                        5.2.5                h7b6447c_0
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.4                h2531618_0
zipp                      3.5.0              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.9                haebb681_0
```

5. pip list output
```
Package             Version
------------------- -------------------
argon2-cffi         20.1.0
async-generator     1.10
attrs               21.2.0
backcall            0.2.0
bleach              4.0.0
certifi             2021.5.30
cffi                1.14.6
colorama            0.4.4
cycler              0.10.0
decorator           5.0.9
defusedxml          0.7.1
entrypoints         0.3
future              0.18.2
fvcore              0.1.5.post20210804
imageio             2.9.0
importlib-metadata  3.10.0
iopath              0.1.9
ipykernel           5.3.4
ipython             7.22.0
ipython-genutils    0.2.0
ipywidgets          7.6.3
jedi                0.17.0
Jinja2              3.0.1
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.12
jupyter-console     6.4.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
kiwisolver          1.3.1
MarkupSafe          2.0.1
matplotlib          3.4.2
mistune             0.8.4
mkl-fft             1.3.0
mkl-random          1.2.2
mkl-service         2.4.0
nbclient            0.5.3
nbconvert           6.1.0
nbformat            5.1.3
nest-asyncio        1.5.1
networkx            2.6.2
notebook            6.4.0
numpy               1.20.3
olefile             0.46
opencv-python       4.5.3.56
packaging           21.0
pandocfilters       1.4.3
parso               0.8.2
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.3.1
pip                 21.2.2
plotly              5.1.0
portalocker         1.7.0
prometheus-client   0.11.0
prompt-toolkit      3.0.17
ptyprocess          0.7.0
pycparser           2.20
Pygments            2.9.0
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.2
pytorch3d           0.4.0
PyWavelets          1.1.1
PyYAML              5.4.1
pyzmq               20.0.0
qtconsole           5.1.0
QtPy                1.9.0
scikit-image        0.18.2
scipy               1.7.1
Send2Trash          1.5.0
setuptools          52.0.0.post20210125
sip                 4.19.13
six                 1.16.0
tabulate            0.8.9
tenacity            8.0.1
termcolor           1.1.0
terminado           0.9.4
testpath            0.5.0
tifffile            2021.7.30
torch               1.5.0
torchvision         0.8.2
tornado             6.1
tqdm                4.62.0
traitlets           5.0.5
typing-extensions   3.10.0.0
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.36.2
widgetsnbextension  3.5.1
yacs                0.1.6
zipp                3.5.0
```

Thanks,

**Comment by bottler** [comment]
This kind of problem come from mismatched versions of dependent libraries. For example, you have a build of PyTorch3D for PyTorch 1.7.1, but your PyTorch version is 1.5.0. And PyTorch is installed from pypi but PyTorch3D is from conda (which might mean PyTorch has been uninstalled since PyTorch3D was installed.

I suggest you start from a new environment, deciding what versions of everything you want and installing everything with conda, according to the PyTorch3D instructions.

**Comment by bernakabadayi** [comment]
Installing on a new env with the provided instructions solved the issue! Thanks
