### ISSUE TITLE
Unable to build from source | torch 1.7.1; CUDA 11.0

### ISSUE THREAD

**Issue by SavvaI** [facebookresearch/pytorch3d#801]
My environment consists of:
*Python 3.8.11
*CUDA 11.0
*torch==1.7.1

I try to build pytorch3d from scratch as it is discribed in the tutorial in the clean environment. I install nvidiacub, etc, but when I start building I keep repeatingly failing on the last (presumably) stage. The full log is too huge to include, so I paste only the final part

 ^
    [54/54] /usr/local/cuda/bin/nvcc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/tmp/pip-req-build-rizoq3iv/pytorch3d/csrc -I/home/cub-1.10.0 -I/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/anaconda3/envs/pytorch3d/include/python3.8 -c -c /tmp/pip-req-build-rizoq3iv/pytorch3d/csrc/knn/knn.cu -o /tmp/pip-req-build-rizoq3iv/build/temp.linux-x86_64-3.8/tmp/pip-req-build-rizoq3iv/pytorch3d/csrc/knn/knn.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++14 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
        subprocess.run(
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-rizoq3iv/setup.py", line 132, in <module>
        setup(
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
        build_ext.build_extensions(self)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/envs/pytorch3d/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rizoq3iv/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rizoq3iv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m2xvz8nq/install-record.txt --single-version-externally-managed --compile --install-headers /root/anaconda3/envs/pytorch3d/include/python3.8/pytorch3d Check the logs for full command output.

**Comment by bottler** [comment]
There isn't any detail here about what the root cause error is. Two possibilities

(1) There is actually a compilation error. You can look if there is a log file from the build, and search it for the word "error". If you retry setting the environment variable `PYTORCH3D_NO_NINJA` to `1` the build will be slower and less distributed, and the error might appear in the output, which might make it easier to find.

(2) The build is running in parallel and running out of memory. Then the PYTORCH3D_NO_NINJA setting above could just fix it. Or, if you have many cores, you could set the environment variable `MAX_JOBS` to a small number.

**Comment by SavvaI** [comment]
> There isn't any detail here about what the root cause error is. Two possibilities
> 
> (1) There is actually a compilation error. You can look if there is a log file from the build, and search it for the word "error". If you retry setting the environment variable `PYTORCH3D_NO_NINJA` to `1` the build will be slower and less distributed, and the error might appear in the output, which might make it easier to find.
> 
> (2) The build is running in parallel and running out of memory. Then the PYTORCH3D_NO_NINJA setting above could just fix it. Or, if you have many cores, you could set the environment variable `MAX_JOBS` to a small number.

Thank you for the reply! I tried setting PYTORCH3D_NO_NINJA and MAX_JOBS, though unfortunately it did not help. Could you please specify what do you mean by the log file and where should I look for it, as I understand that the output is already log

**Comment by bottler** [comment]
Setting PYTORCH3D_NO_NINJA should have changed the output from the build quite a lot. Can you share the new output?

(If it hasn't changed, it likely isn't set properly.)

**Comment by SavvaI** [comment]
You are right, I have set that env variables properly and now it installs :), it seems that the problem was with the memory. Thanks a lot!
