### ISSUE TITLE
RuntimeError when calling renderer_textured

### ISSUE THREAD

**Issue by simovolo** [facebookresearch/pytorch3d#895]
When running the PyTorch3D tutorial "fit a mesh via rendering" in Ubuntu, the code crashes when calling render_textured. This the error message:

Traceback (most recent call last):
  File "fit_textured_mesh.py", line 538, in <module>
    images_predicted = renderer_textured(new_src_mesh, cameras=target_cameras[j], lights=lights)
  File "/home/simone/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/simone/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 60, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/simone/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/simone/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 149, in forward
    colors = phong_shading(
  File "/home/simone/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 90, in phong_shading
    ambient, diffuse, specular = _apply_lighting(
  File "/home/simone/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 36, in _apply_lighting
    camera_position=cameras.get_camera_center(),
  File "/home/simone/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/cameras.py", line 155, in get_camera_center
    P = w2v_trans.inverse().get_matrix()
  File "/home/simone/anaconda3/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 277, in inverse
    i_matrix = self._get_matrix_inverse()
  File "/home/simone/anaconda3/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 247, in _get_matrix_inverse
    return torch.inverse(self._matrix)
RuntimeError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`

**Comment by nikhilaravi** [comment]
Closing this issue as it has been answered by @bottler!
