### ISSUE TITLE
a problem   happen when i training 

### ISSUE THREAD

**Issue by zhangzhenyu-123** [facebookresearch/pytorch3d#929]
After I get the grid and camera parameters, I use pytorch3d to turn them into two-dimensional projection pictures and build pixel level loss functions. However, during training (not at the beginning of training, but during training), I often report the following errors. I confirm that my data are in GPU. I want to know why？

Epoch 0:  13%|█▎        | 237/1771 [03:12<20:30,  1.25it/s][A

Epoch 0:  13%|█▎        | 238/1771 [03:13<20:06,  1.27it/s][ACUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/interface_cuda/interface.cpp:944
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/interface_cuda/interface.cpp:945
CUDA runtime error: an illegal memory access was encountered (700) in magma_queue_destroy_internal at /opt/conda/conda-bld/magma-cuda110_1598416697386/work/interface_cuda/interface.cpp:946

Epoch 0:  13%|█▎        | 238/1771 [03:14<20:51,  1.22it/s]

  0%|          | 0/20 [03:14<?, ?it/s]
Traceback (most recent call last):
  File "/share/home/wanghui/workspacce/zzy/spin_render/train.py", line 14, in <module>
    trainer.train()
  File "/share/home/wanghui/workspacce/zzy/spin_render/utils/base_trainer.py", line 65, in train
    out = self.train_step(batch)
  File "/share/home/wanghui/workspacce/zzy/spin_render/train/trainer.py", line 300, in train_step
    loss_render_plus = self.render_loss_plus(pred_vertices=pred_vertices,gt_vertices=opt_vertices,
  File "/share/home/wanghui/workspacce/zzy/spin_render/train/trainer.py", line 118, in render_loss_plus
    render1=render3d_plus(gt_vertices,gt_t)
  File "/share/home/wanghui/workspacce/zzy/spin_render/test11.py", line 94, in render3d_plus
    return render(objce)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 56, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 126, in forward
    colors = phong_shading(
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 80, in phong_shading
    ambient, diffuse, specular = _apply_lighting(
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 32, in _apply_lighting
    camera_position=cameras.get_camera_center(),
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/cameras.py", line 144, in get_camera_center
    w2v_trans = self.get_world_to_view_transform(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/cameras.py", line 171, in get_world_to_view_transform
    world_to_view_transform = get_world_to_view_transform(R=self.R, T=self.T)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/cameras.py", line 1250, in get_world_to_view_transform
    R = Rotate(R, device=R.device)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 530, in __init__
    _check_valid_rotation_matrix(R, tol=orthogonal_tol)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 722, in _check_valid_rotation_matrix
    det_R = torch.det(R)
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by bottler** [comment]
It was a known problem that in certain cases (hardware, drivers etc) the call to `torch.det` in `_check_valid_rotation_matrix` could be problematic. The latest version 0.6.0 (and 0.5.0 too) avoids it by calling a custom 3x3 determinant function. If you update, you should be ok.

**Comment by nikhilaravi** [comment]
@zhangzhenyu-123 please try updating the version as @bottler suggested. If you still experience issues feel free to reopen this issue.
