### ISSUE TITLE
Emitting ninja build file when building 'pytorch3d._C' extension

### ISSUE THREAD

**Issue by YiLin32Wang** [facebookresearch/pytorch3d#931]
## 🐛 Bugs / Unexpected behaviors
 I'm using Pytorch1.6.0 and CUDA10.2 on Linux, and have successfully installed all the prerequisites. I'm trying to use the local clone method to install but fail because of the following error:
```
Obtaining file:///home/yilin/Hand_est/%5B5%5DS2Hand/pytorch3d
Requirement already satisfied: fvcore in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from pytorch3d==0.6.0) (0.1.5.post20210915)
Requirement already satisfied: iopath in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from pytorch3d==0.6.0) (0.1.9)
Requirement already satisfied: numpy in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (1.19.5)
Requirement already satisfied: yacs>=0.1.6 in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (0.1.8)
Requirement already satisfied: pyyaml>=5.1 in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (5.4.1)
Requirement already satisfied: tqdm in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (4.62.3)
Requirement already satisfied: termcolor>=1.1 in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (1.1.0)
Requirement already satisfied: Pillow in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (8.3.2)
Requirement already satisfied: tabulate in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (0.8.9)
Requirement already satisfied: dataclasses in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (0.8)
Requirement already satisfied: portalocker in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from iopath->pytorch3d==0.6.0) (2.3.2)
Installing collected packages: pytorch3d
  Running setup.py develop for pytorch3d
    ERROR: Command errored out with exit status 1:
     command: /home/yilin/anaconda3/envs/Pytorch_py6/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/yilin/Hand_est/[5]S2Hand/pytorch3d/setup.py'"'"'; __file__='"'"'/home/yilin/Hand_est/[5]S2Hand/pytorch3d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/yilin/Hand_est/[5]S2Hand/pytorch3d/
    Complete output (57 lines):
    running develop
    running egg_info
    writing pytorch3d.egg-info/PKG-INFO
    writing dependency_links to pytorch3d.egg-info/dependency_links.txt
    writing requirements to pytorch3d.egg-info/requires.txt
    writing top-level names to pytorch3d.egg-info/top_level.txt
    reading manifest file 'pytorch3d.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'pytorch3d.egg-info/SOURCES.txt'
    running build_ext
    building 'pytorch3d._C' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/yilin/Hand_est/[5]S2Hand/pytorch3d/setup.py", line 150, in <module>
        "": ["*.json"],
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
        build_ext.build_extensions(self)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1225, in _write_ninja_file_and_compile_objects
        with_cuda=with_cuda)
      File "/home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1686, in _write_ninja_file
        assert len(sources) > 0
    AssertionError
    Emitting ninja build file /home/yilin/Hand_est/[5]S2Hand/pytorch3d/build/temp.linux-x86_64-3.6/build.ninja...

```
I have no idea about what is going on here and why this ninja build file emits. I haven't changed anything in the original codes. Could you help me with my issues? Thanks!

**Comment by bottler** [comment]
Something might be confused the characters `[` and `]` in a path like `[5]S2Hand`. Those characters are special to some shells. Can you move the code to a place without them?

Another option is to set the environment variable `PYTORCH3D_NO_NINJA` to `1` and try again.

**Comment by YiLin32Wang** [comment]
Thank you very much! I've changed the path and it works! 
But after successfully installing, I failed to run the get-started codes of chamfer loss as given in the tutorial getting segmantation fault.
```
~/Hand_est/S2Hand/pytorch3d/my_tests$ python test.py
Segmentation fault (core dumped)
```
Then if run with python3, getting aborted
```
~/Hand_est/S2Hand/pytorch3d/my_tests$ python3 test.py
free(): invalid size
Aborted (core dumped)
```

The codes I run is just what given on the get-started page:

```
from pytorch3d.utils import ico_sphere
from pytorch3d.io import load_obj
from pytorch3d.structures import Meshes
from pytorch3d.ops import sample_points_from_meshes
from pytorch3d.loss import chamfer_distance

# Use an ico_sphere mesh and load a mesh from an .obj e.g. model.obj
sphere_mesh = ico_sphere(level=3)
verts, faces, _ = load_obj("model.obj")
test_mesh = Meshes(verts=[verts], faces=[faces.verts_idx])

# Differentiably sample 5k points from the surface of each mesh and then compute the loss.
sample_sphere = sample_points_from_meshes(sphere_mesh, 5000)
sample_test = sample_points_from_meshes(test_mesh, 5000)
loss_chamfer, _ = chamfer_distance(sample_sphere, sample_test)
```

**Comment by bottler** [comment]
Are you in the same conda environment where you installed? Can you print out `conda list` of that environment? And `conda info`. Does `python -c "import torch"` work? Does `python3 -c "import torch"` work?

**Comment by YiLin32Wang** [comment]
Thanks for quick reply! Yes, I'm in the same conda environment. And both `python-c "import torch" ` and ` python3 -c "import torch"`  can work.The conda list shown here:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
absl-py                   0.15.0                   pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backports                 1.0                        py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
black                     21.10b0                  pypi_0    pypi
bleach                    4.1.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2021.10.8            ha878542_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.14.6           py36hd8eec40_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
charset-normalizer        2.0.7                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cudatoolkit               9.0                  h13b8566_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cupy-cuda102              9.5.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
dataclasses               0.8                pyh787bdff_2    conda-forge
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fastrlock                 0.8                      pypi_0    pypi
flake8                    4.0.1                    pypi_0    pypi
flake8-bugbear            21.9.2                   pypi_0    pypi
flake8-comprehensions     3.7.0                    pypi_0    pypi
fontconfig                2.13.1            hba837de_1005    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
freetype                  2.10.4               h0708190_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20210915            py36    fvcore
google-auth               2.3.3                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.41.1                   pypi_0    pypi
icu                       68.2                 h9c3ff4c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
idna                      3.3                      pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        4.2.0                    pypi_0    pypi
intel-openmp              2021.3.0          h06a4308_3350    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
iopath                    0.1.9                      py36    iopath
ipykernel                 5.5.5            py36hcb3619a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipython                   5.8.0                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipython_genutils          0.2.0                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
isort                     4.3.21                   pypi_0    pypi
jbig                      2.1               h7f98852_2003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jpeg                      9d                   h36c2ea0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jsonschema                2.6.0                 py36_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter                   1.0.0            py36h5fab9bb_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_client            5.3.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_console           5.2.0                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_core              4.5.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.12                 hddcbb42_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lerc                      2.2.1                h9c3ff4c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libblas                   3.9.0           11_linux64_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcblas                  3.9.0           11_linux64_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libdeflate                1.7                  h7f98852_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h9c3ff4c_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 11.2.0               h1d223b6_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran-ng            11.2.0               h69a702a_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran5              11.2.0               h5c6108e_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp                   11.2.0               h1d223b6_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.16                 h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
liblapack                 3.9.0           11_linux64_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.37               h21135ba_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsodium                 1.0.18               h36c2ea0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              11.2.0               he4da1e4_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.3.0                hf544144_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.32.1            h7f98852_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.2.1                h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.9.12               h72842e0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py36h8f6f2f9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
matplotlib                3.3.4                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py36h8f6f2f9_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl                       2021.3.0           h06a4308_520    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mypy-extensions           0.4.3                    pypi_0    pypi
nbconvert                 5.6.1              pyhd8ed1ab_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ncurses                   6.2                  h58526e2_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
networkx                  2.5.1                    pypi_0    pypi
neural-renderer-pytorch   1.1.3                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
notebook                  5.7.11           py36h5fab9bb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numpy                     1.19.5           py36hfc0c790_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nvidiacub                 1.10.0                        0    bottler
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
opencv-python             4.5.3.56                 pypi_0    pypi
opendr                    0.78                     pypi_0    pypi
openjpeg                  2.4.0                hb52868f_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openssl                   1.1.1l               h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
packaging                 21.0               pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pathspec                  0.9.0                    pypi_0    pypi
pexpect                   4.8.0              pyh9f0ad1d_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pickleshare               0.7.5                   py_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pillow                    8.3.2            py36h676a545_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pip                       21.2.4             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
platformdirs              2.4.0                    pypi_0    pypi
plotly                    5.3.1                    pypi_0    pypi
portalocker               2.3.2            py36h5fab9bb_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prompt_toolkit            1.0.15                     py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
protobuf                  3.18.0                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.10.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyparsing                 2.4.7                    pypi_0    pypi
pyqt                      4.11.4                   py36_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python                    3.6.13          hb7a2778_2_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python_abi                3.6                     2_cp36m    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch3d                 0.6.0                     dev_0    <develop>
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.3.0           py36h7068817_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
qt                        4.8.7                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtconsole                 5.2.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
qtpy                      1.11.2             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
readline                  8.1                  h46c0cb4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
regex                     2021.11.10               pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
setuptools                58.0.4           py36h5fab9bb_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
simplegeneric             0.8.1                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sip                       4.18                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
six                       1.16.0             pyh6c4a22f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sqlite                    3.36.0               h9cd32fc_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tenacity                  8.0.1                    pypi_0    pypi
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorboardx              2.4                      pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.12.1           py36h5fab9bb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tifffile                  2020.9.3                 pypi_0    pypi
tk                        8.6.11               h27826a3_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tomli                     1.2.2                    pypi_0    pypi
torch                     1.6.0                    pypi_0    pypi
torchvision               0.7.0                    pypi_0    pypi
tornado                   6.1              py36h8f6f2f9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 4.3.3              pyhd8ed1ab_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
transforms3d              0.3.1                    pypi_0    pypi
typed-ast                 1.4.3                    pypi_0    pypi
typing-extensions         3.10.0.2                 pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
webencodings              0.5.1                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
widgetsnbextension        3.5.1              pyh9f0ad1d_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.5                h516909a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11            h516909a_1010    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zstd                      1.5.0                ha95c52a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
```

**Comment by bottler** [comment]
CUDA 9.0 is too old. But your code doesn't use CUDA, so should work. The pytorch3d compiled extension _C may not be built properly? You could confirm by starting `python` and running the code line-by-line? It will crash inside a call to _C inside sample_points_from_meshes, or on importing _C.

If that's right, I don't know what the cause would have been. Maybe the python headers used in building were wrong/modified/from a different version of python? You could try doing the build again.

**Comment by YiLin32Wang** [comment]
Hi, I've tried the methods you've mentioned here. 
First I figured out that I haven't assign the path of the obj file so I revised the codes on that. And the codes can run in python line by line but still got `free() invalid pointer` when I use exit() or Ctrl+D to quit python, as shown here.
```
>>> from pytorch3d.utils import ico_sphere
>>> from pytorch3d.io import load_obj
>>> from pytorch3d.structures import Meshes
>>> from pytorch3d.ops import sample_points_from_meshes
>>> from pytorch3d.loss import chamfer_distance
>>> sphere_mesh = ico_sphere(level=3)
>>> file_path = "/home/yilin/Hand_est/S2Hand/pytorch3d/my_tests"
>>> verts, faces, _ = load_obj(os.path.join(file_path,"dolphin.obj"))
>>> test_mesh = Meshes(verts=[verts], faces=[faces.verts_idx])
>>> sample_sphere = sample_points_from_meshes(sphere_mesh, 5000)
>>> sample_test = sample_points_from_meshes(test_mesh, 5000)
>>> loss_chamfer, _ = chamfer_distance(sample_sphere, sample_test)
>>> 
double free or corruption (!prev)
Aborted (core dumped)
```

And then I do the rebuilding using `rm -rf build/ **/*.so` then `pip install -e .` but still got this invalid pointer error.
```
Requirement already satisfied: tabulate in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (0.8.9)
Requirement already satisfied: dataclasses in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from fvcore->pytorch3d==0.6.0) (0.8)
Requirement already satisfied: portalocker in /home/yilin/anaconda3/envs/Pytorch_py6/lib/python3.6/site-packages (from iopath->pytorch3d==0.6.0) (2.3.2)
Installing collected packages: pytorch3d
  Attempting uninstall: pytorch3d
    Found existing installation: pytorch3d 0.6.0
    Uninstalling pytorch3d-0.6.0:
      Successfully uninstalled pytorch3d-0.6.0
  Running setup.py develop for pytorch3d
Successfully installed pytorch3d-0.6.0

$ python ./my_tests/test_0.py
munmap_chunk(): invalid pointer
Aborted (core dumped)
$ python ./my_tests/test_0.py
double free or corruption (!prev)
Aborted (core dumped)
```

**Comment by YiLin32Wang** [comment]
Also, I've tried the unit tests but got the message below:

```
$ python3 -m unittest discover -p *.py
usage: python3 -m unittest discover [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                                    [-s START] [-p PATTERN] [-t TOP]
python3 -m unittest discover: error: unrecognized arguments: bm_cameras_alignment.py bm_chamfer.py bm_cubify.py bm_face_areas_normals.py bm_graph_conv.py bm_interpolate_face_attributes.py bm_iou_box3d.py bm_knn.py bm_lighting.py bm_main.py bm_marching_cubes.py bm_mesh_edge_loss.py bm_meshes.py bm_mesh_io.py bm_mesh_laplacian_smoothing.py bm_mesh_normal_consistency.py bm_mesh_rasterizer_transform.py bm_packed_to_padded.py bm_perspective_n_points.py bm_pointclouds.py bm_point_mesh_distance.py bm_points_alignment.py bm_points_to_volumes.py bm_pulsar.py bm_rasterize_meshes.py bm_rasterize_points.py bm_raymarching.py bm_raysampling.py bm_render_implicit.py bm_render_volumes.py bm_sample_farthest_points.py bm_sample_pdf.py bm_sample_points_from_meshes.py bm_se3.py bm_so3.py bm_subdivide_meshes.py bm_symeig3x3.py bm_vert_align.py common_testing.py __init__.py test_acos_linear_extrapolation.py test_ball_query.py test_blending.py test_build.py test_camera_conversions.py test_cameras_alignment.py test_cameras.py test_camera_utils.py test_chamfer.py test_common_testing.py test_common_workaround.py test_compositing.py test_cubify.py test_face_areas_normals.py test_graph_conv.py test_interpolate_face_attributes.py test_io_gltf.py test_io_obj.py test_io_off.py test_io_ply.py test_iou_box3d.py test_knn.py test_laplacian_matrices.py test_lighting.py test_marching_cubes.py test_materials.py test_mesh_edge_loss.py test_meshes.py test_mesh_filtering.py test_mesh_laplacian_smoothing.py test_mesh_normal_consistency.py test_mesh_rendering_utils.py test_ops_utils.py test_packed_to_padded.py test_perspective_n_points.py test_pointclouds.py test_point_mesh_distance.py test_points_alignment.py test_points_normals.py test_points_to_volumes.py test_r2n2.py test_rasterize_meshes.py test_rasterize_points.py test_rasterize_rectangle_images.py test_rasterizer.py test_raymarching.py test_raysampling.py test_render_implicit.py test_rendering_utils.py test_render_meshes_clipped.py test_render_meshes.py test_render_multigpu.py test_render_points.py test_render_volumes.py test_rotation_conversions.py test_sample_farthest_points.py test_sample_pdf.py test_sample_points_from_meshes.py test_se3.py test_shader.py test_shapenet_core.py test_so3.py test_struct_utils.py test_subdivide_meshes.py test_symeig3x3.py test_texturing.py test_transforms.py test_vert_align.py test_volumes.py

```

**Comment by bottler** [comment]
There's something seriously wrong with the build here, and we can't really help. Some library - probably torch or numpy or python itself - is doing something strange with allocation. It's unlikely to be a problem in any single released version of the code of any library, rather I expect the specifics of how they have been built, and used in the build of PyTorch3D, to be the problem. It might come from headers and builds being inconsistent. If you run in a debugger like gdb (or you look at the core dump with a debugger) you may be able to find out what deallocation is broken, then track it down slowly.

For the unit tests that isn't quite the right command line. Try just `python3 -m unittest discover -v -s tests ` from outside the test folder.

**Comment by YiLin32Wang** [comment]
Thanks for the reply!
I finally avoided this allocation problem by creating a new environment with python=3.8 pytorch=1.7.1 and installing pytorch3d in this new environment. :) I think there was something wrong with the python3.6 header in my previous environment.
Thanks again for the kind help:)
